import { useState } from 'react';
import { useAuth } from 'wasp/client/auth';
import { useQuery, useAction } from 'wasp/client/operations';
// @ts-ignore — generated by Wasp on next dev start
import { adminCreateUser, adminUpdateUser, adminDeleteUser, getAdminUsers } from 'wasp/client/operations';
import { Navigate } from 'react-router';
import { PageHeader } from '../../client/ui';
import {
  LuUserPlus,
  LuCircleCheck,
  LuLoader,
  LuShield,
  LuTriangleAlert,
  LuPencil,
  LuTrash2,
  LuX,
  LuCheck,
  LuUsers,
  LuBan,
} from 'react-icons/lu';

const EMPTY_FORM = { email: '', password: '', fullName: '' };
const EMPTY_EDIT = { email: '', fullName: '', status: 'active', password: '' };

export default function AdminUsersPage() {
  const { data: user } = useAuth();
  const { data: users, isLoading: usersLoading, refetch } = useQuery(getAdminUsers);
  const createUserAction = useAction(adminCreateUser);
  const updateUserAction = useAction(adminUpdateUser);
  const deleteUserAction = useAction(adminDeleteUser);

  const [form, setForm] = useState(EMPTY_FORM);
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Modal edit state
  const [editUser, setEditUser] = useState<any | null>(null);
  const [editFields, setEditFields] = useState(EMPTY_EDIT);
  const [editSaving, setEditSaving] = useState(false);
  const [editError, setEditError] = useState<string | null>(null);

  // Delete confirm modal
  const [deleteUser, setDeleteUser] = useState<any | null>(null);
  const [deleteWorking, setDeleteWorking] = useState(false);

  const isAdmin = (user as any)?.isAdmin === true;
  if (user !== undefined && !isAdmin) return <Navigate to='/tableau-de-bord' replace />;

  // ── Create ────────────────────────────────────────────────────────────────
  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);
    if (!form.email.trim() || !form.password) {
      setError('Courriel et mot de passe sont obligatoires.');
      return;
    }
    if (form.password.length < 8) {
      setError('Le mot de passe doit contenir au moins 8 caractères.');
      return;
    }
    setSubmitting(true);
    try {
      await createUserAction({
        email: form.email.trim().toLowerCase(),
        password: form.password,
        fullName: form.fullName || undefined,
      });
      setSuccess(`Compte créé pour ${form.email.trim().toLowerCase()}.`);
      setForm(EMPTY_FORM);
      // @ts-ignore
      refetch?.();
    } catch (err: any) {
      setError(err?.message || 'Une erreur est survenue.');
    } finally {
      setSubmitting(false);
    }
  };

  // ── Modal edit ────────────────────────────────────────────────────────────
  const openEdit = (u: any) => {
    setEditUser(u);
    setEditFields({ email: u.email ?? '', fullName: u.fullName ?? '', status: u.status ?? 'active', password: '' });
    setEditError(null);
  };

  const closeEdit = () => { setEditUser(null); setEditError(null); };

  const saveEdit = async (e: React.FormEvent) => {
    e.preventDefault();
    setEditError(null);
    setEditSaving(true);
    try {
      // @ts-ignore — status field added to UpdateArgs, regen on next wasp start
      await (updateUserAction as any)({
        userId: editUser.id,
        fullName: editFields.fullName,
        status: editFields.status,
        password: editFields.password || undefined,
      });
      closeEdit();
      // @ts-ignore
      refetch?.();
    } catch (err: any) {
      setEditError(err?.message || 'Erreur lors de la mise à jour.');
    } finally {
      setEditSaving(false);
    }
  };

  // ── Delete ────────────────────────────────────────────────────────────────
  const confirmDelete = async () => {
    if (!deleteUser) return;
    setDeleteWorking(true);
    try {
      await deleteUserAction({ userId: deleteUser.id });
      setDeleteUser(null);
      // @ts-ignore
      refetch?.();
    } catch (err: any) {
      setError(err?.message || 'Erreur lors de la suppression.');
      setDeleteUser(null);
    } finally {
      setDeleteWorking(false);
    }
  };

  const myId = (user as any)?.id;

  return (
    <>
      <PageHeader
        title='Gestion des utilisateurs'
        subtitle='Créez, modifiez ou supprimez les comptes de la plateforme.'
      />

      <div className='space-y-8 max-w-4xl'>

        {/* ── Create form ─────────────────────────────────────────────────── */}
        <div className='card p-6'>
          <div className='flex items-center gap-3 mb-6'>
            <div className='w-10 h-10 rounded-xl bg-accent-50 flex items-center justify-center'>
              <LuUserPlus size={20} className='text-accent' />
            </div>
            <div>
              <h2 className='font-semibold text-ink'>Créer un compte</h2>
              <p className='text-xs text-muted'>Le compte est immédiatement actif — aucune vérification par courriel.</p>
            </div>
          </div>

          {success && (
            <div className='mb-4 flex items-start gap-2 rounded-lg bg-emerald-50 border border-emerald-200 px-4 py-3 text-sm text-emerald-800'>
              <LuCircleCheck size={16} className='mt-0.5 shrink-0' />
              {success}
            </div>
          )}
          {error && (
            <div className='mb-4 flex items-start gap-2 rounded-lg bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-800'>
              <LuTriangleAlert size={16} className='mt-0.5 shrink-0' />
              {error}
            </div>
          )}

          <form onSubmit={handleCreate} className='grid sm:grid-cols-3 gap-4'>
            <div>
              <label className='label'>Courriel <span className='text-danger'>*</span></label>
              <input
                type='email'
                className='input'
                placeholder='client@exemple.com'
                value={form.email}
                onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))}
                required
                autoComplete='off'
              />
            </div>
            <div>
              <label className='label'>Nom complet <span className='text-muted font-normal'>(optionnel)</span></label>
              <input
                type='text'
                className='input'
                placeholder='Marie Tremblay'
                value={form.fullName}
                onChange={(e) => setForm((f) => ({ ...f, fullName: e.target.value }))}
                autoComplete='off'
              />
            </div>
            <div>
              <label className='label'>Mot de passe <span className='text-danger'>*</span></label>
              <input
                type='password'
                className='input'
                placeholder='8 caractères minimum'
                value={form.password}
                onChange={(e) => setForm((f) => ({ ...f, password: e.target.value }))}
                required
                minLength={8}
                autoComplete='new-password'
              />
            </div>
            <div className='sm:col-span-3 flex items-center gap-4'>
              <button type='submit' className='btn-accent justify-center py-2' disabled={submitting}>
                {submitting
                  ? <><LuLoader size={15} className='animate-spin' />Création…</>
                  : <><LuUserPlus size={15} />Créer le compte</>}
              </button>
              <p className='text-xs text-muted'>
                Le rôle est déterminé par <code className='bg-canvas-200 px-1 rounded'>ADMIN_EMAILS</code>.
              </p>
            </div>
          </form>
        </div>

        {/* ── User list ───────────────────────────────────────────────────── */}
        <div className='card overflow-hidden'>
          <div className='flex items-center gap-3 px-6 py-4 border-b border-line'>
            <LuUsers size={18} className='text-muted' />
            <h2 className='font-semibold text-ink'>Comptes existants</h2>
            {!usersLoading && (
              <span className='ml-auto text-xs text-muted'>
                {users?.length ?? 0} utilisateur{(users?.length ?? 0) !== 1 ? 's' : ''}
              </span>
            )}
          </div>

          {usersLoading ? (
            <div className='flex items-center justify-center py-14 text-muted text-sm gap-2'>
              <LuLoader size={16} className='animate-spin' /> Chargement…
            </div>
          ) : !users?.length ? (
            <div className='py-14 text-center text-muted text-sm'>Aucun utilisateur trouvé.</div>
          ) : (
            <div className='divide-y divide-line'>
              {users.map((u: any) => (
                <div key={u.id} className='px-6 py-4'>
              {(
                    // ── Normal row ───────────────────────────────────────
                    <div className='flex items-center gap-4'>
                      <div className='w-9 h-9 rounded-full bg-accent-50 text-accent-700 flex items-center justify-center font-semibold text-sm shrink-0'>
                        {(u.email || 'U').slice(0, 2).toUpperCase()}
                      </div>
                      <div className='flex-1 min-w-0'>
                        <div className='flex items-center gap-2 flex-wrap'>
                          <span className='text-sm font-medium text-ink truncate'>
                            {u.fullName || u.email}
                          </span>
                          {u.isAdmin && (
                            <span className='inline-flex items-center gap-1 text-[10px] font-semibold bg-amber-50 text-amber-700 border border-amber-200 px-1.5 py-0.5 rounded-full'>
                              <LuShield size={9} /> Admin
                            </span>
                          )}
                          {u.status === 'cancelled' ? (
                            <span className='inline-flex items-center gap-1 text-[10px] font-semibold bg-red-50 text-red-700 border border-red-200 px-1.5 py-0.5 rounded-full'>
                              <LuBan size={9} /> Suspendu
                            </span>
                          ) : (
                            <span className='inline-flex items-center gap-1 text-[10px] font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200 px-1.5 py-0.5 rounded-full'>
                              <LuCircleCheck size={9} /> Actif
                            </span>
                          )}
                        </div>
                        {u.fullName && (
                          <div className='text-xs text-muted truncate'>{u.email}</div>
                        )}
                        <div className='flex items-center gap-3 mt-0.5'>
                          {u.companyName && (
                            <span className='text-xs text-muted'>{u.companyName}</span>
                          )}
                          <span className='text-xs text-muted'>
                            {new Date(u.createdAt).toLocaleDateString('fr-CA', {
                              year: 'numeric', month: 'short', day: 'numeric',
                            })}
                          </span>
                        </div>
                      </div>
                      {u.id !== myId && (
                        <div className='flex items-center gap-1 shrink-0'>
                          <button
                            className='btn-ghost text-sm p-2'
                            title='Modifier'
                            onClick={() => openEdit(u)}
                          >
                            <LuPencil size={15} />
                          </button>
                          <button
                            className='btn-ghost text-sm p-2 text-danger hover:bg-red-50'
                            title='Supprimer'
                            onClick={() => setDeleteUser(u)}
                          >
                            <LuTrash2 size={15} />
                          </button>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>

      </div>

      {/* ── Delete modal ──────────────────────────────────────────────────── */}
      {deleteUser && (
        <div
          className='fixed inset-0 z-50 flex items-center justify-center p-4'
          style={{ background: 'rgba(10,10,11,0.5)' }}
          onClick={(e) => { if (e.target === e.currentTarget) setDeleteUser(null); }}
        >
          <div className='bg-canvas rounded-2xl shadow-2xl w-full max-w-sm'>
            <div className='flex items-center gap-3 px-6 py-4 border-b border-line'>
              <div className='w-8 h-8 rounded-lg bg-red-50 flex items-center justify-center'>
                <LuTrash2 size={15} className='text-danger' />
              </div>
              <h2 className='font-semibold text-ink flex-1'>Supprimer le compte</h2>
              <button className='btn-ghost p-1.5' onClick={() => setDeleteUser(null)} aria-label='Fermer'>
                <LuX size={16} />
              </button>
            </div>
            <div className='px-6 py-5 space-y-5'>
              <p className='text-sm text-muted leading-relaxed'>
                Vous êtes sur le point de supprimer le compte de{' '}
                <span className='font-semibold text-ink'>{deleteUser.fullName || deleteUser.email}</span>.
                Cette action est <span className='font-semibold text-danger'>irréversible</span>.
              </p>
              <div className='flex gap-3'>
                <button
                  className='btn-danger flex-1 justify-center py-2.5'
                  onClick={confirmDelete}
                  disabled={deleteWorking}
                >
                  {deleteWorking ? <LuLoader size={15} className='animate-spin' /> : <LuTrash2 size={15} />}
                  Supprimer
                </button>
                <button className='btn-ghost py-2.5 px-4' onClick={() => setDeleteUser(null)}>
                  Annuler
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── Edit modal ────────────────────────────────────────────────────── */}
      {editUser && (
        <div
          className='fixed inset-0 z-50 flex items-center justify-center p-4'
          style={{ background: 'rgba(10,10,11,0.5)' }}
          onClick={(e) => { if (e.target === e.currentTarget) closeEdit(); }}
        >
          <div className='bg-canvas rounded-2xl shadow-2xl w-full max-w-md'>
            {/* Modal header */}
            <div className='flex items-center gap-3 px-6 py-4 border-b border-line'>
              <div className='w-8 h-8 rounded-lg bg-accent-50 flex items-center justify-center'>
                <LuPencil size={15} className='text-accent' />
              </div>
              <h2 className='font-semibold text-ink flex-1'>Modifier le compte</h2>
              <button className='btn-ghost p-1.5' onClick={closeEdit} aria-label='Fermer'>
                <LuX size={16} />
              </button>
            </div>

            {/* Modal body */}
            <form onSubmit={saveEdit} className='px-6 py-5 space-y-4'>
              {editError && (
                <div className='flex items-start gap-2 rounded-lg bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-800'>
                  <LuTriangleAlert size={15} className='mt-0.5 shrink-0' />
                  {editError}
                </div>
              )}

              <div>
                <label className='label'>Courriel</label>
                <div className='input bg-canvas-200 text-muted cursor-not-allowed'>{editUser?.email}</div>
              </div>

              <div>
                <label className='label'>Nom complet</label>
                <input
                  type='text'
                  className='input'
                  placeholder='(optionnel)'
                  value={editFields.fullName}
                  onChange={(e) => setEditFields((f) => ({ ...f, fullName: e.target.value }))}
                />
              </div>

              <div>
                <label className='label'>Nouveau mot de passe <span className='text-muted font-normal'>(laisser vide pour ne pas changer)</span></label>
                <input
                  type='password'
                  className='input'
                  placeholder='8 caractères minimum'
                  value={editFields.password}
                  onChange={(e) => setEditFields((f) => ({ ...f, password: e.target.value }))}
                  minLength={8}
                  autoComplete='new-password'
                />
              </div>

              <div>
                <label className='label'>Statut du compte</label>
                <select
                  className='input'
                  value={editFields.status}
                  onChange={(e) => setEditFields((f) => ({ ...f, status: e.target.value }))}
                >
                  <option value='active'>Actif</option>
                  <option value='cancelled'>Suspendu</option>
                </select>
                {editFields.status === 'cancelled' && (
                  <p className='mt-1.5 text-xs text-red-600 flex items-center gap-1'>
                    <LuBan size={11} /> L'utilisateur ne pourra plus accéder à la plateforme.
                  </p>
                )}
              </div>

              <div className='flex gap-3 pt-2'>
                <button type='submit' className='btn-accent flex-1 justify-center py-2.5' disabled={editSaving}>
                  {editSaving ? <LuLoader size={15} className='animate-spin' /> : <LuCheck size={15} />}
                  Enregistrer
                </button>
                <button type='button' className='btn-ghost py-2.5 px-4' onClick={closeEdit}>
                  Annuler
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </>
  );
}

