import { useState } from 'react';
import { useAuth } from 'wasp/client/auth';
import { useQuery, useAction } from 'wasp/client/operations';
// @ts-ignore — generated by Wasp on next dev start
import { adminCreateUser, adminUpdateUser, adminDeleteUser, getAdminUsers } from 'wasp/client/operations';
import { Navigate } from 'react-router';
import { PageHeader } from '../../client/ui';
import {
  LuUserPlus,
  LuCircleCheck,
  LuLoader,
  LuShield,
  LuTriangleAlert,
  LuPencil,
  LuTrash2,
  LuX,
  LuCheck,
  LuUsers,
} from 'react-icons/lu';

const EMPTY_FORM = { email: '', password: '', fullName: '' };

export default function AdminUsersPage() {
  const { data: user } = useAuth();
  const { data: users, isLoading: usersLoading, refetch } = useQuery(getAdminUsers);
  const createUserAction = useAction(adminCreateUser);
  const updateUserAction = useAction(adminUpdateUser);
  const deleteUserAction = useAction(adminDeleteUser);

  const [form, setForm] = useState(EMPTY_FORM);
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Inline edit state
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editFields, setEditFields] = useState({ email: '', fullName: '' });
  const [editSaving, setEditSaving] = useState(false);
  const [editError, setEditError] = useState<string | null>(null);

  // Delete confirm
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [deleteWorking, setDeleteWorking] = useState(false);

  const isAdmin = (user as any)?.role === 'admin' || (user as any)?.isAdmin;
  if (user !== undefined && !isAdmin) return <Navigate to='/tableau-de-bord' replace />;

  // ── Create ────────────────────────────────────────────────────────────────
  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);
    if (!form.email.trim() || !form.password) {
      setError('Courriel et mot de passe sont obligatoires.');
      return;
    }
    if (form.password.length < 8) {
      setError('Le mot de passe doit contenir au moins 8 caractères.');
      return;
    }
    setSubmitting(true);
    try {
      await createUserAction({
        email: form.email.trim().toLowerCase(),
        password: form.password,
        fullName: form.fullName || undefined,
      });
      setSuccess(`Compte créé pour ${form.email.trim().toLowerCase()}.`);
      setForm(EMPTY_FORM);
      // @ts-ignore
      refetch?.();
    } catch (err: any) {
      setError(err?.message || 'Une erreur est survenue.');
    } finally {
      setSubmitting(false);
    }
  };

  // ── Edit ──────────────────────────────────────────────────────────────────
  const startEdit = (u: any) => {
    setEditingId(u.id);
    setEditFields({ email: u.email ?? '', fullName: u.fullName ?? '' });
    setEditError(null);
  };

  const cancelEdit = () => { setEditingId(null); setEditError(null); };

  const saveEdit = async (userId: string) => {
    setEditError(null);
    setEditSaving(true);
    try {
      await updateUserAction({ userId, email: editFields.email, fullName: editFields.fullName });
      setEditingId(null);
      // @ts-ignore
      refetch?.();
    } catch (err: any) {
      setEditError(err?.message || 'Erreur lors de la mise à jour.');
    } finally {
      setEditSaving(false);
    }
  };

  // ── Delete ────────────────────────────────────────────────────────────────
  const confirmDelete = async (userId: string) => {
    setDeleteWorking(true);
    try {
      await deleteUserAction({ userId });
      setDeletingId(null);
      // @ts-ignore
      refetch?.();
    } catch (err: any) {
      setError(err?.message || 'Erreur lors de la suppression.');
      setDeletingId(null);
    } finally {
      setDeleteWorking(false);
    }
  };

  return (
    <>
      <PageHeader
        title='Gestion des utilisateurs'
        subtitle='Créez, modifiez ou supprimez les comptes de la plateforme.'
      />

      <div className='space-y-8 max-w-4xl'>

        {/* ── Create form ─────────────────────────────────────────────────── */}
        <div className='card p-6'>
          <div className='flex items-center gap-3 mb-6'>
            <div className='w-10 h-10 rounded-xl bg-accent-50 flex items-center justify-center'>
              <LuUserPlus size={20} className='text-accent' />
            </div>
            <div>
              <h2 className='font-semibold text-ink'>Créer un compte</h2>
              <p className='text-xs text-muted'>Le compte est immédiatement actif — aucune vérification par courriel.</p>
            </div>
          </div>

          {success && (
            <div className='mb-4 flex items-start gap-2 rounded-lg bg-emerald-50 border border-emerald-200 px-4 py-3 text-sm text-emerald-800'>
              <LuCircleCheck size={16} className='mt-0.5 shrink-0' />
              {success}
            </div>
          )}
          {error && (
            <div className='mb-4 flex items-start gap-2 rounded-lg bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-800'>
              <LuTriangleAlert size={16} className='mt-0.5 shrink-0' />
              {error}
            </div>
          )}

          <form onSubmit={handleCreate} className='grid sm:grid-cols-3 gap-4'>
            <div>
              <label className='label'>Courriel <span className='text-danger'>*</span></label>
              <input
                type='email'
                className='input'
                placeholder='client@exemple.com'
                value={form.email}
                onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))}
                required
                autoComplete='off'
              />
            </div>
            <div>
              <label className='label'>Nom complet <span className='text-muted font-normal'>(optionnel)</span></label>
              <input
                type='text'
                className='input'
                placeholder='Marie Tremblay'
                value={form.fullName}
                onChange={(e) => setForm((f) => ({ ...f, fullName: e.target.value }))}
                autoComplete='off'
              />
            </div>
            <div>
              <label className='label'>Mot de passe <span className='text-danger'>*</span></label>
              <input
                type='password'
                className='input'
                placeholder='8 caractères minimum'
                value={form.password}
                onChange={(e) => setForm((f) => ({ ...f, password: e.target.value }))}
                required
                minLength={8}
                autoComplete='new-password'
              />
            </div>
            <div className='sm:col-span-3 flex items-center gap-4'>
              <button type='submit' className='btn-accent justify-center py-2' disabled={submitting}>
                {submitting
                  ? <><LuLoader size={15} className='animate-spin' />Création…</>
                  : <><LuUserPlus size={15} />Créer le compte</>}
              </button>
              <p className='text-xs text-muted'>
                Le rôle est déterminé par <code className='bg-canvas-200 px-1 rounded'>ADMIN_EMAILS</code>.
              </p>
            </div>
          </form>
        </div>

        {/* ── User list ───────────────────────────────────────────────────── */}
        <div className='card overflow-hidden'>
          <div className='flex items-center gap-3 px-6 py-4 border-b border-line'>
            <LuUsers size={18} className='text-muted' />
            <h2 className='font-semibold text-ink'>Comptes existants</h2>
            {!usersLoading && (
              <span className='ml-auto text-xs text-muted'>
                {users?.length ?? 0} utilisateur{(users?.length ?? 0) !== 1 ? 's' : ''}
              </span>
            )}
          </div>

          {usersLoading ? (
            <div className='flex items-center justify-center py-14 text-muted text-sm gap-2'>
              <LuLoader size={16} className='animate-spin' /> Chargement…
            </div>
          ) : !users?.length ? (
            <div className='py-14 text-center text-muted text-sm'>Aucun utilisateur trouvé.</div>
          ) : (
            <div className='divide-y divide-line'>
              {users.map((u: any) => (
                <div key={u.id} className='px-6 py-4'>
                  {editingId === u.id ? (
                    // ── Inline edit row ──────────────────────────────────
                    <div className='space-y-3'>
                      {editError && (
                        <p className='text-xs text-red-600 flex items-center gap-1'>
                          <LuTriangleAlert size={13} /> {editError}
                        </p>
                      )}
                      <div className='grid sm:grid-cols-2 gap-3'>
                        <div>
                          <label className='label text-xs'>Courriel</label>
                          <input
                            type='email'
                            className='input text-sm py-1.5'
                            value={editFields.email}
                            onChange={(e) => setEditFields((f) => ({ ...f, email: e.target.value }))}
                          />
                        </div>
                        <div>
                          <label className='label text-xs'>Nom complet</label>
                          <input
                            type='text'
                            className='input text-sm py-1.5'
                            value={editFields.fullName}
                            onChange={(e) => setEditFields((f) => ({ ...f, fullName: e.target.value }))}
                          />
                        </div>
                      </div>
                      <div className='flex gap-2'>
                        <button
                          className='btn-accent text-sm py-1.5 px-3'
                          onClick={() => saveEdit(u.id)}
                          disabled={editSaving}
                        >
                          {editSaving ? <LuLoader size={14} className='animate-spin' /> : <LuCheck size={14} />}
                          Enregistrer
                        </button>
                        <button className='btn-ghost text-sm py-1.5 px-3' onClick={cancelEdit}>
                          <LuX size={14} /> Annuler
                        </button>
                      </div>
                    </div>
                  ) : deletingId === u.id ? (
                    // ── Delete confirm row ───────────────────────────────
                    <div className='flex items-center gap-3 flex-wrap'>
                      <LuTriangleAlert size={16} className='text-amber-500 shrink-0' />
                      <span className='text-sm'>
                        Supprimer <strong>{u.email}</strong> ? Cette action est irréversible.
                      </span>
                      <div className='flex gap-2 ml-auto'>
                        <button
                          className='btn-danger text-sm py-1.5 px-3'
                          onClick={() => confirmDelete(u.id)}
                          disabled={deleteWorking}
                        >
                          {deleteWorking ? <LuLoader size={14} className='animate-spin' /> : <LuTrash2 size={14} />}
                          Supprimer
                        </button>
                        <button className='btn-ghost text-sm py-1.5 px-3' onClick={() => setDeletingId(null)}>
                          <LuX size={14} /> Annuler
                        </button>
                      </div>
                    </div>
                  ) : (
                    // ── Normal row ───────────────────────────────────────
                    <div className='flex items-center gap-4'>
                      <div className='w-9 h-9 rounded-full bg-accent-50 text-accent-700 flex items-center justify-center font-semibold text-sm shrink-0'>
                        {(u.email || 'U').slice(0, 2).toUpperCase()}
                      </div>
                      <div className='flex-1 min-w-0'>
                        <div className='text-sm font-medium text-ink truncate'>
                          {u.fullName || u.email}
                          {u.isAdmin && (
                            <span className='ml-2 inline-flex items-center gap-1 text-[10px] font-semibold bg-amber-50 text-amber-700 border border-amber-200 px-1.5 py-0.5 rounded-full'>
                              <LuShield size={9} /> Admin
                            </span>
                          )}
                        </div>
                        {u.fullName && (
                          <div className='text-xs text-muted truncate'>{u.email}</div>
                        )}
                        <div className='flex items-center gap-3 mt-0.5'>
                          {u.companyName && (
                            <span className='text-xs text-muted'>{u.companyName}</span>
                          )}
                          <span className='text-xs text-muted'>
                            {new Date(u.createdAt).toLocaleDateString('fr-CA', {
                              year: 'numeric', month: 'short', day: 'numeric',
                            })}
                          </span>
                        </div>
                      </div>
                      <div className='flex items-center gap-1 shrink-0'>
                        <button
                          className='btn-ghost text-sm p-2'
                          title='Modifier'
                          onClick={() => startEdit(u)}
                        >
                          <LuPencil size={15} />
                        </button>
                        {u.id !== (user as any)?.id && (
                          <button
                            className='btn-ghost text-sm p-2 text-danger hover:bg-red-50'
                            title='Supprimer'
                            onClick={() => setDeletingId(u.id)}
                          >
                            <LuTrash2 size={15} />
                          </button>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>

        <div className='flex items-center gap-2 px-3 py-2 rounded-lg bg-amber-50 border border-amber-200 text-amber-800 text-xs w-fit'>
          <LuShield size={13} />
          <span>Accès administrateur uniquement</span>
        </div>

      </div>
    </>
  );
}
