// The `DocumentLifecycleSweep` type is generated by Wasp from the `job`
// declaration in main.wasp.
import type { DocumentLifecycleSweep } from 'wasp/server/jobs';

/**
 * Recurring sweep that advances document statuses based on time:
 *   - quotes in 'envoyee' past dueDate              → 'expiree'
 *   - invoices in 'envoyee' or 'acompte_recu'
 *     past dueDate                                  → 'en_retard'
 *
 * Both document types use the single "date d'échéance" (`dueDate`) field as
 * the expiry trigger. Logs an ActivityLog row per transition so users see
 * the change in the client timeline. Designed to be idempotent:
 * re-running it on rows already in their target state is a no-op.
 *
 * Future extension point: emit emails (e.g. "your quote expired") right after
 * the status flip. The activity row already captures who/when so any email
 * sender can dedupe against it.
 */
export const sweepDocumentLifecycles: DocumentLifecycleSweep<
  Record<string, never>,
  { expired: number; overdue: number }
> = async (_args, context) => {
  const now = new Date();

  const [quotesToExpire, invoicesToFlag] = await Promise.all([
    context.entities.Document.findMany({
      where: {
        type: 'quote',
        status: 'envoyee',
        statusLocked: false,
        dueDate: { lt: now, not: null },
      },
      select: { id: true, companyId: true, clientId: true, number: true },
    }),
    context.entities.Document.findMany({
      where: {
        type: 'invoice',
        status: { in: ['envoyee', 'acompte_recu'] },
        dueDate: { lt: now, not: null },
      },
      select: { id: true, companyId: true, clientId: true, number: true, status: true },
    }),
  ]);

  const ops: Promise<unknown>[] = [];

  for (const q of quotesToExpire) {
    ops.push(
      context.entities.Document.update({ where: { id: q.id }, data: { status: 'expiree' } }),
      context.entities.ActivityLog.create({
        data: {
          companyId: q.companyId,
          clientId: q.clientId,
          documentId: q.id,
          type: 'document.status_changed',
          message: `Soumission ${q.number} expirée automatiquement (date d'échéance dépassée)`,
          metadata: { from: 'envoyee', to: 'expiree', reason: 'auto_expire' },
        },
      }),
    );
  }

  for (const inv of invoicesToFlag) {
    ops.push(
      context.entities.Document.update({ where: { id: inv.id }, data: { status: 'en_retard' } }),
      context.entities.ActivityLog.create({
        data: {
          companyId: inv.companyId,
          clientId: inv.clientId,
          documentId: inv.id,
          type: 'document.status_changed',
          message: `Facture ${inv.number} marquée en retard (date d'échéance dépassée)`,
          metadata: { from: inv.status, to: 'en_retard', reason: 'auto_overdue' },
        },
      }),
    );
  }

  if (ops.length) await Promise.all(ops);

  return { expired: quotesToExpire.length, overdue: invoicesToFlag.length };
};
