import { useState, useRef, useEffect, useCallback, useMemo } from 'react';
import { createPortal } from 'react-dom';
import {
  useQuery,
  useAction,
  getCompanyBrandAssets,
  getCurrentCompany,
  getClientDetail,
  generateTemplateContent,
} from 'wasp/client/operations';
// @ts-ignore — generated by wasp after next build
import { updateClientFileDynamicVars } from 'wasp/client/operations';
import MDEditor from '@uiw/react-md-editor';
import toast from 'react-hot-toast';
import { LuX, LuEye, LuWand, LuSave, LuChevronLeft, LuChevronRight, LuCopy, LuSlidersHorizontal } from 'react-icons/lu';
import { TEMPLATE_VARIABLE_GROUPS, getTemplatePdfBase64, TEMPLATE_TYPES } from '../settings/templatePdf';
import type { BrandAssets } from '../documents/pdf';
import type { EditorFileInfo } from '../projects/FileEditorModal';

interface Props {
  file: EditorFileInfo;
  onClose: () => void;
  fetchContent: (id: string) => Promise<{ type: 'text'; content: string }>;
  saveContent: (id: string, content: string, contentType: 'text') => Promise<any>;
  onNavigate?: (dir: 'prev' | 'next') => void;
  hasPrev?: boolean;
  hasNext?: boolean;
  clientId?: string | null;
  /** Raw JSON string from ClientFile.dynamicVars — mutable, refreshed after edits */
  dynamicVars?: string | null;
  onDynamicVarsUpdated?: (newJson: string) => void;
}

// Strip `.md` extension for display
function displayName(name: string) {
  return name.endsWith('.md') ? name.slice(0, -3) : name;
}

// ─── EditDynamicVarsModal ─────────────────────────────────────────────────────

interface EditVarsProps {
  fileId: string;
  resolvedValues: Record<string, string>;
  storedOverrides: Record<string, string>;
  onSave: (newJson: string) => void;
  onClose: () => void;
}

function EditDynamicVarsModal({ fileId, resolvedValues, storedOverrides, onSave, onClose }: EditVarsProps) {
  const [values, setValues] = useState<Record<string, string>>(() => {
    // Start from resolved values so every field is pre-filled
    return { ...resolvedValues, ...storedOverrides };
  });
  const [saving, setSaving] = useState(false);
  const updateVars = useAction(updateClientFileDynamicVars);

  const handleSave = async () => {
    setSaving(true);
    try {
      // Only persist non-empty overrides
      const toSave: Record<string, string> = {};
      for (const [k, v] of Object.entries(values)) {
        if (v.trim()) toSave[k] = v.trim();
      }
      await updateVars({ id: fileId, vars: toSave });
      onSave(JSON.stringify(toSave));
      toast.success('Variables sauvegardées');
      onClose();
    } catch (e: any) {
      toast.error(e?.message || 'Erreur de sauvegarde');
    } finally {
      setSaving(false);
    }
  };

  return createPortal(
    <div className='fixed inset-0 bg-ink/50 backdrop-blur-sm z-[70] flex items-center justify-center p-4' onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className='bg-white rounded-2xl shadow-2xl w-full max-w-lg flex flex-col max-h-[85vh] overflow-hidden'>
        <div className='shrink-0 px-5 py-4 border-b border-line flex items-center justify-between'>
          <div className='flex items-center gap-2'>
            <LuSlidersHorizontal size={16} className='text-primary' />
            <h2 className='font-semibold text-ink'>Modifier les variables</h2>
          </div>
          <button onClick={onClose} className='text-muted hover:text-ink p-1'><LuX size={16} /></button>
        </div>
        <p className='px-5 py-3 text-xs text-muted border-b border-line'>
          Ces valeurs sont sauvegardées dans la fiche. Elles remplacent les valeurs automatiques lors de l'insertion des variables dans l'éditeur.
        </p>
        <div className='flex-1 overflow-y-auto px-5 py-4 flex flex-col gap-5'>
          {TEMPLATE_VARIABLE_GROUPS.map((group) => (
            <div key={group.group}>
              <p className='text-xs font-semibold text-muted uppercase tracking-wide mb-2'>{group.group}</p>
              <div className='flex flex-col gap-2'>
                {group.vars.map((v) => (
                  <div key={v.key} className='flex flex-col gap-0.5'>
                    <label className='text-xs font-medium text-ink flex items-center gap-1.5'>
                      <span className={`inline-block w-1.5 h-1.5 rounded-full shrink-0 ${(values[v.key] ?? '').trim() ? 'bg-emerald-400' : 'bg-amber-400'}`} />
                      {v.label}
                      <span className='font-mono text-[10px] text-muted ml-0.5'>{v.key}</span>
                    </label>
                    <input
                      className='input text-sm'
                      value={values[v.key] ?? ''}
                      onChange={(e) => setValues((prev) => ({ ...prev, [v.key]: e.target.value }))}
                      placeholder={v.sample}
                    />
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
        <div className='shrink-0 px-5 py-3 border-t border-line flex justify-end gap-2 bg-canvas-50'>
          <button className='btn-ghost' onClick={onClose}>Annuler</button>
          <button className='btn-primary flex items-center gap-1.5' onClick={handleSave} disabled={saving}>
            <LuSave size={14} />
            {saving ? 'Sauvegarde…' : 'Sauvegarder'}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}

export function ClientDocEditorModal({ file, onClose, fetchContent, saveContent, onNavigate, hasPrev, hasNext, clientId, dynamicVars, onDynamicVarsUpdated }: Props) {
  const { data: brand } = useQuery(getCompanyBrandAssets);
  const { data: company } = useQuery(getCurrentCompany);
  const { data: clientDetail } = useQuery(getClientDetail, clientId ? { clientId } : undefined as any, { enabled: !!clientId } as any);
  const generateContent = useAction(generateTemplateContent);
  const updateDynVars = useAction(updateClientFileDynamicVars);

  const [showVarEditor, setShowVarEditor] = useState(() => !!file.openVarEditor);

  const type = file.sourceTemplateType ?? 'autre';
  const typeLabel = TEMPLATE_TYPES.find((t) => t.value === type)?.label ?? type;

  const [content, setContent] = useState('');
  const [loadError, setLoadError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [dirty, setDirty] = useState(false);

  const [previewing, setPreviewing] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);

  const [aiOpen, setAiOpen] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiLoading, setAiLoading] = useState(false);

  const mdEditorRef = useRef<{ textarea?: HTMLTextAreaElement }>(null);

  // Parsed stored overrides (from dynamicVars JSON prop)
  const storedOverrides = useMemo<Record<string, string>>(() => {
    if (!dynamicVars) return {};
    try { return JSON.parse(dynamicVars); } catch { return {}; }
  }, [dynamicVars]);

  // Resolved variable values — auto-filled from client/company, overridden by storedOverrides
  const resolvedValues = useMemo<Record<string, string>>(() => {
    const today = new Date().toLocaleDateString('fr-CA', { day: 'numeric', month: 'long', year: 'numeric' });
    const c = clientDetail as any;
    const co = company as any;
    const clientAddress = [c?.address, c?.city, c?.province, c?.postalCode].filter(Boolean).join(', ');
    const companyAddress = [co?.address, co?.city, co?.province, co?.postalCode].filter(Boolean).join(', ');
    return {
      '{{date}}':            today,
      '{{date_expiry}}':     '',
      '{{client.name}}':    c ? (c.contactName ?? c.name ?? '') : '',
      '{{client.company}}': c?.name ?? '',
      '{{client.email}}':   c?.email ?? '',
      '{{client.phone}}':   c?.phone ?? '',
      '{{client.address}}': clientAddress,
      '{{company.name}}':    co?.name ?? '',
      '{{company.email}}':   co?.email ?? '',
      '{{company.phone}}':   co?.phone ?? '',
      '{{company.address}}': companyAddress,
      '{{company.neq}}':     co?.neq ?? '',
      '{{company.tps}}':     co?.taxNumberGst ?? '',
      '{{company.tvq}}':     co?.taxNumberQst ?? '',
      '{{payment.link}}':    '',
      // Stored overrides win over auto-resolved values
      ...storedOverrides,
    };
  }, [clientDetail, company, storedOverrides]);

  // Load content from S3 on mount / when file changes
  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setLoadError(null);
    setContent('');
    setDirty(false);
    if (previewUrl) { URL.revokeObjectURL(previewUrl); setPreviewUrl(null); }
    fetchContent(file.id).then((res) => {
      if (!cancelled) {
        setContent(res.type === 'text' ? res.content : '');
        setLoading(false);
      }
    }).catch((e: any) => {
      if (!cancelled) { setLoadError(e?.message || 'Erreur de chargement'); setLoading(false); }
    });
    return () => { cancelled = true; };
  }, [file.id]);

  // Cleanup preview blob on unmount
  useEffect(() => {
    return () => { if (previewUrl) URL.revokeObjectURL(previewUrl); };
  }, [previewUrl]);

  // Auto-close PDF preview when content changes
  useEffect(() => {
    if (previewUrl) { URL.revokeObjectURL(previewUrl); setPreviewUrl(null); }
  }, [content]);

  const insertVariable = useCallback((key: string) => {
    // Insert resolved value when available, else insert the {{key}} placeholder
    const toInsert = resolvedValues[key] && resolvedValues[key].trim() ? resolvedValues[key] : key;
    const el = mdEditorRef.current?.textarea;
    if (!el) { setContent((c) => c + toInsert); return; }
    el.focus();
    const scrollTop = el.scrollTop;
    const inserted = document.execCommand('insertText', false, toInsert);
    if (!inserted) {
      const start = el.selectionStart;
      const end = el.selectionEnd;
      setContent(content.slice(0, start) + toInsert + content.slice(end));
      setTimeout(() => {
        el.focus();
        el.setSelectionRange(start + toInsert.length, start + toInsert.length);
        el.scrollTop = scrollTop;
      }, 0);
    } else {
      setContent(el.value);
      requestAnimationFrame(() => { el.scrollTop = scrollTop; });
    }
    setDirty(true);
  }, [content, resolvedValues]);

  const handlePreview = async () => {
    if (previewing) return;
    setPreviewing(true);
    try {
      if (previewUrl) URL.revokeObjectURL(previewUrl);
      const b64 = await getTemplatePdfBase64(
        { name: displayName(file.name), type, description: null, content },
        (brand as BrandAssets) ?? null,
        (company as any)?.name ?? 'Mon Entreprise',
      );
      const bytes = atob(b64);
      const arr = new Uint8Array(bytes.length);
      for (let i = 0; i < bytes.length; i++) arr[i] = bytes.charCodeAt(i);
      setPreviewUrl(URL.createObjectURL(new Blob([arr], { type: 'application/pdf' })));
    } catch (e: any) {
      toast.error(e?.message || 'Erreur lors de la génération du PDF');
    } finally {
      setPreviewing(false);
    }
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveContent(file.id, content, 'text');
      setDirty(false);
      toast.success('Document sauvegardé');
    } catch (e: any) {
      toast.error(e?.message || 'Erreur de sauvegarde');
    } finally {
      setSaving(false);
    }
  };

  const handleGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setAiLoading(true);
    try {
      const hasContent = content.trim().length > 0;
      const res = await generateContent({ description: aiPrompt.trim(), type, currentContent: hasContent ? content : undefined }) as { markdown: string };
      setContent(res.markdown);
      setDirty(true);
      setAiOpen(false);
      setAiPrompt('');
      toast.success(hasContent ? 'Document mis à jour !' : 'Contenu généré !');
    } catch (e: any) {
      toast.error(e?.message || 'Erreur de génération IA');
    } finally {
      setAiLoading(false);
    }
  };

  const handleKeyDown = useCallback((e: KeyboardEvent) => {
    if ((e.metaKey || e.ctrlKey) && e.key === 's') {
      e.preventDefault();
      if (!saving && dirty) handleSave();
    }
    if (e.key === 'Escape' && !aiOpen) onClose();
  }, [saving, dirty, aiOpen]);

  useEffect(() => {
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  return <>
  {createPortal(
    <div className='fixed inset-0 bg-ink/40 backdrop-blur-sm z-[60] flex items-center justify-center p-4'>
      <div
        className='bg-white rounded-2xl shadow-2xl flex flex-col w-full max-w-6xl max-h-[92vh] overflow-hidden'
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className='shrink-0 px-5 py-3 border-b border-line flex items-center gap-3'>
          {/* Prev/next */}
          {onNavigate && (
            <div className='flex items-center gap-1 shrink-0'>
              <button onClick={() => onNavigate('prev')} disabled={!hasPrev} className='p-1 rounded hover:bg-canvas-200 disabled:opacity-30'><LuChevronLeft size={16} /></button>
              <button onClick={() => onNavigate('next')} disabled={!hasNext} className='p-1 rounded hover:bg-canvas-200 disabled:opacity-30'><LuChevronRight size={16} /></button>
            </div>
          )}
          <span className='flex-1 font-semibold text-lg text-ink truncate'>{displayName(file.name)}</span>
          {/* Type badge */}
          <span className='shrink-0 text-[10px] font-semibold px-2 py-0.5 rounded-full bg-primary/10 text-primary'>
            {typeLabel}
          </span>
          {dirty && (
            <span className='shrink-0 text-[10px] text-muted border border-line rounded px-1.5 py-0.5'>Non sauvegardé</span>
          )}
          {/* Edit dynamic vars */}
          <button
            onClick={() => setShowVarEditor(true)}
            title='Modifier les variables dynamiques'
            className='shrink-0 p-1.5 rounded hover:bg-canvas-200 text-muted hover:text-ink'
          >
            <LuSlidersHorizontal size={16} />
          </button>
          <button onClick={onClose} className='text-muted hover:text-ink p-1 shrink-0' aria-label='Fermer'>
            <LuX size={18} />
          </button>
        </div>

        {/* Body */}
        {loading ? (
          <div className='flex-1 flex items-center justify-center text-sm text-muted'>Chargement…</div>
        ) : loadError ? (
          <div className='flex-1 flex items-center justify-center text-sm text-red-500'>{loadError}</div>
        ) : (
          <div className='flex flex-1 min-h-0 overflow-hidden'>
            {/* Editor panel */}
            <div className='flex flex-col flex-1 min-w-0 border-r border-line'>
              <div className='flex-1 min-h-0 overflow-auto relative' data-color-mode='light'>
                <MDEditor
                  ref={mdEditorRef as any}
                  value={content}
                  onChange={(v) => { setContent(v ?? ''); setDirty(true); }}
                  preview='edit'
                  hideToolbar={false}
                  height='100%'
                  visibleDragbar={false}
                  style={{ height: '100%', borderRadius: 0, border: 'none', boxShadow: 'none' }}
                  textareaProps={{ placeholder: 'Rédigez votre document en Markdown…', spellCheck: false }}
                />
                {/* AI button */}
                <button
                  onClick={() => setAiOpen((v) => !v)}
                  title="Générer / modifier avec l'IA"
                  className='absolute bottom-3 right-3 z-10 flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-amber-500 text-white text-xs font-semibold shadow-lg hover:bg-amber-600 transition-colors'
                >
                  <LuWand size={13} /> IA
                </button>
                {/* AI popover */}
                {aiOpen && (() => {
                  const hasContent = content.trim().length > 0;
                  return (
                    <div className='absolute bottom-12 right-3 z-20 w-80 bg-white rounded-xl shadow-2xl border border-line p-4 flex flex-col gap-3'>
                      <div className='flex items-center justify-between'>
                        <div className='flex items-center gap-1.5'>
                          <LuWand size={14} className='text-amber-500' />
                          <p className='text-sm font-semibold'>{hasContent ? "Modifier avec l'IA" : "Générer avec l'IA"}</p>
                        </div>
                        <button onClick={() => setAiOpen(false)} className='text-muted hover:text-ink'><LuX size={14} /></button>
                      </div>
                      <p className='text-xs text-muted'>
                        {hasContent
                          ? "Décrivez la modification souhaitée. L'IA conservera le reste du document intact."
                          : "Décrivez le document souhaité. L'IA utilisera les variables dynamiques."}
                      </p>
                      <textarea
                        className='border border-line rounded-lg p-2.5 text-sm resize-none h-24 outline-none focus:ring-2 focus:ring-amber-400 focus:border-amber-400'
                        placeholder={hasContent
                          ? 'Ex : Ajoute une section sur la propriété intellectuelle…'
                          : 'Ex : Contrat de maintenance mensuelle pour site WordPress, 6 mois…'}
                        value={aiPrompt}
                        onChange={(e) => setAiPrompt(e.target.value)}
                        onKeyDown={(e) => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) handleGenerate(); }}
                        autoFocus
                      />
                      <p className='text-xs text-muted/70'>Type actif : <span className='font-medium text-ink'>{typeLabel}</span></p>
                      <div className='flex justify-end gap-2'>
                        <button className='btn-ghost text-xs' onClick={() => setAiOpen(false)}>Annuler</button>
                        <button
                          className='flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-amber-500 text-white text-xs font-semibold hover:bg-amber-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                          onClick={handleGenerate}
                          disabled={aiLoading || !aiPrompt.trim()}
                        >
                          {aiLoading ? (
                            <><span className='animate-spin inline-block w-3 h-3 border-2 border-white/40 border-t-white rounded-full' /> {hasContent ? 'Modification…' : 'Génération…'}</>
                          ) : (
                            <><LuWand size={12} /> {hasContent ? 'Modifier' : 'Générer'}</>
                          )}
                        </button>
                      </div>
                    </div>
                  );
                })()}
              </div>
            </div>

            {/* Variables sidebar */}
            <div className='w-56 shrink-0 flex flex-col overflow-y-auto border-r border-line bg-canvas-50'>
              <div className='px-3 py-2.5 border-b border-line'>
                <p className='text-xs font-semibold text-muted uppercase tracking-wide'>Variables</p>
                <p className='text-xs text-muted mt-0.5'>Cliquez pour insérer</p>
              </div>
              <div className='flex items-center gap-3 px-3 py-2 border-b border-line'>
                <span className='flex items-center gap-1 text-[10px] text-muted'>
                  <span className='inline-block w-1.5 h-1.5 rounded-full bg-emerald-400' />
                  Valeur disponible
                </span>
                <span className='flex items-center gap-1 text-[10px] text-muted'>
                  <span className='inline-block w-1.5 h-1.5 rounded-full bg-amber-400' />
                  Valeur manquante
                </span>
              </div>
              <div className='flex-1 overflow-y-auto py-1'>
                {TEMPLATE_VARIABLE_GROUPS.map((group) => (
                  <div key={group.group} className='mb-1'>
                    <p className='px-3 py-1.5 text-xs font-medium text-muted uppercase tracking-wide'>{group.group}</p>
                    {group.vars.map((v) => {
                      const resolved = resolvedValues[v.key];
                      const hasValue = !!resolved && resolved.trim().length > 0;
                      return (
                        <button
                          key={v.key}
                          onClick={() => insertVariable(v.key)}
                          title={hasValue ? `Valeur : ${resolved}` : `Aucune valeur — insère le marqueur ${v.key}`}
                          className='w-full flex items-start gap-2 px-3 py-1.5 text-left hover:bg-canvas-100 group'
                        >
                          <span className={`inline-block w-1.5 h-1.5 rounded-full shrink-0 mt-1 ${hasValue ? 'bg-emerald-400' : 'bg-amber-400'}`} />
                          <span className='flex flex-col flex-1 min-w-0'>
                            <span className='text-xs text-ink truncate'>{v.label}</span>
                            {hasValue && (
                              <span className='text-[10px] text-muted truncate'>{resolved}</span>
                            )}
                          </span>
                          <LuCopy size={10} className='text-muted opacity-0 group-hover:opacity-100 shrink-0 ml-1 mt-1' />
                        </button>
                      );
                    })}
                  </div>
                ))}
              </div>
            </div>

            {/* PDF preview panel */}
            {previewUrl && (
              <div className='w-[45%] shrink-0 flex flex-col border-l border-line bg-canvas-50'>
                <div className='px-3 py-2.5 border-b border-line flex items-center justify-between'>
                  <p className='text-xs font-semibold text-muted'>Aperçu PDF</p>
                  <div className='flex items-center gap-2'>
                    <a
                      href={previewUrl}
                      download={`${displayName(file.name)}.pdf`}
                      className='text-xs text-primary hover:underline'
                    >
                      Télécharger
                    </a>
                    <button onClick={() => { URL.revokeObjectURL(previewUrl); setPreviewUrl(null); }} className='text-muted hover:text-ink'>
                      <LuX size={14} />
                    </button>
                  </div>
                </div>
                <iframe src={previewUrl} className='flex-1 w-full' title='Aperçu PDF' />
              </div>
            )}
          </div>
        )}

        {/* Footer */}
        <div className='shrink-0 px-5 py-3 border-t border-line flex justify-between items-center bg-canvas-50'>
          <p className='text-xs text-muted'>
            Markdown · <kbd className='bg-canvas-200 px-1 rounded text-[10px]'>⌘S</kbd> pour sauvegarder
          </p>
          <div className='flex gap-2'>
            <button className='btn-ghost' onClick={onClose}>Fermer</button>
            <button
              className='btn-secondary flex items-center gap-1.5'
              onClick={handlePreview}
              disabled={previewing || loading}
            >
              <LuEye size={14} />
              {previewing ? 'Génération…' : 'Aperçu PDF'}
            </button>
            <button
              className='btn-primary flex items-center gap-1.5'
              onClick={handleSave}
              disabled={saving || loading || !dirty}
            >
              <LuSave size={14} />
              {saving ? 'Sauvegarde…' : 'Sauvegarder'}
            </button>
          </div>
        </div>
      </div>
    </div>,
    document.body,
  )}
  {showVarEditor && (
    <EditDynamicVarsModal
      fileId={file.id}
      resolvedValues={resolvedValues}
      storedOverrides={storedOverrides}
      onSave={(newJson) => { onDynamicVarsUpdated?.(newJson); }}
      onClose={() => setShowVarEditor(false)}
    />
  )}
  </>;
}

// ─── Standalone wrapper — used from SharedFileManager right-click ─────────────

export interface StandaloneEditVarsProps {
  fileId: string;
  clientId: string | null;
  dynamicVars: string | null;
  onSave: (newJson: string) => void;
  onClose: () => void;
}

export function StandaloneEditDynamicVarsModal({ fileId, clientId, dynamicVars, onSave, onClose }: StandaloneEditVarsProps) {
  const { data: company } = useQuery(getCurrentCompany);
  const { data: clientDetail } = useQuery(getClientDetail, clientId ? { clientId } : undefined as any, { enabled: !!clientId } as any);

  const storedOverrides = useMemo<Record<string, string>>(() => {
    if (!dynamicVars) return {};
    try { return JSON.parse(dynamicVars); } catch { return {}; }
  }, [dynamicVars]);

  const resolvedValues = useMemo<Record<string, string>>(() => {
    const today = new Date().toLocaleDateString('fr-CA', { day: 'numeric', month: 'long', year: 'numeric' });
    const c = clientDetail as any;
    const co = company as any;
    const clientAddress = [c?.address, c?.city, c?.province, c?.postalCode].filter(Boolean).join(', ');
    const companyAddress = [co?.address, co?.city, co?.province, co?.postalCode].filter(Boolean).join(', ');
    return {
      '{{date}}':            today,
      '{{date_expiry}}':     '',
      '{{client.name}}':    c ? (c.contactName ?? c.name ?? '') : '',
      '{{client.company}}': c?.name ?? '',
      '{{client.email}}':   c?.email ?? '',
      '{{client.phone}}':   c?.phone ?? '',
      '{{client.address}}': clientAddress,
      '{{company.name}}':    co?.name ?? '',
      '{{company.email}}':   co?.email ?? '',
      '{{company.phone}}':   co?.phone ?? '',
      '{{company.address}}': companyAddress,
      '{{company.neq}}':     co?.neq ?? '',
      '{{company.tps}}':     co?.taxNumberGst ?? '',
      '{{company.tvq}}':     co?.taxNumberQst ?? '',
      '{{payment.link}}':    '',
      ...storedOverrides,
    };
  }, [clientDetail, company, storedOverrides]);

  return (
    <EditDynamicVarsModal
      fileId={fileId}
      resolvedValues={resolvedValues}
      storedOverrides={storedOverrides}
      onSave={onSave}
      onClose={onClose}
    />
  );
}
