// Whether this company can actually send SMS / email right now, so the UI can
// disable its send controls with an explanation instead of letting the click
// fail server-side.
//
// Backed by getSmsCapability / getEmailCapability, which any company member may
// read (unlike the admin-only settings queries). React Query dedupes by key, so
// every component that calls these shares one request per capability.

import {
  useQuery,
  // @ts-ignore -- generated by Wasp on next restart
  getSmsCapability,
  // @ts-ignore -- generated by Wasp on next restart
  getEmailCapability,
} from 'wasp/client/operations';

export type Capability = {
  canSend: boolean;
  /** Ready-to-display tooltip text when canSend is false. */
  reason: string | null;
  canConfigure: boolean;
};

function normalise(data: unknown, fallbackReason: string): Capability {
  const c = data as Capability | undefined;

  // Optimistic while the query is in flight: controls stay clickable rather than
  // flickering disabled on every load. The server action is the real gate.
  if (!c) return { canSend: true, reason: null, canConfigure: false };

  return {
    canSend: !!c.canSend,
    reason: c.canSend ? null : (c.reason || fallbackReason),
    canConfigure: !!c.canConfigure,
  };
}

export function useSmsCapability(): Capability {
  const { data } = useQuery(getSmsCapability);
  return normalise(data, 'SMS non configuré dans Paramètres → Intégrations.');
}

export type SmsInboxCapability = Capability & { inboxEnabled: boolean };

/**
 * Comme `useSmsCapability`, plus l'état de la messagerie flottante — `normalise`
 * laisse tomber les champs qu'il ne connaît pas, d'où ce hook séparé. Même clé
 * de requête, donc aucun appel réseau supplémentaire.
 *
 * Pessimiste pendant le chargement, à l'inverse de `canSend` : mieux vaut une
 * bulle qui arrive 200 ms trop tard qu'une bulle qui clignote chez ceux qui ont
 * désactivé la messagerie.
 */
export function useSmsInbox(): SmsInboxCapability {
  const { data } = useQuery(getSmsCapability);
  return {
    ...normalise(data, 'SMS non configuré dans Paramètres → Intégrations.'),
    inboxEnabled: (data as any)?.inboxEnabled === true,
  };
}

export type EmailCapability = Capability & {
  /** Company address copied in Cci on every client send, null when off. */
  copyToCompany: string | null;
  /** En-têtes que porteront les envois, pour l'aperçu. Null avant réponse. */
  fromName: string | null;
  fromEmail: string | null;
  replyTo: string | null;
};

/**
 * Comme les autres capacités, plus l'adresse copiée en Cci et les en-têtes
 * d'envoi — `normalise` laisse tomber les champs qu'il ne connaît pas, d'où les
 * champs ajoutés ici. Null tant que la requête n'a pas répondu : mieux vaut ne
 * rien annoncer qu'annoncer une copie qui n'aura pas lieu.
 */
export function useEmailCapability(): EmailCapability {
  const { data } = useQuery(getEmailCapability);
  return {
    ...normalise(data, 'Courriel non configuré dans Paramètres → Intégrations.'),
    copyToCompany: (data as any)?.copyToCompany || null,
    fromName: (data as any)?.fromName || null,
    fromEmail: (data as any)?.fromEmail || null,
    replyTo: (data as any)?.replyTo || null,
  };
}
