import { Link } from 'react-router';
import { useState } from 'react';
// @ts-ignore — generated by Wasp on next dev start
import { sendContactEmail } from 'wasp/client/operations';
import Logo from '../client/Logo';
import { LuMail, LuMapPin, LuMessageSquare, LuSend, LuLoader, LuCircleCheck } from 'react-icons/lu';

export default function ContactPage() {
  const [form, setForm] = useState({ name: '', email: '', company: '', message: '' });
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [formError, setFormError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError('');
    if (!form.name.trim() || !form.email.trim() || !form.message.trim()) {
      setFormError('Veuillez remplir tous les champs obligatoires.');
      return;
    }
    setSending(true);
    try {
      await sendContactEmail(form);
      setSent(true);
    } catch (err: any) {
      setFormError(err?.message || 'Une erreur est survenue. Réessayez.');
    } finally {
      setSending(false);
    }
  };

  return (
    <div className='min-h-screen bg-canvas text-ink'>
      <header className='border-b border-line bg-white/80 backdrop-blur sticky top-0 z-30'>
        <div className='max-w-6xl mx-auto px-6 h-16 flex items-center justify-between'>
          <Link to='/' className='flex items-center gap-2'>
            <Logo height={32} />
          </Link>
          <div className='flex items-center gap-2'>
            <Link to='/connexion' className='btn-ghost'>Connexion</Link>
            <Link to='/#contact' className='btn-primary'>Demander une démo</Link>
          </div>
        </div>
      </header>

      <div className='max-w-5xl mx-auto px-6 py-20'>
        <div className='text-center mb-14'>
          <span className='inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-accent-50 text-accent-700 text-xs font-medium mb-4'>
            <LuMessageSquare size={12} />
            On est là pour vous aider
          </span>
          <h1 className='text-3xl md:text-4xl font-semibold mb-3'>Contactez-nous</h1>
          <p className='text-muted max-w-lg mx-auto leading-relaxed'>
            Une question sur Gestia, besoin d'une démo ou envie d'en savoir plus ?
            Notre équipe vous répond rapidement, en français.
          </p>
        </div>

        <div className='grid md:grid-cols-3 gap-8 items-start'>
          {/* Sidebar info */}
          <div className='space-y-4'>
            <div className='card p-5'>
              <div className='w-10 h-10 rounded-xl bg-accent-50 flex items-center justify-center mb-3'>
                <LuMail size={20} className='text-accent' />
              </div>
              <h3 className='font-semibold mb-1'>Support général</h3>
              <p className='text-sm text-muted mb-2'>Questions, aide, retour d'expérience.</p>
              <a href='mailto:info@trifali.com' className='text-sm text-accent hover:underline font-medium'>
                info@trifali.com
              </a>
            </div>
            <div className='card p-5'>
              <div className='w-10 h-10 rounded-xl bg-sky-50 flex items-center justify-center mb-3'>
                <LuMapPin size={20} className='text-sky-600' />
              </div>
              <h3 className='font-semibold mb-1'>Fait au Québec</h3>
              <p className='text-sm text-muted'>Équipe basée au Québec, service entièrement en français.</p>
            </div>
          </div>

          {/* Form */}
          <div className='md:col-span-2'>
            {sent ? (
              <div className='card p-10 text-center'>
                <div className='w-14 h-14 rounded-full bg-emerald-50 flex items-center justify-center mx-auto mb-4'>
                  <LuCircleCheck size={28} className='text-success' />
                </div>
                <h3 className='font-semibold text-xl mb-2'>Message envoyé !</h3>
                <p className='text-muted'>Merci de nous avoir contactés. Nous vous répondrons dans les meilleurs délais.</p>
                <button
                  className='mt-6 btn-ghost'
                  onClick={() => { setSent(false); setForm({ name: '', email: '', company: '', message: '' }); }}
                >
                  Envoyer un autre message
                </button>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className='card p-7 space-y-5'>
                <div className='grid sm:grid-cols-2 gap-4'>
                  <div>
                    <label className='label'>Nom <span className='text-danger'>*</span></label>
                    <input
                      type='text'
                      className='input'
                      placeholder='Marie Tremblay'
                      value={form.name}
                      onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
                      required
                    />
                  </div>
                  <div>
                    <label className='label'>Courriel <span className='text-danger'>*</span></label>
                    <input
                      type='email'
                      className='input'
                      placeholder='marie@entreprise.com'
                      value={form.email}
                      onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))}
                      required
                    />
                  </div>
                </div>
                <div>
                  <label className='label'>Entreprise <span className='text-muted font-normal'>(optionnel)</span></label>
                  <input
                    type='text'
                    className='input'
                    placeholder='Acme Design inc.'
                    value={form.company}
                    onChange={(e) => setForm((f) => ({ ...f, company: e.target.value }))}
                  />
                </div>
                <div>
                  <label className='label'>Message <span className='text-danger'>*</span></label>
                  <textarea
                    className='input min-h-[140px] resize-y'
                    placeholder='Décrivez votre projet ou votre question…'
                    value={form.message}
                    onChange={(e) => setForm((f) => ({ ...f, message: e.target.value }))}
                    required
                  />
                </div>
                {formError && (
                  <p className='text-sm text-danger'>{formError}</p>
                )}
                <button type='submit' className='btn-accent w-full justify-center py-2.5' disabled={sending}>
                  {sending ? (
                    <>
                      <LuLoader size={16} className='animate-spin' />
                      Envoi en cours…
                    </>
                  ) : (
                    <>
                      <LuSend size={16} />
                      Envoyer le message
                    </>
                  )}
                </button>
              </form>
            )}
          </div>
        </div>

        <p className='mt-10 text-center text-xs text-muted'>
          Questions relatives à la{' '}
          <Link to='/confidentialite' className='hover:text-ink underline underline-offset-2'>confidentialité</Link>
          {' '}ou aux{' '}
          <Link to='/conditions' className='hover:text-ink underline underline-offset-2'>conditions d'utilisation</Link>.
        </p>
      </div>

      <footer className='border-t border-line bg-white'>
        <div className='max-w-6xl mx-auto px-6 py-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-muted'>
          <span>© {new Date().getFullYear()} Gestia · Fait au Québec</span>
          <div className='flex items-center gap-5'>
            <Link to='/confidentialite' className='hover:text-ink transition-colors'>Confidentialité</Link>
            <Link to='/conditions' className='hover:text-ink transition-colors'>Conditions</Link>
            <Link to='/contact' className='hover:text-ink transition-colors'>Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
