import { Link } from 'react-router';
import { useState } from 'react';
import { useAuth } from 'wasp/client/auth';
// @ts-ignore — generated by Wasp on next dev start
import { sendContactEmail } from 'wasp/client/operations';
import Logo from '../client/Logo';
import {
  LuUsers,
  LuFolder,
  LuFileText,
  LuCreditCard,
  LuCalendar,
  LuSparkles,
  LuSearch,
  LuMail,
  LuLink,
  LuTag,
  LuZap,
  LuLayoutDashboard,
  LuArrowRight,
  LuCircleCheck,
  LuReceipt,
  LuMapPin,
  LuTrendingUp,
  LuShield,
  LuInfinity,
  LuSend,
  LuLoader,
} from 'react-icons/lu';

const FEATURES = [
  {
    Icon: LuUsers,
    title: 'CRM Clients',
    desc: 'Centralisez contacts, historique, fichiers et notes pour chaque client en un seul endroit.',
    iconColor: 'text-sky-600',
    iconBg: 'bg-sky-50',
  },
  {
    Icon: LuSearch,
    title: 'Prospection',
    desc: 'Recherchez des prospects, gérez votre pipeline et envoyez des courriels personnalisés.',
    iconColor: 'text-violet-600',
    iconBg: 'bg-violet-50',
  },
  {
    Icon: LuFolder,
    title: 'Projets',
    desc: "Suivez l'avancement, les sections et les fichiers de chaque mandat client.",
    iconColor: 'text-amber-600',
    iconBg: 'bg-amber-50',
  },
  {
    Icon: LuLink,
    title: 'Portail client',
    desc: 'Partagez un projet via lien sécurisé — le client y accède sans créer de compte.',
    iconColor: 'text-teal-600',
    iconBg: 'bg-teal-50',
  },
  {
    Icon: LuFileText,
    title: 'Soumissions',
    desc: 'Préparez des soumissions professionnelles avec calculs de TPS et TVQ automatiques.',
    iconColor: 'text-accent',
    iconBg: 'bg-accent-50',
  },
  {
    Icon: LuReceipt,
    title: 'Factures',
    desc: 'Facturez en CAD, suivez les statuts (envoyée, payée, en retard) et envoyez des rappels.',
    iconColor: 'text-emerald-600',
    iconBg: 'bg-emerald-50',
  },
  {
    Icon: LuCreditCard,
    title: 'Paiements',
    desc: 'Enregistrez les paiements reçus et gardez un œil sur les soldes impayés en temps réel.',
    iconColor: 'text-indigo-600',
    iconBg: 'bg-indigo-50',
  },
  {
    Icon: LuTag,
    title: 'Catalogue de prix',
    desc: 'Créez un catalogue de produits et services réutilisable dans tous vos documents.',
    iconColor: 'text-pink-600',
    iconBg: 'bg-pink-50',
  },
  {
    Icon: LuCalendar,
    title: 'Rencontres',
    desc: 'Planifiez vos réunions et synchronisez avec Google Agenda en un seul clic.',
    iconColor: 'text-blue-600',
    iconBg: 'bg-blue-50',
  },
  {
    Icon: LuMail,
    title: 'Courriels intégrés',
    desc: "Envoyez devis, factures et suivis directement depuis l'application avec des gabarits.",
    iconColor: 'text-orange-600',
    iconBg: 'bg-orange-50',
  },
  {
    Icon: LuLayoutDashboard,
    title: 'Tableau de bord',
    desc: "Vue d'ensemble de vos KPIs : chiffre d'affaires, projets actifs et factures en attente.",
    iconColor: 'text-slate-600',
    iconBg: 'bg-slate-100',
  },
  {
    Icon: LuSparkles,
    title: 'Intelligence artificielle',
    desc: "Rédigez des courriels, corrigez vos textes et générez des gabarits grâce à l'IA.",
    iconColor: 'text-accent',
    iconBg: 'bg-accent-50',
  },
];

const STATS = [
  { Icon: LuZap, value: '12+', label: 'modules intégrés' },
  { Icon: LuMapPin, value: '100%', label: 'en français' },
  { Icon: LuTrendingUp, value: 'TPS+TVQ', label: 'calculées automatiquement' },
  { Icon: LuShield, value: 'CAD', label: 'devise locale ($)' },
];

const AI_FEATURES = [
  'Correction et amélioration de texte en un clic',
  'Génération de courriels de prospection personnalisés',
  'Création de gabarits de documents automatisée',
  "Gabarits de courriels intelligents pour chaque étape du pipeline",
];

export default function LandingPage() {
  const { data: user } = useAuth();
  const ctaTo = user ? '/tableau-de-bord' : '#contact';

  const [form, setForm] = useState({ name: '', email: '', company: '', message: '' });
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [formError, setFormError] = useState('');

  const handleContact = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError('');
    if (!form.name.trim() || !form.email.trim() || !form.message.trim()) {
      setFormError('Veuillez remplir tous les champs obligatoires.');
      return;
    }
    setSending(true);
    try {
      await sendContactEmail(form);
      setSent(true);
    } catch (err: any) {
      setFormError(err?.message || 'Une erreur est survenue. Réessayez.');
    } finally {
      setSending(false);
    }
  };

  return (
    <div className='min-h-screen bg-canvas text-ink overflow-x-hidden'>

      {/* ── Header ───────────────────────────────────────────────────────── */}
      <header className='border-b border-line bg-white/80 backdrop-blur sticky top-0 z-30'>
        <div className='max-w-6xl mx-auto px-6 h-16 flex items-center justify-between'>
          <Link to='/' className='flex items-center gap-2'>
            <Logo height={32} />
          </Link>
          <nav className='hidden md:flex items-center gap-6 text-sm'>
            <a href='#fonctionnalites' className='text-muted hover:text-ink transition-colors'>Fonctionnalités</a>
            <a href='#ia' className='text-muted hover:text-ink transition-colors'>IA</a>
            <a href='#tarifs' className='text-muted hover:text-ink transition-colors'>Tarifs</a>
            <a href='#contact' className='text-muted hover:text-ink transition-colors'>Contact</a>
            <a href='#quebec' className='text-muted hover:text-ink transition-colors'>Québec</a>
          </nav>
          <div className='flex items-center gap-2'>
            {user ? (
              <Link to='/tableau-de-bord' className='btn-primary'>Mon tableau de bord</Link>
            ) : (
              <>
                <Link to='/connexion' className='btn-ghost'>Connexion</Link>
                <a href='#contact' className='btn-primary'>Demander une démo</a>
              </>
            )}
          </div>
        </div>
      </header>

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section className='relative overflow-hidden'>
        {/* Background orbs */}
        <div
          className='landing-float absolute -top-32 -left-40 w-[500px] h-[500px] rounded-full opacity-[0.07] pointer-events-none'
          style={{ background: 'radial-gradient(circle, #FF6A3D 0%, transparent 70%)' }}
        />
        <div
          className='landing-float-alt absolute -top-16 -right-32 w-[420px] h-[420px] rounded-full opacity-[0.06] pointer-events-none'
          style={{ background: 'radial-gradient(circle, #6366F1 0%, transparent 70%)', animationDelay: '1.5s' }}
        />
        <div
          className='landing-float absolute bottom-0 left-1/2 w-[320px] h-[320px] rounded-full opacity-[0.05] pointer-events-none'
          style={{ background: 'radial-gradient(circle, #FF6A3D 0%, transparent 70%)', animationDelay: '3s' }}
        />

        <div className='max-w-6xl mx-auto px-6 pt-24 pb-20 text-center relative z-10'>
          <div className='landing-fade-up' style={{ animationDelay: '0.05s' }}>
            <span className='inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-accent-100 bg-accent-50 text-xs font-medium'>
              <LuMapPin size={12} className='text-accent' />
              <span className='landing-shimmer-badge font-semibold'>Conçu au Québec · 100 % en français</span>
            </span>
          </div>

          <h1
            className='landing-fade-up mt-6 text-4xl md:text-6xl font-semibold tracking-tight leading-[1.06]'
            style={{ animationDelay: '0.15s' }}
          >
            La gestion de votre entreprise,
            <br />
            <span className='text-accent'>simple et intelligente.</span>
          </h1>

          <p
            className='landing-fade-up mt-6 text-lg text-muted max-w-2xl mx-auto leading-relaxed'
            style={{ animationDelay: '0.25s' }}
          >
            Gestia regroupe CRM, projets, soumissions, factures, paiements, rencontres et prospection
            dans une seule plateforme pensée pour les entreprises québécoises.
          </p>

          <div
            className='landing-fade-up mt-8 flex flex-wrap items-center justify-center gap-3'
            style={{ animationDelay: '0.35s' }}
          >
            <a href='#contact' className='btn-accent text-base px-6 py-3 shadow-md hover:shadow-lg transition-shadow'>
              Demander une démo
              <LuArrowRight size={16} />
            </a>
            <a href='#fonctionnalites' className='btn-secondary text-base px-6 py-3'>
              Voir les fonctionnalités
            </a>
          </div>

          <p
            className='landing-fade-up mt-4 text-xs text-muted'
            style={{ animationDelay: '0.45s' }}
          >
            Accès sur invitation · Contactez-nous pour créer votre compte
          </p>
        </div>
      </section>

      {/* ── Stats strip ──────────────────────────────────────────────────── */}
      <div className='border-y border-line bg-white'>
        <div className='max-w-6xl mx-auto px-6 py-6 grid grid-cols-2 md:grid-cols-4 gap-6'>
          {STATS.map(({ Icon, value, label }, i) => (
            <div
              key={label}
              className='landing-fade-up flex items-center gap-3'
              style={{ animationDelay: `${0.1 + i * 0.08}s` }}
            >
              <div className='w-9 h-9 rounded-lg bg-accent-50 flex items-center justify-center flex-shrink-0'>
                <Icon size={18} className='text-accent' />
              </div>
              <div>
                <div className='font-semibold text-ink leading-tight'>{value}</div>
                <div className='text-xs text-muted'>{label}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ── Contact form ─────────────────────────────────────────────────── */}
      <section id='contact' className='bg-canvas-200 border-y border-line'>
        <div className='max-w-6xl mx-auto px-6 py-20'>
          <div className='grid md:grid-cols-2 gap-14 items-start'>
            <div className='landing-slide-left'>
              <span className='inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white border border-line text-ink-700 text-xs font-medium mb-5'>
                <LuMail size={12} className='text-accent' />
                Prenez contact
              </span>
              <h2 className='text-3xl md:text-4xl font-semibold leading-tight'>Parlez-nous de<br />votre projet</h2>
              <p className='mt-4 text-muted leading-relaxed'>
                Une question sur Gestia, besoin d'une démo ou envie d'en savoir plus ?
                Notre équipe vous répond rapidement, en français.
              </p>
              <div className='mt-8 space-y-3'>
                <div className='flex items-center gap-3 text-sm'>
                  <div className='w-9 h-9 rounded-xl bg-white border border-line flex items-center justify-center flex-shrink-0'>
                    <LuMail size={16} className='text-accent' />
                  </div>
                  <a href='mailto:info@trifali.com' className='text-accent hover:underline font-medium'>
                    info@trifali.com
                  </a>
                </div>
                <div className='flex items-center gap-3 text-sm'>
                  <div className='w-9 h-9 rounded-xl bg-white border border-line flex items-center justify-center flex-shrink-0'>
                    <LuMapPin size={16} className='text-sky-600' />
                  </div>
                  <span className='text-muted'>Québec, Canada · Service en français</span>
                </div>
              </div>
            </div>

          <div className='landing-slide-right'>
            {sent ? (
              <div className='card p-8 text-center'>
                <div className='w-12 h-12 rounded-full bg-emerald-50 flex items-center justify-center mx-auto mb-4'>
                  <LuCircleCheck size={24} className='text-success' />
                </div>
                <h3 className='font-semibold text-lg mb-2'>Message envoyé !</h3>
                <p className='text-sm text-muted'>Merci de nous avoir contactés. Nous vous répondrons dans les meilleurs délais.</p>
                <button
                  className='mt-6 btn-ghost text-sm'
                  onClick={() => { setSent(false); setForm({ name: '', email: '', company: '', message: '' }); }}
                >
                  Envoyer un autre message
                </button>
              </div>
            ) : (
              <form onSubmit={handleContact} className='card p-6 space-y-4'>
                <div className='grid sm:grid-cols-2 gap-4'>
                  <div>
                    <label className='label'>Nom <span className='text-danger'>*</span></label>
                    <input
                      type='text'
                      className='input'
                      placeholder='Marie Tremblay'
                      value={form.name}
                      onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
                      required
                    />
                  </div>
                  <div>
                    <label className='label'>Courriel <span className='text-danger'>*</span></label>
                    <input
                      type='email'
                      className='input'
                      placeholder='marie@entreprise.com'
                      value={form.email}
                      onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))}
                      required
                    />
                  </div>
                </div>
                <div>
                  <label className='label'>Entreprise <span className='text-muted font-normal'>(optionnel)</span></label>
                  <input
                    type='text'
                    className='input'
                    placeholder='Acme Design inc.'
                    value={form.company}
                    onChange={(e) => setForm((f) => ({ ...f, company: e.target.value }))}
                  />
                </div>
                <div>
                  <label className='label'>Message <span className='text-danger'>*</span></label>
                  <textarea
                    className='input min-h-[120px] resize-y'
                    placeholder='Décrivez votre projet ou votre question…'
                    value={form.message}
                    onChange={(e) => setForm((f) => ({ ...f, message: e.target.value }))}
                    required
                  />
                </div>
                {formError && (
                  <p className='text-sm text-danger'>{formError}</p>
                )}
                <button type='submit' className='btn-accent w-full justify-center py-2.5' disabled={sending}>
                  {sending ? (
                    <>
                      <LuLoader size={16} className='animate-spin' />
                      Envoi en cours…
                    </>
                  ) : (
                    <>
                      <LuSend size={16} />
                      Envoyer le message
                    </>
                  )}
                </button>
              </form>
            )}
          </div>
        </div>
        </div>
      </section>

      {/* ── Features grid ────────────────────────────────────────────────── */}
      <section id='fonctionnalites' className='max-w-6xl mx-auto px-6 py-24'>
        <div className='text-center mb-14 landing-fade-up'>
          <span className='inline-block px-3 py-1 rounded-full bg-canvas-200 text-ink-700 text-xs font-medium uppercase tracking-wide'>
            Fonctionnalités
          </span>
          <h2 className='mt-4 text-3xl md:text-4xl font-semibold'>Tout ce qu'il vous faut pour bien gérer</h2>
          <p className='mt-3 text-muted max-w-xl mx-auto'>
            Une suite complète et intégrée — sans dispersion, sans abonnements multiples, en français.
          </p>
        </div>

        <div className='grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4'>
          {FEATURES.map(({ Icon, title, desc, iconColor, iconBg }, i) => (
            <div
              key={title}
              className='card feature-card p-5 landing-fade-up'
              style={{ animationDelay: `${0.05 + i * 0.055}s` }}
            >
              <div className={`w-10 h-10 rounded-xl ${iconBg} flex items-center justify-center`}>
                <Icon size={20} className={iconColor} />
              </div>
              <h3 className='mt-4 font-semibold text-sm'>{title}</h3>
              <p className='mt-1.5 text-sm text-muted leading-relaxed'>{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── AI spotlight ─────────────────────────────────────────────────── */}
      <section id='ia' className='bg-ink text-white overflow-hidden relative'>
        <div
          className='landing-float-alt absolute -top-20 right-0 w-[360px] h-[360px] rounded-full opacity-[0.12] pointer-events-none'
          style={{ background: 'radial-gradient(circle, #FF6A3D 0%, transparent 70%)' }}
        />
        <div
          className='landing-float absolute bottom-0 left-0 w-[300px] h-[300px] rounded-full opacity-[0.08] pointer-events-none'
          style={{ background: 'radial-gradient(circle, #A78BFA 0%, transparent 70%)', animationDelay: '2s' }}
        />

        <div className='max-w-6xl mx-auto px-6 py-20 grid md:grid-cols-2 gap-12 items-center relative z-10'>
          <div className='landing-slide-left'>
            <span className='inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-white/80 text-xs font-medium mb-4'>
              <LuSparkles size={12} />
              Intelligence artificielle intégrée
            </span>
            <h2 className='text-3xl md:text-4xl font-semibold'>L'IA qui travaille pour vous</h2>
            <p className='mt-4 text-white/65 leading-relaxed'>
              Gestia intègre l'IA directement dans votre flux de travail pour éliminer les tâches
              répétitives, améliorer vos communications et accélérer la création de contenu.
            </p>
            <ul className='mt-6 space-y-3'>
              {AI_FEATURES.map((feat) => (
                <li key={feat} className='flex items-start gap-3 text-sm text-white/80'>
                  <LuCircleCheck size={16} className='text-accent mt-0.5 flex-shrink-0' />
                  {feat}
                </li>
              ))}
            </ul>
            <div className='mt-8'>
              <a href='#contact' className='btn-accent px-5 py-2.5'>
                Demander une démo
                <LuArrowRight size={15} />
              </a>
            </div>
          </div>

          <div className='landing-slide-right space-y-3'>
            {/* AI demo card */}
            <div className='rounded-2xl bg-white/8 border border-white/10 p-5 backdrop-blur-sm'>
              <div className='flex items-center gap-2 mb-3'>
                <div className='w-7 h-7 rounded-lg bg-accent/20 flex items-center justify-center'>
                  <LuSparkles size={14} className='text-accent' />
                </div>
                <span className='text-xs font-medium text-white/60 uppercase tracking-wide'>Courriel généré par l'IA</span>
              </div>
              <p className='text-sm text-white/80 leading-relaxed'>
                "Bonjour Mme Tremblay, suite à notre échange de la semaine dernière, je vous transmets
                notre soumission pour le projet de refonte de votre site web. N'hésitez pas à me contacter
                si vous avez des questions..."
              </p>
              <div className='mt-3 flex items-center gap-2'>
                <span className='badge bg-emerald-500/20 text-emerald-300 text-xs'>Prêt à envoyer</span>
                <span className='text-xs text-white/40'>Généré en 2 secondes</span>
              </div>
            </div>
            <div className='rounded-2xl bg-white/8 border border-white/10 p-5 backdrop-blur-sm'>
              <div className='flex items-center gap-2 mb-3'>
                <div className='w-7 h-7 rounded-lg bg-violet-500/20 flex items-center justify-center'>
                  <LuZap size={14} className='text-violet-300' />
                </div>
                <span className='text-xs font-medium text-white/60 uppercase tracking-wide'>Correction magique</span>
              </div>
              <div className='text-sm space-y-1'>
                <div className='text-white/40 line-through'>"veuillez trouver ci joint notre offre de service"</div>
                <div className='text-white/85'>"Veuillez trouver ci-joint notre offre de service."</div>
              </div>
              <div className='mt-2'>
                <span className='badge bg-white/10 text-white/60 text-xs'>Grammaire, ponctuation, style</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Quebec section ───────────────────────────────────────────────── */}
      <section id='quebec' className='max-w-6xl mx-auto px-6 py-24 grid md:grid-cols-2 gap-12 items-center'>
        <div className='landing-slide-left'>
          <span className='inline-flex items-center gap-2 px-3 py-1 rounded-full bg-canvas-200 text-ink-700 text-xs font-medium mb-4'>
            <LuMapPin size={12} />
            Fait au Québec
          </span>
          <h2 className='text-3xl md:text-4xl font-semibold'>Pensé pour les entreprises québécoises</h2>
          <p className='mt-4 text-muted leading-relaxed'>
            Devise canadienne, formats de date québécois, calculs de TPS (5 %) et TVQ (9,975 %) intégrés,
            terminologie locale. Tout est prêt dès la première connexion.
          </p>
          <ul className='mt-6 space-y-3'>
            {[
              'Devise CAD ($) avec format québécois',
              'Dates : 30 avril 2026 · Heures : 13 h 30',
              'Nombres : 1 234,56 $',
              'Multi-entreprises et multi-utilisateurs',
              'Terminologie locale (soumission, NEQ…)',
            ].map((item) => (
              <li key={item} className='flex items-center gap-3 text-sm text-ink-700'>
                <LuCircleCheck size={16} className='text-success flex-shrink-0' />
                {item}
              </li>
            ))}
          </ul>
        </div>

        <div className='landing-slide-right'>
          <div className='card p-6 shadow-card feature-card'>
            <div className='flex items-center justify-between mb-1'>
              <div className='flex items-center gap-2'>
                <LuReceipt size={16} className='text-muted' />
                <span className='text-xs text-muted'>Aperçu d'une facture</span>
              </div>
              <span className='badge-success text-xs px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 font-medium'>Payée</span>
            </div>
            <div className='mt-2 text-lg font-semibold'>F-2026-0042</div>
            <div className='text-sm text-muted mb-5'>Émise le 30 avril 2026 · Acme Design inc.</div>

            <div className='space-y-2.5 text-sm'>
              <div className='flex justify-between text-muted'>
                <span>Conception graphique (15 h)</span>
                <span>900,00 $</span>
              </div>
              <div className='flex justify-between text-muted'>
                <span>Intégration web</span>
                <span>350,00 $</span>
              </div>
              <div className='border-t border-line pt-2.5 mt-2.5 space-y-1.5'>
                <div className='flex justify-between text-muted'>
                  <span>Sous-total</span>
                  <span>1 250,00 $</span>
                </div>
                <div className='flex justify-between text-muted'>
                  <span>TPS (5 %)</span>
                  <span>62,50 $</span>
                </div>
                <div className='flex justify-between text-muted'>
                  <span>TVQ (9,975 %)</span>
                  <span>124,69 $</span>
                </div>
                <div className='flex justify-between font-semibold border-t border-line pt-2 mt-1 text-ink'>
                  <span>Total</span>
                  <span>1 437,19 $</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Pricing ──────────────────────────────────────────────────────── */}
      <section id='tarifs' className='bg-canvas-200 border-y border-line'>
        <div className='max-w-6xl mx-auto px-6 py-24'>
        <div className='text-center mb-14 landing-fade-up'>
          <span className='inline-block px-3 py-1 rounded-full bg-canvas-200 text-ink-700 text-xs font-medium uppercase tracking-wide'>
            Tarification
          </span>
          <h2 className='mt-4 text-3xl md:text-4xl font-semibold'>Simple et transparent</h2>
          <p className='mt-3 text-muted max-w-xl mx-auto'>
            Un seul forfait, toutes les fonctionnalités incluses. Aucune surprise, aucun palier caché.
          </p>
        </div>

        <div className='card shadow-card overflow-hidden landing-scale-in'>
          <div className='grid md:grid-cols-[1fr_auto] gap-0'>

            {/* Left — price + CTA */}
            <div className='relative p-8 md:p-10 flex flex-col justify-between border-b md:border-b-0 md:border-r border-line overflow-hidden'>
              {/* Accent glow */}
              <div
                className='absolute -top-16 -left-16 w-52 h-52 rounded-full opacity-[0.07] pointer-events-none'
                style={{ background: 'radial-gradient(circle, #FF6A3D 0%, transparent 70%)' }}
              />
              <div>
                <div className='flex items-center gap-3 mb-6'>
                  <span className='text-lg font-semibold text-ink'>Gestia Complet</span>
                  <span className='inline-flex items-center gap-1 bg-accent-50 text-accent-700 font-medium px-3 py-1 rounded-full text-xs'>
                    <LuInfinity size={11} />
                    Tout inclus
                  </span>
                </div>
                <div className='flex items-end gap-1.5'>
                  <span className='text-6xl font-semibold tracking-tight'>169,99</span>
                  <div className='mb-2 text-left'>
                    <div className='text-xl font-medium text-muted'>$&nbsp;CAD</div>
                    <div className='text-xs text-muted'>/ mois · taxes en sus</div>
                  </div>
                </div>
                <p className='mt-4 text-sm text-muted max-w-xs'>
                  Un seul forfait, tous les modules inclus. Aucun palier caché, aucune limite d'utilisateurs.
                </p>
              </div>
              <div className='mt-8 flex flex-col sm:flex-row gap-3'>
                <a href='#contact' className='btn-accent px-6 py-3 justify-center'>
                  Demander l'accès
                  <LuArrowRight size={16} />
                </a>
                <p className='self-center text-xs text-muted'>Accès sur invitation · démo incluse</p>
              </div>
            </div>

            {/* Right — feature list */}
            <div className='p-8 md:p-10 md:min-w-[320px]'>
              <p className='text-xs font-medium uppercase tracking-wide text-muted mb-5'>Ce qui est inclus</p>
              <ul className='space-y-3'>
                {[
                  'CRM clients & gestion de projets',
                  'Soumissions, factures & paiements',
                  'Prospection & pipeline de ventes',
                  'Rencontres + Google Agenda',
                  'Intelligence artificielle intégrée',
                  'Portail client partageable',
                  'Multi-utilisateurs illimités',
                  'Support en français',
                ].map((item) => (
                  <li key={item} className='flex items-center gap-3 text-sm text-ink-700'>
                    <LuCircleCheck size={15} className='text-success flex-shrink-0' />
                    {item}
                  </li>
                ))}
              </ul>
            </div>

          </div>
        </div>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────────────────── */}
      <section className='relative overflow-hidden'>
        <div
          className='absolute inset-0 pointer-events-none'
          style={{ background: 'linear-gradient(135deg, #0A0A0B 0%, #1e1e24 50%, #0A0A0B 100%)' }}
        />
        <div
          className='landing-float absolute top-0 left-1/4 w-[400px] h-[400px] rounded-full opacity-[0.1] pointer-events-none'
          style={{ background: 'radial-gradient(circle, #FF6A3D 0%, transparent 70%)' }}
        />

        <div className='relative z-10 max-w-3xl mx-auto px-6 py-24 text-center text-white'>
          <div className='landing-fade-up'>
            <span className='inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-white/70 text-xs font-medium mb-5'>
              <LuZap size={12} className='text-accent' />
              Accès sur invitation
            </span>
          </div>
          <h2 className='landing-fade-up text-3xl md:text-5xl font-semibold leading-tight' style={{ animationDelay: '0.1s' }}>
            Prêt à simplifier<br />votre gestion ?
          </h2>
          <p className='landing-fade-up mt-5 text-white/60 text-lg leading-relaxed' style={{ animationDelay: '0.2s' }}>
            Contactez-nous pour planifier une démo personnalisée. Nous créons votre compte
            et vous accompagnons dès le départ.
          </p>
          <div className='landing-fade-up mt-8 flex flex-wrap items-center justify-center gap-3' style={{ animationDelay: '0.3s' }}>
            <a href='#contact' className='btn-accent text-base px-7 py-3.5 shadow-lg hover:shadow-xl transition-shadow'>
              Planifier une démo
              <LuArrowRight size={16} />
            </a>
            <Link to='/connexion' className='btn text-base px-6 py-3.5 border border-white/20 text-white/80 hover:bg-white/10 transition-colors rounded-lg'>
              J'ai déjà un compte
            </Link>
          </div>
          <p className='landing-fade-up mt-4 text-xs text-white/40' style={{ animationDelay: '0.4s' }}>
            Démo gratuite · Accompagnement personnalisé · Support en français
          </p>
        </div>
      </section>

      {/* ── Footer ───────────────────────────────────────────────────────── */}
      <footer className='border-t border-line bg-white'>
        <div className='max-w-6xl mx-auto px-6 py-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-muted'>
          <div className='flex items-center gap-2'>
            <Logo height={24} />
            <span>© {new Date().getFullYear()} Gestia · Fait au Québec</span>
          </div>
          <div className='flex items-center gap-5'>
            <Link to='/confidentialite' className='hover:text-ink transition-colors'>Confidentialité</Link>
            <Link to='/conditions' className='hover:text-ink transition-colors'>Conditions</Link>
            <Link to='/contact' className='hover:text-ink transition-colors'>Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
