import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import {
  useQuery,
  // @ts-ignore -- generated by Wasp on next restart
  searchSmsRecipients,
  // @ts-ignore -- generated by Wasp on next restart
  sendDirectSms,
} from 'wasp/client/operations';
import { SmsComposer } from './SmsComposer';
import { toE164, formatPhoneDisplay } from './phone';
import type { SmsConversationItem, SmsRecipientItem } from './types';

const SOURCE_LABEL: Record<SmsRecipientItem['source'], string> = {
  contact: 'Contact',
  client: 'Client',
  lead: 'Prospect',
  raw: 'Numéro',
};
// .badge-* applique déjà .badge (voir Main.css).
const SOURCE_BADGE: Record<SmsRecipientItem['source'], string> = {
  contact: 'badge-neutral shrink-0',
  client: 'badge-info shrink-0',
  lead: 'badge-accent shrink-0',
  raw: 'badge-neutral shrink-0',
};

export function SmsNewConversation({
  initialTo,
  conversations,
  canSend,
  reason,
  onOpenThread,
  onChanged,
}: {
  initialTo: string;
  conversations: SmsConversationItem[];
  canSend: boolean;
  reason: string | null;
  onOpenThread: (identifier: string) => void;
  onChanged: () => void;
}) {
  const [to, setTo] = useState(initialTo);
  const [debounced, setDebounced] = useState(initialTo);
  const [text, setText] = useState('');
  const [sending, setSending] = useState(false);

  useEffect(() => {
    const id = setTimeout(() => setDebounced(to), 250);
    return () => clearTimeout(id);
  }, [to]);

  const e164 = useMemo(() => toE164(to), [to]);

  const { data: suggestionData } = useQuery(
    // @ts-ignore -- generated by Wasp on next restart
    searchSmsRecipients,
    { q: debounced.trim() },
    { enabled: debounced.trim().length >= 2 },
  );
  const suggestions: SmsRecipientItem[] = (suggestionData as any)?.items ?? [];
  const truncated: boolean = (suggestionData as any)?.truncated ?? false;

  // Le fil existant est un raccourci d'interface ; la garantie de non-duplication
  // est côté serveur, qui résout l'identifiant à l'envoi.
  const existing = e164 ? conversations.find(c => c.phone === e164) : undefined;

  async function handleSend() {
    if (!e164) { toast.error('Numéro invalide'); return; }
    setSending(true);
    try {
      const result = await (sendDirectSms as any)({ to: e164, body: text });
      setText('');
      onChanged();
      onOpenThread(result.identifier);
    } catch (err: any) {
      toast.error(err?.message || "Erreur lors de l'envoi");
    } finally {
      setSending(false);
    }
  }

  return (
    <>
      <div className='flex-1 min-h-0 overflow-y-auto'>
        <div className='p-3 border-b border-line relative'>
          <label className='label' htmlFor='sms-to'>À (numéro)</label>
          <input
            id='sms-to'
            type='tel'
            autoComplete='off'
            autoFocus
            role='combobox'
            aria-expanded={suggestions.length > 0}
            aria-autocomplete='list'
            aria-controls='sms-to-suggestions'
            className='input mt-1'
            value={to}
            onChange={e => setTo(e.target.value)}
            placeholder='(514) 555-0100 ou un nom'
          />
          <p
            className={`text-xs mt-1 ${
              to.trim() === '' ? 'text-muted' : e164 ? 'text-success' : 'text-danger'
            }`}
          >
            {to.trim() === ''
              ? 'Les numéros à 10 chiffres sont envoyés en +1 (Amérique du Nord).'
              : e164
                ? `Sera envoyé à ${formatPhoneDisplay(e164)}`
                : 'Numéro invalide.'}
          </p>

          {suggestions.length > 0 && (
            <ul
              id='sms-to-suggestions'
              role='listbox'
              className='absolute z-50 top-full mt-1 left-3 right-3 bg-white border border-line rounded-xl shadow-lg max-h-52 overflow-y-auto'
            >
              {suggestions.map(s => (
                <li key={`${s.source}:${s.phone}`}>
                  <button
                    type='button'
                    role='option'
                    aria-selected='false'
                    onClick={() => {
                      // Un prospect ou un fil déjà ouvert : on y va au lieu d'en
                      // ouvrir un second.
                      if (s.hasThread) { onOpenThread(s.identifier); return; }
                      setTo(s.phone);
                      setDebounced(s.phone);
                    }}
                    className='w-full text-left px-3 py-2 flex items-center gap-2 hover:bg-canvas-100 transition-colors'
                  >
                    <span className='min-w-0 flex-1'>
                      <span className='block text-sm text-ink truncate'>{s.name}</span>
                      <span className='block text-xs text-muted'>{formatPhoneDisplay(s.phone)}</span>
                    </span>
                    <span className={SOURCE_BADGE[s.source]}>{SOURCE_LABEL[s.source]}</span>
                  </button>
                </li>
              ))}
              {truncated && (
                <li className='px-3 py-1.5 text-[11px] text-muted border-t border-line'>
                  Liste partielle — précisez votre recherche.
                </li>
              )}
            </ul>
          )}
        </div>

        {existing && (
          <div className='mx-3 mt-3 rounded-lg border border-accent-100 bg-accent-50 px-3 py-2 flex items-center gap-2'>
            <span className='text-xs text-accent-700 min-w-0 flex-1'>
              Conversation existante avec{' '}
              <strong className='font-semibold'>
                {existing.displayName || formatPhoneDisplay(existing.phone)}
              </strong>
              .
            </span>
            <button
              className='btn-secondary text-xs px-2.5 py-1 shrink-0'
              onClick={() => onOpenThread(existing.identifier)}
            >
              Ouvrir
            </button>
          </div>
        )}
      </div>

      <SmsComposer
        value={text}
        onChange={setText}
        onSend={handleSend}
        sending={sending}
        canSend={canSend && !!e164}
        reason={canSend && !e164 ? 'Entrez un numéro valide pour envoyer.' : reason}
      />
    </>
  );
}
