import { useEffect, useMemo, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import {
  useQuery,
  // @ts-ignore -- generated by Wasp on next restart
  searchSmsRecipients,
  // @ts-ignore -- generated by Wasp on next restart
  sendDirectSms,
} from 'wasp/client/operations';
import { SmsComposer } from './SmsComposer';
import { LuX } from 'react-icons/lu';
import { toE164, formatPhoneDisplay, initialsFor, maskPhoneOrName } from './phone';
import type { SmsConversationItem, SmsRecipientItem } from './types';

const SOURCE_LABEL: Record<SmsRecipientItem['source'], string> = {
  contact: 'Contact',
  client: 'Client',
  lead: 'Prospect',
  raw: 'Numéro',
};
// .badge-* applique déjà .badge (voir Main.css).
const SOURCE_BADGE: Record<SmsRecipientItem['source'], string> = {
  contact: 'badge-neutral shrink-0',
  client: 'badge-info shrink-0',
  lead: 'badge-accent shrink-0',
  raw: 'badge-neutral shrink-0',
};

export function SmsNewConversation({
  initialTo,
  conversations,
  canSend,
  reason,
  onOpenThread,
  onChanged,
}: {
  initialTo: string;
  conversations: SmsConversationItem[];
  canSend: boolean;
  reason: string | null;
  onOpenThread: (identifier: string) => void;
  onChanged: () => void;
}) {
  const [to, setTo] = useState(initialTo);
  const [debounced, setDebounced] = useState(initialTo);
  const [text, setText] = useState('');
  const [sending, setSending] = useState(false);
  // La liste ne s'ouvre qu'à la frappe. Sans ce drapeau, choisir une suggestion
  // remplit le champ, ce qui relance la recherche — qui retrouve la même
  // personne : la liste resterait ouverte sur un choix déjà fait.
  const [suggestOpen, setSuggestOpen] = useState(false);
  // Le champ ne contient qu'un numéro : on retient à côté qui il désigne, pour
  // que le choix reste lisible après la fermeture de la liste.
  const [picked, setPicked] = useState<SmsRecipientItem | null>(null);

  useEffect(() => {
    const id = setTimeout(() => setDebounced(to), 250);
    return () => clearTimeout(id);
  }, [to]);

  const e164 = useMemo(() => toE164(to), [to]);

  // Un clic ailleurs — la zone de message, par exemple — referme la liste.
  const fieldRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    if (!suggestOpen) return;
    function onPointerDown(e: PointerEvent) {
      if (!fieldRef.current?.contains(e.target as Node)) setSuggestOpen(false);
    }
    document.addEventListener('pointerdown', onPointerDown);
    return () => document.removeEventListener('pointerdown', onPointerDown);
  }, [suggestOpen]);

  const { data: suggestionData } = useQuery(
    // @ts-ignore -- generated by Wasp on next restart
    searchSmsRecipients,
    { q: debounced.trim() },
    { enabled: debounced.trim().length >= 2 },
  );
  const suggestions: SmsRecipientItem[] = (suggestionData as any)?.items ?? [];
  const truncated: boolean = (suggestionData as any)?.truncated ?? false;
  const showSuggestions = suggestOpen && suggestions.length > 0;

  // Le fil existant est un raccourci d'interface ; la garantie de non-duplication
  // est côté serveur, qui résout l'identifiant à l'envoi.
  const existing = e164 ? conversations.find(c => c.phone === e164) : undefined;

  // Nom du destinataire, qu'il vienne d'un choix dans la liste ou d'un numéro
  // tapé à la main qui se trouve appartenir à une conversation connue. Une
  // suggestion « numéro brut » porte le numéro comme nom : ne rien afficher.
  const recipientName =
    (picked && picked.phone === e164 && picked.name !== picked.phone ? picked.name : null) ??
    existing?.displayName ??
    null;

  async function handleSend() {
    if (!e164) { toast.error('Numéro invalide'); return; }
    setSending(true);
    try {
      const result = await (sendDirectSms as any)({ to: e164, body: text });
      setText('');
      onChanged();
      onOpenThread(result.identifier);
    } catch (err: any) {
      toast.error(err?.message || "Erreur lors de l'envoi");
    } finally {
      setSending(false);
    }
  }

  return (
    <>
      <div className='flex-1 min-h-0 overflow-y-auto'>
        <div ref={fieldRef} className='p-3 border-b border-line relative'>
          <label className='label' htmlFor='sms-to'>À (numéro)</label>
          <input
            id='sms-to'
            type='tel'
            autoComplete='off'
            autoFocus
            role='combobox'
            aria-expanded={showSuggestions}
            aria-autocomplete='list'
            aria-controls='sms-to-suggestions'
            className='input mt-1'
            value={to}
            // `maskPhoneOrName`, pas `maskPhone` : ce champ cherche aussi un
            // contact par son nom, que le masque réduirait en miettes.
            onChange={e => { setTo(maskPhoneOrName(e.target.value)); setPicked(null); setSuggestOpen(true); }}
            onKeyDown={e => {
              // Échap referme d'abord la liste. Sans l'arrêt de propagation, le
              // panneau au-dessus l'interpréterait comme « fermer la messagerie ».
              if (e.key === 'Escape' && showSuggestions) {
                e.stopPropagation();
                setSuggestOpen(false);
              }
            }}
            placeholder='(514) 555-0100 ou un nom'
          />
          {recipientName && e164 ? (
            <div className='mt-1.5 flex items-center gap-2 rounded-lg border border-accent-100 bg-accent-50 px-2.5 py-1.5'>
              <span className='shrink-0 w-7 h-7 rounded-full bg-white text-accent-700 flex items-center justify-center font-semibold text-[10px]'>
                {initialsFor(recipientName)}
              </span>
              <span className='min-w-0 flex-1'>
                <span className='block text-sm font-medium text-ink truncate'>{recipientName}</span>
                <span className='block text-xs text-muted'>{formatPhoneDisplay(e164)}</span>
              </span>
              <button
                type='button'
                onClick={() => { setPicked(null); setTo(''); setDebounced(''); }}
                aria-label='Changer de destinataire'
                title='Changer de destinataire'
                className='shrink-0 w-6 h-6 rounded-md flex items-center justify-center text-muted hover:text-ink hover:bg-white transition-colors'
              >
                <LuX size={14} />
              </button>
            </div>
          ) : (
            <p
              className={`text-xs mt-1 ${
                to.trim() === '' ? 'text-muted' : e164 ? 'text-success' : 'text-danger'
              }`}
            >
              {to.trim() === ''
                ? 'Les numéros à 10 chiffres sont envoyés en +1 (Amérique du Nord).'
                : e164
                  ? `Sera envoyé à ${formatPhoneDisplay(e164)}`
                  : 'Numéro invalide.'}
            </p>
          )}

          {showSuggestions && (
            <ul
              id='sms-to-suggestions'
              role='listbox'
              className='absolute z-50 top-full mt-1 left-3 right-3 bg-white border border-line rounded-xl shadow-lg max-h-52 overflow-y-auto'
            >
              {suggestions.map(s => (
                <li key={`${s.source}:${s.phone}`}>
                  <button
                    type='button'
                    role='option'
                    aria-selected='false'
                    onClick={() => {
                      setSuggestOpen(false);
                      // Un prospect ou un fil déjà ouvert : on y va au lieu d'en
                      // ouvrir un second.
                      if (s.hasThread) { onOpenThread(s.identifier); return; }
                      setPicked(s);
                      setTo(s.phone);
                      setDebounced(s.phone);
                    }}
                    className='w-full text-left px-3 py-2 flex items-center gap-2 hover:bg-canvas-100 transition-colors'
                  >
                    <span className='min-w-0 flex-1'>
                      <span className='block text-sm text-ink truncate'>{s.name}</span>
                      <span className='block text-xs text-muted'>{formatPhoneDisplay(s.phone)}</span>
                    </span>
                    <span className={SOURCE_BADGE[s.source]}>{SOURCE_LABEL[s.source]}</span>
                  </button>
                </li>
              ))}
              {truncated && (
                <li className='px-3 py-1.5 text-[11px] text-muted border-t border-line'>
                  Liste partielle — précisez votre recherche.
                </li>
              )}
            </ul>
          )}
        </div>

        {existing && (
          <div className='mx-3 mt-3 rounded-lg border border-accent-100 bg-accent-50 px-3 py-2 flex items-center gap-2'>
            <span className='text-xs text-accent-700 min-w-0 flex-1'>
              {/* Inutile de répéter le nom : la pastille au-dessus le porte déjà. */}
              {recipientName ? (
                'Une conversation existe déjà avec ce numéro.'
              ) : (
                <>
                  Conversation existante avec{' '}
                  <strong className='font-semibold'>
                    {existing.displayName || formatPhoneDisplay(existing.phone)}
                  </strong>
                  .
                </>
              )}
            </span>
            <button
              className='btn-secondary text-xs px-2.5 py-1 shrink-0'
              onClick={() => onOpenThread(existing.identifier)}
            >
              Ouvrir
            </button>
          </div>
        )}
      </div>

      <SmsComposer
        value={text}
        onChange={setText}
        onSend={handleSend}
        sending={sending}
        canSend={canSend && !!e164}
        reason={canSend && !e164 ? 'Entrez un numéro valide pour envoyer.' : reason}
      />
    </>
  );
}
