import { useEffect, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import {
  useQuery,
  // @ts-ignore -- generated by Wasp on next restart
  getLeadSmsLogs,
  // @ts-ignore -- generated by Wasp on next restart
  markLeadSmsRead,
  // @ts-ignore -- generated by Wasp on next restart
  sendDirectSms,
} from 'wasp/client/operations';
import { SMS_THREAD_POLL_MS } from '../polling';
import { SmsMessageList } from './SmsMessageList';
import { SmsComposer } from './SmsComposer';
import { toE164 } from './phone';
import type { SmsConversationItem } from './types';

/** Le numéro de l'interlocuteur, déduit du dernier message du fil. */
function phoneFromLogs(logs: any[]): string | null {
  const last = logs[logs.length - 1];
  if (!last) return null;
  return toE164(last.direction === 'inbound' ? last.fromNumber : last.to);
}

export function SmsThread({
  identifier,
  conversation,
  canSend,
  reason,
  onChanged,
}: {
  identifier: string;
  conversation: SmsConversationItem | undefined;
  canSend: boolean;
  reason: string | null;
  /** Appelé après lecture ou envoi : rafraîchit la liste et les pastilles. */
  onChanged: () => void;
}) {
  const { data: logs = [], refetch: refetchLogs } = useQuery(
    // @ts-ignore -- generated by Wasp on next restart
    getLeadSmsLogs,
    { identifier },
    { refetchInterval: SMS_THREAD_POLL_MS, refetchOnWindowFocus: true },
  );
  const [text, setText] = useState('');
  const [sending, setSending] = useState(false);

  // Avoir le fil ouvert vaut lecture. Piloté par les messages et non par le
  // montage, pour qu'une réponse arrivant pendant la lecture soit marquée elle
  // aussi au lieu de laisser une pastille périmée derrière soi.
  const markingRead = useRef(false);
  const unreadInThread = (logs as any[]).some((l: any) => l.direction === 'inbound' && !l.readAt);
  useEffect(() => {
    if (!unreadInThread || markingRead.current) return;
    markingRead.current = true;
    (markLeadSmsRead as any)({ identifier })
      .then(() => { refetchLogs(); onChanged(); })
      .finally(() => { markingRead.current = false; });
  }, [identifier, unreadInThread]);

  // Défilement : saut sec à l'ouverture, puis suivi en douceur — et seulement si
  // l'utilisateur était déjà en bas, sinon un poll l'arracherait à sa lecture.
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const bottomRef = useRef<HTMLDivElement | null>(null);
  const seenCount = useRef(0);
  useEffect(() => { seenCount.current = 0; }, [identifier]);
  useEffect(() => {
    const el = scrollRef.current;
    const count = (logs as any[]).length;
    if (!el || !count) return;
    const first = seenCount.current === 0;
    const grew = count > seenCount.current;
    seenCount.current = count;
    if (first) {
      bottomRef.current?.scrollIntoView({ block: 'end' });
      return;
    }
    if (!grew) return;
    const nearBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 80;
    if (nearBottom) bottomRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' });
  }, [logs, identifier]);

  // Le numéro est repris des messages plutôt que de la liste : ouvrir un fil
  // depuis un toast peut précéder le chargement de la liste, et « pas encore
  // chargé » ne doit pas se lire comme « injoignable ».
  const replyTo = conversation?.phone ?? phoneFromLogs(logs as any[]);
  // Un code court ou un expéditeur alphanumérique se lit mais ne se répond pas.
  const canReply = canSend && !!replyTo;

  async function handleSend() {
    if (!replyTo) return;
    setSending(true);
    try {
      await (sendDirectSms as any)({ to: replyTo, body: text });
      setText('');
      refetchLogs();
      onChanged();
    } catch (err: any) {
      toast.error(err?.message || "Erreur lors de l'envoi");
    } finally {
      setSending(false);
    }
  }

  return (
    <>
      <div
        ref={scrollRef}
        role='log'
        aria-live='polite'
        aria-relevant='additions'
        className='flex-1 min-h-0 overflow-y-auto overscroll-contain px-3 py-3'
      >
        {(logs as any[]).length === 0 ? (
          <p className='text-xs text-muted text-center py-8'>Aucun message. Écrivez le premier.</p>
        ) : (
          <SmsMessageList logs={logs as any[]} />
        )}
        <div ref={bottomRef} />
      </div>
      <SmsComposer
        value={text}
        onChange={setText}
        onSend={handleSend}
        sending={sending}
        canSend={canReply}
        reason={
          canSend && !replyTo
            ? "Ce numéro n'est pas joignable (code court ou expéditeur alphanumérique)."
            : reason
        }
        autoFocus
      />
    </>
  );
}
