// Messagerie SMS flottante.
//
// Bulle en bas à droite, panneau empilé liste ↔ conversation ↔ nouveau message.
// C'est le seul écran où se lisent les fils qui n'ont pas de carte de prospect :
// numéros inconnus, et réponses dont le prospect a été supprimé.
//
// Empilement : bulle z-[36], panneau z-[37] — au-dessus du panneau de détail
// prospect (34/35), en dessous de .modal-backdrop (40) et du tiroir mobile (50),
// pour que toute boîte de dialogue le recouvre sans aucune coordination.

import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import toast from 'react-hot-toast';
import {
  LuMessageSquare, LuX, LuPlus, LuChevronLeft, LuCheck, LuLoader,
} from 'react-icons/lu';
import {
  useQuery,
  getCurrentCompany,
  // @ts-ignore -- generated by Wasp on next restart
  getSmsConversations,
  // @ts-ignore -- generated by Wasp on next restart
  upsertSmsContact,
} from 'wasp/client/operations';
import { IconBtn, EditIcon } from '../ui';
import { useSmsInbox } from '../capabilities';
import { useSmsAlerts } from './useSmsAlerts';
import { useSmsWidget } from './SmsWidgetContext';
import { SmsConversationList } from './SmsConversationList';
import { SmsThread } from './SmsThread';
import { SmsNewConversation } from './SmsNewConversation';
import { formatPhoneDisplay } from './phone';
import type { SmsConversationItem } from './types';

export function SmsWidget() {
  const { data: company } = useQuery(getCurrentCompany);
  const { inboxEnabled, canSend, reason } = useSmsInbox();
  const {
    open, view, activeIdentifier, draftTo,
    openThread, startNew, goBack, close, toggle,
  } = useSmsWidget();

  const alerts = useSmsAlerts({ enabled: !!company });
  const { data: conversationData, isLoading, refetch: refetchConversations } = useQuery(
    // @ts-ignore -- generated by Wasp on next restart
    getSmsConversations,
    undefined,
    { enabled: open && inboxEnabled },
  );
  const conversations: SmsConversationItem[] = (conversationData as any)?.items ?? [];
  const active = conversations.find(c => c.identifier === activeIdentifier);

  // La liste est coûteuse (un regroupement sur toute la table) : au lieu de la
  // poller, on se greffe sur le compteur d'alertes, déjà en vol pour toute
  // l'application, et on ne recharge que quand il bouge.
  useEffect(() => {
    if (open) refetchConversations();
  }, [open, alerts.total]);

  // Animation d'entrée/sortie : même mécanique que LeadDetailPanel.
  const [mounted, setMounted] = useState(false);
  const [shown, setShown] = useState(false);
  useEffect(() => {
    if (open) {
      setMounted(true);
      const id = setTimeout(() => setShown(true), 10);
      return () => clearTimeout(id);
    }
    setShown(false);
    const id = setTimeout(() => setMounted(false), 200);
    return () => clearTimeout(id);
  }, [open]);

  // Remonte l'état à la feuille de style pour que la file des toasts s'écarte de
  // la bulle, puis du panneau (voir Main.css).
  useEffect(() => {
    if (!inboxEnabled) return;
    const el = document.documentElement;
    el.dataset.smsWidget = open ? 'open' : 'mounted';
    return () => { delete el.dataset.smsWidget; };
  }, [open, inboxEnabled]);

  // À l'ouverture, le focus entre dans le panneau ; à la fermeture il revient
  // sur la bulle, pour ne pas déposer un utilisateur au clavier en haut du
  // document. Le drapeau évite de voler le focus au premier rendu, où la
  // messagerie est fermée sans avoir jamais été ouverte.
  const bubbleRef = useRef<HTMLButtonElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);
  const wasOpen = useRef(false);
  useEffect(() => {
    if (open) {
      wasOpen.current = true;
      if (shown) panelRef.current?.focus({ preventScroll: true });
      return;
    }
    if (wasOpen.current) {
      wasOpen.current = false;
      bubbleRef.current?.focus({ preventScroll: true });
    }
  }, [open, shown]);

  // Renommage d'un numéro, depuis l'en-tête du fil.
  const [naming, setNaming] = useState(false);
  const [nameDraft, setNameDraft] = useState('');
  const [savingName, setSavingName] = useState(false);
  useEffect(() => { setNaming(false); }, [activeIdentifier, view]);

  async function saveName() {
    if (!active?.phone || !nameDraft.trim()) return;
    setSavingName(true);
    try {
      await (upsertSmsContact as any)({ phone: active.phone, name: nameDraft.trim() });
      setNaming(false);
      setNameDraft('');
      refetchConversations();
      toast.success('Contact enregistré');
    } catch (err: any) {
      toast.error(err?.message || 'Erreur');
    } finally {
      setSavingName(false);
    }
  }

  if (!company || !inboxEnabled) return null;

  const unread = alerts.total;

  // Escape est capté sur le panneau et non sur le document : une boîte de
  // dialogue ouverte par-dessus doit garder la main sur sa propre touche Échap.
  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key !== 'Escape') return;
    e.stopPropagation();
    if (naming) { setNaming(false); return; }
    if (view !== 'list') goBack();
    else close();
  }

  const headerTitle =
    view === 'list'
      ? 'Messages'
      : view === 'new'
        ? 'Nouveau message'
        : active?.displayName || formatPhoneDisplay(active?.phone) || active?.address || 'Conversation';
  const headerSubtitle =
    view === 'list'
      ? unread > 0 ? `${unread} non lu${unread > 1 ? 's' : ''}` : 'Aucun message non lu'
      : view === 'thread' && active?.displayName
        ? formatPhoneDisplay(active.phone) || active.address
        : null;

  return createPortal(
    <>
      <button
        ref={bubbleRef}
        type='button'
        onClick={toggle}
        aria-expanded={open}
        aria-controls='sms-widget-panel'
        aria-label={
          unread > 0
            ? `Messagerie SMS — ${unread} message${unread > 1 ? 's' : ''} non lu${unread > 1 ? 's' : ''}`
            : 'Messagerie SMS'
        }
        className={`fixed bottom-5 right-5 z-[36] w-14 h-14 rounded-full bg-ink text-white shadow-card flex items-center justify-center transition-all duration-150 hover:bg-ink-800 hover:scale-105 active:scale-95 focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-500 focus-visible:ring-offset-2 ${
          open ? 'hidden sm:flex' : ''
        }`}
      >
        {open ? <LuX size={22} /> : <LuMessageSquare size={22} />}
        {!open && unread > 0 && (
          <span
            aria-hidden='true'
            className='absolute -top-0.5 -right-0.5 min-w-[18px] h-[18px] rounded-full bg-accent-500 text-white text-[10px] font-bold flex items-center justify-center px-1 leading-none ring-2 ring-canvas'
          >
            {unread > 99 ? '99+' : unread}
          </span>
        )}
      </button>
      <span className='sr-only' role='status' aria-live='polite'>
        {unread > 0 ? `${unread} message SMS non lu` : ''}
      </span>

      {mounted && (
        <div
          id='sms-widget-panel'
          ref={panelRef}
          tabIndex={-1}
          role='dialog'
          aria-label='Messagerie SMS'
          onKeyDown={handleKeyDown}
          className={`fixed z-[37] bg-white flex flex-col overflow-hidden outline-none inset-x-0 top-0 h-[100dvh] sm:inset-auto sm:top-auto sm:bottom-[88px] sm:right-5 sm:h-[560px] sm:max-h-[calc(100dvh-140px)] sm:w-[380px] lg:w-[400px] sm:rounded-2xl sm:border sm:border-line sm:shadow-card transition-all duration-200 ${
            shown ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-2 pointer-events-none'
          }`}
        >
          <div className='shrink-0 flex items-center gap-1.5 px-3 py-3 border-b border-line'>
            {view !== 'list' && (
              <button
                onClick={goBack}
                aria-label='Retour aux conversations'
                className='w-8 h-8 rounded-lg flex items-center justify-center text-muted hover:text-ink hover:bg-canvas-200 transition-colors shrink-0'
              >
                <LuChevronLeft size={18} />
              </button>
            )}
            <div className='min-w-0 flex-1'>
              <h2 className='text-sm font-semibold text-ink truncate leading-tight'>{headerTitle}</h2>
              {headerSubtitle && <p className='text-xs text-muted truncate'>{headerSubtitle}</p>}
            </div>
            {view === 'list' && (
              <IconBtn title='Nouveau message' onClick={() => startNew()}>
                <LuPlus size={16} />
              </IconBtn>
            )}
            {view === 'thread' && active?.kind === 'number' && active.phone && (
              <IconBtn
                title='Nommer ce numéro'
                onClick={() => { setNameDraft(active.displayName ?? ''); setNaming(true); }}
              >
                <EditIcon />
              </IconBtn>
            )}
            <button
              onClick={close}
              aria-label='Fermer la messagerie'
              className='w-8 h-8 rounded-lg flex items-center justify-center text-muted hover:text-ink hover:bg-canvas-200 transition-colors shrink-0'
            >
              <LuX size={18} />
            </button>
          </div>

          {naming && (
            <div className='shrink-0 flex gap-2 items-center px-3 py-2 border-b border-line bg-canvas-100'>
              <input
                className='input text-sm py-1.5'
                autoFocus
                value={nameDraft}
                onChange={e => setNameDraft(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') saveName(); }}
                placeholder='Nom du contact'
              />
              <button
                className='btn-primary px-2.5 py-1.5 shrink-0'
                onClick={saveName}
                disabled={savingName || !nameDraft.trim()}
                aria-label='Enregistrer le nom'
              >
                {savingName ? <LuLoader size={14} className='animate-spin' /> : <LuCheck size={14} />}
              </button>
              <button
                className='btn-ghost px-2 py-1.5 shrink-0'
                onClick={() => setNaming(false)}
                aria-label='Annuler'
              >
                <LuX size={14} />
              </button>
            </div>
          )}

          {view === 'list' && (
            <SmsConversationList
              conversations={conversations}
              loading={isLoading && !conversations.length}
              onOpen={openThread}
              onNew={() => startNew()}
            />
          )}
          {view === 'thread' && activeIdentifier && (
            <SmsThread
              key={activeIdentifier}
              identifier={activeIdentifier}
              conversation={active}
              canSend={canSend}
              reason={reason}
              onChanged={() => { refetchConversations(); alerts.refetch(); }}
            />
          )}
          {view === 'new' && (
            <SmsNewConversation
              initialTo={draftTo}
              conversations={conversations}
              canSend={canSend}
              reason={reason}
              onOpenThread={openThread}
              onChanged={() => { refetchConversations(); alerts.refetch(); }}
            />
          )}
        </div>
      )}
    </>,
    document.body,
  );
}
