import {
  useQuery,
  // @ts-ignore -- generated by Wasp on next restart
  getSmsReplyAlerts,
} from 'wasp/client/operations';
import { SMS_POLL_MS } from '../polling';

/**
 * L'unique porte d'entrée sur `getSmsReplyAlerts`.
 *
 * React Query dédoublonne sur `[route, arguments]` : tous les appelants doivent
 * donc passer exactement `undefined` — un `{}` égaré créerait une seconde entrée
 * de cache et doublerait le trafic. Un `refetchInterval` divergent serait pire
 * encore : React Query retient le plus court pour tous les observateurs. D'où ce
 * hook, qui rend ces options impossibles à faire diverger.
 */
export function useSmsAlerts(opts?: { enabled?: boolean }) {
  const { data, refetch } = useQuery(getSmsReplyAlerts, undefined, {
    enabled: opts?.enabled ?? true,
    refetchInterval: SMS_POLL_MS,
    // Une réponse arrivée pendant que l'onglet était en arrière-plan doit être
    // là au retour, sans attendre le prochain battement.
    refetchOnWindowFocus: true,
  });
  const d = data as any;
  return {
    /** Tout le non-lu : ce que compte la bulle de messagerie. */
    total: (d?.total ?? 0) as number,
    /** Non-lu rattaché à un prospect vivant : ce que compte la pastille Prospection. */
    leadTotal: (d?.leadTotal ?? 0) as number,
    /** Non-lu sans carte de prospect : ne se lit que dans la messagerie. */
    otherTotal: (d?.otherTotal ?? 0) as number,
    bySearch: (d?.bySearch ?? {}) as Record<string, number>,
    inboxEnabled: !!d?.inboxEnabled,
    loaded: data !== undefined,
    refetch,
  };
}
