import { useState, useRef, useEffect, useMemo, useCallback } from 'react';
import { useSearchParams } from 'react-router';
import toast from 'react-hot-toast';
import { KanbanComponent, ColumnsDirective, ColumnDirective } from '@syncfusion/ej2-react-kanban';
import { extend } from '@syncfusion/ej2-base';
import {
  useQuery,
  getLeadSearches,
  getLeadSearchDetail,
  searchLeads,
  updateLead,
  deleteLeadSearch,
  // @ts-ignore -- generated by Wasp on next restart
  updateLeadSearch,
  exportLeads,
  getLeadStatusConfigs,
  createLeadStatusConfig,
  updateLeadStatusConfig,
  deleteLeadStatusConfig,
  getCurrentCompany,
  // @ts-ignore -- generated by Wasp on next restart
  reorderLeadStatusConfigs,
  // @ts-ignore -- generated by Wasp on next restart
  getLeadNotes,
  // @ts-ignore -- generated by Wasp on next restart
  addLeadNote,
  // @ts-ignore -- generated by Wasp on next restart
  deleteLeadNote,
  // @ts-ignore -- generated by Wasp on next restart
  sendProspectEmail,
  // @ts-ignore -- generated by Wasp on next restart
  getLeadEmailDraft,
  // @ts-ignore -- generated by Wasp on next restart
  saveLeadEmailDraft,
  // @ts-ignore -- generated by Wasp on next restart
  clearLeadEmailSent,
  // @ts-ignore -- generated by Wasp on next restart
  generateProspectEmail,
} from 'wasp/client/operations';
import type { Lead, LeadSearch, LeadStatusConfig } from 'wasp/entities';
import {
  PageHeader,
  EmptyState,
  Modal,
  useConfirm,
  IconBtn,
  TrashIcon,
  EditIcon,
} from '../../client/ui';
import {
  LuSearch,
  LuDownload,
  LuExternalLink,
  LuCopy,
  LuCheck,
  LuLoader,
  LuMapPin,
  LuPhone,
  LuMail,
  LuGlobe,
  LuStar,
  LuChevronLeft,
  LuRefreshCw,
  LuSlidersHorizontal,
  LuUsers,
  LuNotebook,
  LuTriangleAlert,
  LuPlus,
  LuPencil,
  LuTrash2,
  LuGripVertical,
  LuLock,
  LuSend,
  LuSave,
  LuRotateCcw,
  LuWand,
} from 'react-icons/lu';
import { MagicInput, MagicTextarea } from '../../client/magic';

// ─── Constants ────────────────────────────────────────────────────────────────

const PROVINCES = ['QC', 'ON', 'BC', 'AB', 'MB', 'SK', 'NS', 'NB', 'NL', 'PE', 'YT', 'NT', 'NU'];

const BUSINESS_TYPE_SUGGESTIONS = [
  'Agence web', 'Agence marketing', 'Agence de communication',
  'Plombier', 'Électricien', 'Menuisier', 'Peintre', 'Entrepreneur général',
  'Architecte', 'Designer intérieur',
  'Restaurant', 'Café', 'Boulangerie', 'Traiteur',
  'Avocat', 'Notaire', 'Comptable', 'Fiscaliste',
  'Médecin', 'Dentiste', 'Physiothérapeute', 'Chiropraticien',
  'Salon de coiffure', 'Salon de beauté', 'Spa',
  'Photographe', 'Vidéaste', 'Studio photo',
  'Mécanicien auto', 'Carrossier',
  'École privée', 'Centre de formation', 'Tuteur',
  'Gym', 'Centre de conditionnement physique', 'Studio yoga',
  'Nettoyage commercial', 'Service de ménage',
  'Fleuriste', 'Boutique cadeaux', 'Librairie',
  'Hôtel', 'Auberge', 'Chalet à louer',
  'Clinique vétérinaire',
  'Garderie', 'CPE',
];

const RADIUS_OPTIONS = [
  { value: 5000, label: '5 km' },
  { value: 10000, label: '10 km' },
  { value: 25000, label: '25 km' },
  { value: 50000, label: '50 km' },
];

const RATING_OPTIONS = [
  { value: 0, label: 'Aucune restriction' },
  { value: 3, label: '3+ étoiles' },
  { value: 4, label: '4+ étoiles' },
  { value: 4.5, label: '4.5+ étoiles' },
];

const MAX_RESULTS_OPTIONS = [
  { value: 10, label: '10 résultats' },
  { value: 20, label: '20 résultats' },
  { value: 40, label: '40 résultats (plus lent)' },
];

const LEAD_STATUS = {
  nouveau: { label: 'Nouveau', className: 'badge-info' },
  contacte: { label: 'Contacté', className: 'badge-neutral' },
  qualifie: { label: 'Qualifié', className: 'badge-success' },
  rejete: { label: 'Rejeté', className: 'bg-red-50 text-red-600 text-xs font-medium px-2 py-0.5 rounded-full' },
} as const;

// ─── Default form state ───────────────────────────────────────────────────────

function defaultForm() {
  return {
    title: '',
    description: '',
    purpose: '',
    businessType: '',
    city: '',
    province: 'QC',
    radius: 10000,
    minRating: 0,
    requireWebsite: false,
    maxResults: 20,
    language: 'fr',
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function Stars({ value }: { value: number | null }) {
  if (value === null) return <span className='text-muted text-xs'>—</span>;
  return (
    <span className='inline-flex items-center gap-1 text-sm'>
      <LuStar size={13} className='text-amber-400 fill-amber-400' />
      <span className='font-medium'>{value.toFixed(1)}</span>
    </span>
  );
}

// ─── Status dropdown ─────────────────────────────────────────────────────────

function StatusDropdown({ lead, statusConfigs, onRefetch }: { lead: Lead; statusConfigs: LeadStatusConfig[]; onRefetch: () => void }) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [open]);

  async function pick(status: string) {
    setOpen(false);
    try {
      await updateLead({ id: lead.id, status });
      onRefetch();
    } catch {
      toast.error('Erreur lors de la mise à jour');
    }
  }

  const current = statusConfigs.find(s => s.key === lead.status)
    ?? statusConfigs.find(s => s.key === 'unknown')
    ?? { label: lead.status, color: '#9ca3af', key: lead.status };

  return (
    <div ref={ref} className='relative inline-block'>
      <button
        className='cursor-pointer select-none flex items-center gap-1 text-xs font-medium px-2 py-0.5 rounded-full border'
        style={{
          backgroundColor: current.color + '18',
          borderColor: current.color + '55',
          color: current.color,
        }}
        onClick={() => setOpen(v => !v)}
      >
        {current.label}
        <svg className='w-3 h-3 opacity-60' viewBox='0 0 20 20' fill='currentColor'>
          <path fillRule='evenodd' d='M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z' clipRule='evenodd' />
        </svg>
      </button>
      {open && (
        <div className='absolute z-20 mt-1 left-0 bg-white border border-line rounded-xl shadow-lg py-1 min-w-[150px]'>
          {statusConfigs.filter(s => s.key !== 'unknown').map(s => (
            <button
              key={s.key}
              className={`w-full text-left px-3 py-2 text-sm hover:bg-canvas transition-colors flex items-center gap-2 ${
                lead.status === s.key ? 'font-semibold' : ''
              }`}
              onClick={() => pick(s.key)}
            >
              <span
                className='text-xs font-medium px-2 py-0.5 rounded-full border'
                style={{
                  backgroundColor: s.color + '18',
                  borderColor: s.color + '55',
                  color: s.color,
                }}
              >
                {s.label}
              </span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Copy button ──────────────────────────────────────────────────────────────

function CopyBtn({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  if (!text) return null;
  return (
    <button
      title='Copier'
      className='inline-flex items-center justify-center w-6 h-6 rounded hover:bg-canvas transition-colors text-muted hover:text-ink'
      onClick={() => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      }}
    >
      {copied ? <LuCheck size={12} className='text-green-600' /> : <LuCopy size={12} />}
    </button>
  );
}

// ─── New search form ──────────────────────────────────────────────────────────

function SearchForm({ onClose, onDone, initialValues, readOnly }: { onClose: () => void; onDone: (id: string) => void; initialValues?: Partial<ReturnType<typeof defaultForm>>; readOnly?: boolean }) {
  const [form, setForm] = useState(() => ({ ...defaultForm(), ...initialValues }));
  const [loading, setLoading] = useState(false);

  function set(field: string, value: any) {
    setForm(prev => ({ ...prev, [field]: value }));
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!form.businessType.trim()) return toast.error('Type d\'entreprise requis');
    if (!form.city.trim()) return toast.error('Ville requise');
    setLoading(true);
    try {
      // @ts-ignore -- purpose added, Wasp will regen types on restart
      const result = await searchLeads({
        title: form.title || `${form.businessType} — ${form.city}`,
        description: form.description || undefined,
        // @ts-ignore
        purpose: form.purpose || undefined,
        filters: {
          businessType: form.businessType,
          city: form.city,
          province: form.province,
          radius: form.radius,
          minRating: form.minRating,
          requireWebsite: form.requireWebsite,
          maxResults: form.maxResults,
          language: form.language,
        },
      });
      toast.success(`${result.leads?.length ?? 0} prospect(s) trouvé(s)`);
      onDone(result.id);
    } catch (err: any) {
      const msg = err?.message ?? 'Erreur lors de la recherche';
      if (msg.includes('GOOGLE_PLACES_API_KEY')) {
        toast.error('Clé API Google Places manquante. Ajoutez GOOGLE_PLACES_API_KEY dans .env.server.', { duration: 6000 });
      } else {
        toast.error(msg);
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className='space-y-5'>
      {!readOnly && (
        <p className='text-sm text-muted'>
          Décrivez le type d'entreprise que vous cherchez, choisissez la zone géographique et
          lancez la prospection. Gestia extraira les coordonnées depuis Google Maps.
        </p>
      )}

      {/* Title */}
      <div>
        <label className='label'>Nom de la recherche</label>
        <input
          className='input'
          placeholder='Ex : Plombiers Montréal — Mai 2026'
          value={form.title}
          onChange={e => set('title', e.target.value)}
          disabled={readOnly}
        />
        {!readOnly && <p className='text-xs text-muted mt-1'>Laissez vide pour générer automatiquement.</p>}
      </div>

      {!readOnly && (
        <div>
          <label className='label'>Objectif de la prospection <span className='text-muted font-normal'>(optionnel)</span></label>
          <input
            className='input'
            placeholder='Ex : proposer une refonte de site web, offrir un audit SEO gratuit…'
            value={form.purpose}
            onChange={e => set('purpose', e.target.value)}
          />
          <p className='text-xs text-muted mt-1'>L’IA utilisera cet objectif pour rédiger les courriels de tous les prospects de cette recherche.</p>
        </div>
      )}

      <hr className='border-line' />

      {/* Business type */}
      <div>
        <label className='label required'>Type d'entreprise / secteur</label>
        <input
          className='input'
          list='biz-types'
          placeholder='Ex : Agence web, Plombier, Restaurant…'
          value={form.businessType}
          onChange={e => set('businessType', e.target.value)}
          required={!readOnly}
          disabled={readOnly}
        />
        {!readOnly && (
          <>
            <datalist id='biz-types'>
              {BUSINESS_TYPE_SUGGESTIONS.map(s => (
                <option key={s} value={s} />
              ))}
            </datalist>
            <p className='text-xs text-muted mt-1'>
              Soyez précis : "Agence web React" donne de meilleurs résultats que "agence".
            </p>
          </>
        )}
      </div>

      {/* Location */}
      <div className='grid grid-cols-2 gap-3'>
        <div>
          <label className='label required'>Ville</label>
          <input
            className='input'
            placeholder='Ex : Montréal, Québec, Laval'
            value={form.city}
            onChange={e => set('city', e.target.value)}
            required={!readOnly}
            disabled={readOnly}
          />
        </div>
        <div>
          <label className='label'>Province</label>
          <select className='input' value={form.province} onChange={e => set('province', e.target.value)} disabled={readOnly}>
            {PROVINCES.map(p => <option key={p} value={p}>{p}</option>)}
          </select>
        </div>
      </div>

      {/* Radius + Rating */}
      <div className='grid grid-cols-2 gap-3'>
        <div>
          <label className='label'>Rayon de recherche</label>
          <select className='input' value={form.radius} onChange={e => set('radius', Number(e.target.value))} disabled={readOnly}>
            {RADIUS_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>
        <div>
          <label className='label'>Note Google minimale</label>
          <select className='input' value={form.minRating} onChange={e => set('minRating', Number(e.target.value))} disabled={readOnly}>
            {RATING_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>
      </div>

      {/* Max results + language */}
      <div className='grid grid-cols-2 gap-3'>
        <div>
          <label className='label'>Nombre de résultats</label>
          <select className='input' value={form.maxResults} onChange={e => set('maxResults', Number(e.target.value))} disabled={readOnly}>
            {MAX_RESULTS_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>
        <div>
          <label className='label'>Langue des résultats</label>
          <select className='input' value={form.language} onChange={e => set('language', e.target.value)} disabled={readOnly}>
            <option value='fr'>Français</option>
            <option value='en'>Anglais</option>
          </select>
        </div>
      </div>

      {/* Toggles */}
      <label className={`flex items-center gap-3 select-none ${readOnly ? 'cursor-default opacity-70' : 'cursor-pointer'}`}>
        <input
          type='checkbox'
          className='w-4 h-4 rounded accent-accent-600'
          checked={form.requireWebsite}
          onChange={e => set('requireWebsite', e.target.checked)}
          disabled={readOnly}
        />
        <span className='text-sm'>Exiger un site web (filtre les entreprises sans site)</span>
      </label>

      {!readOnly && (
        <div className='bg-blue-50 border border-blue-200 rounded-xl p-4 text-sm text-blue-800'>
          <p className='font-medium mb-1'>Ce que Gestia va extraire :</p>
          <ul className='space-y-0.5 text-blue-700 text-xs list-disc list-inside'>
            <li>Nom, adresse, ville, code postal</li>
            <li>Numéro de téléphone (si disponible sur Google)</li>
            <li>Site web + tentative d'extraction du courriel</li>
            <li>Note Google et nombre d'avis</li>
            <li>Lien Google Maps</li>
          </ul>
          <p className='mt-2 text-xs text-blue-600'>
            Nécessite <code className='bg-blue-100 px-1 rounded'>GOOGLE_PLACES_API_KEY</code> dans votre fichier <code className='bg-blue-100 px-1 rounded'>.env.server</code>.
          </p>
        </div>
      )}

      {loading && (
        <div className='flex items-center gap-3 text-sm text-accent-700 bg-accent-50 border border-accent-200 rounded-xl p-4'>
          <LuLoader size={18} className='animate-spin shrink-0' />
          <span>Recherche en cours… cela peut prendre jusqu'à 30 secondes selon le nombre de résultats.</span>
        </div>
      )}

      <div className='flex justify-end gap-2 pt-2'>
        <button type='button' className='btn-secondary' onClick={onClose} disabled={loading}>
          {readOnly ? 'Fermer' : 'Annuler'}
        </button>
        {!readOnly && (
          <button type='submit' className='btn-primary gap-2' disabled={loading}>
            {loading ? <LuLoader size={16} className='animate-spin' /> : <LuSearch size={16} />}
            Lancer la prospection
          </button>
        )}
      </div>
    </form>
  );
}

// ─── Edit lead modal ─────────────────────────────────────────────────────────

function EditLeadModal({ lead, onClose }: { lead: Lead; onClose: () => void }) {
  const [form, setForm] = useState({
    name: lead.name,
    phone: lead.phone ?? '',
    email: lead.email ?? '',
    website: lead.website ?? '',
    address: lead.address ?? '',
    category: lead.category ?? '',
  });
  const [saving, setSaving] = useState(false);

  function set(field: string, value: string) {
    setForm(f => ({ ...f, [field]: value }));
  }

  async function save() {
    setSaving(true);
    try {
      await updateLead({
        id: lead.id,
        name: form.name.trim() || undefined,
        phone: form.phone.trim() || undefined,
        email: form.email.trim() || undefined,
        website: form.website.trim() || undefined,
        address: form.address.trim() || undefined,
        category: form.category.trim() || undefined,
      });
      toast.success('Prospect mis à jour');
      onClose();
    } catch {
      toast.error('Erreur lors de la sauvegarde');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className='space-y-4'>
      <div className='grid grid-cols-1 sm:grid-cols-2 gap-3'>
        <div className='sm:col-span-2'>
          <label className='label'>Nom de l'entreprise</label>
          <input className='input' value={form.name} onChange={e => set('name', e.target.value)} />
        </div>
        <div>
          <label className='label'>Téléphone</label>
          <input className='input' type='tel' value={form.phone} onChange={e => set('phone', e.target.value)} placeholder='—' />
        </div>
        <div>
          <label className='label'>Courriel</label>
          <input className='input' type='email' value={form.email} onChange={e => set('email', e.target.value)} placeholder='—' />
        </div>
        <div className='sm:col-span-2'>
          <label className='label'>Site web</label>
          <input className='input' type='url' value={form.website} onChange={e => set('website', e.target.value)} placeholder='https://…' />
        </div>
        <div className='sm:col-span-2'>
          <label className='label'>Adresse</label>
          <input className='input' value={form.address} onChange={e => set('address', e.target.value)} placeholder='—' />
        </div>
        <div>
          <label className='label'>Catégorie</label>
          <input className='input' value={form.category} onChange={e => set('category', e.target.value)} placeholder='—' />
        </div>
      </div>
      <div className='flex justify-end gap-2 pt-1'>
        <button className='btn-secondary' onClick={onClose}>Annuler</button>
        <button className='btn-primary' onClick={save} disabled={saving}>
          {saving ? 'Sauvegarde…' : 'Sauvegarder'}
        </button>
      </div>
    </div>
  );
}

// ─── Note modal ───────────────────────────────────────────────────────────────

// ─── Montreal timezone helper ─────────────────────────────────────────────

function formatMontrealTime(date: string | Date): string {
  return new Intl.DateTimeFormat('fr-CA', {
    timeZone: 'America/Toronto',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date(date));
}

// ─── Note timeline modal ─────────────────────────────────────────────────

// ─── Prospect email modal ────────────────────────────────────────────────────

function ProspectEmailModal({ lead, onClose, onSent }: { lead: Lead; onClose: () => void; onSent: () => void }) {
  const identifier = (lead as any).placeId ?? lead.id;
  const { data: company } = useQuery(getCurrentCompany);
  const { data: draft } = useQuery(
    // @ts-ignore -- generated by Wasp on next restart
    getLeadEmailDraft,
    { identifier },
  );

  const [to, setTo] = useState<string>('');
  const [cc, setCc] = useState<string>('');
  const [subject, setSubject] = useState<string>(`${lead.name} — Prise de contact`);
  const [body, setBody] = useState<string>('');
  const [sending, setSending] = useState(false);
  const [savingDraft, setSavingDraft] = useState(false);
  const [clearingStatus, setClearingStatus] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [initialized, setInitialized] = useState(false);

  // Populate fields from draft or defaults once data loads
  useEffect(() => {
    if (initialized) return;
    const companyEmail = (company as any)?.email ?? '';
    if (draft !== undefined) {
      setTo((draft as any)?.to || (lead as any).email || '');
      setCc((draft as any)?.cc || companyEmail);
      setSubject((draft as any)?.subject || `${lead.name} — Prise de contact`);
      setBody((draft as any)?.body || '');
      setInitialized(true);
    } else if (company !== undefined) {
      setTo((lead as any).email || '');
      setCc(companyEmail);
      setInitialized(true);
    }
  }, [draft, company, initialized]);

  async function handleSaveDraft() {
    setSavingDraft(true);
    try {
      await (saveLeadEmailDraft as any)({ identifier, to, cc, subject, body });
      toast.success('Brouillon enregistré');
    } catch (err: any) {
      toast.error(err?.message || 'Erreur');
    } finally {
      setSavingDraft(false);
    }
  }

  async function handleGenerate() {
    setGenerating(true);
    try {
      const result = await (generateProspectEmail as any)({
        searchId: lead.searchId,
        leadName: lead.name,
        leadCategory: (lead as any).category ?? null,
        leadAddress: (lead as any).address ?? null,
        leadEmail: (lead as any).email ?? null,
        currentSubject: subject.trim() || null,
        currentBody: body.trim() || null,
      });
      if (result.subject) setSubject(result.subject);
      if (result.body) setBody(result.body);
      toast.success('Brouillon généré');
    } catch (err: any) {
      toast.error(err?.message || 'Erreur lors de la génération');
    } finally {
      setGenerating(false);
    }
  }

  async function handleClearStatus() {
    setClearingStatus(true);
    try {
      await (clearLeadEmailSent as any)({ identifier });
      toast.success('Statut réinitialisé');
      onSent();
    } catch (err: any) {
      toast.error(err?.message || 'Erreur');
    } finally {
      setClearingStatus(false);
    }
  }

  async function handleSubmit() {
    if (!to.trim()) { toast.error('Destinataire requis'); return; }
    if (!subject.trim()) { toast.error('Objet requis'); return; }
    setSending(true);
    try {
      await (sendProspectEmail as any)({
        identifier,
        to: to.trim(),
        cc: cc.trim() || null,
        subject: subject.trim(),
        body,
      });
      toast.success('Courriel envoyé');
      onSent();
      onClose();
    } catch (err: any) {
      toast.error(err?.message || "Erreur lors de l'envoi");
    } finally {
      setSending(false);
    }
  }

  return (
    <div className='space-y-4'>
      <div className='flex justify-end -mt-1 -mb-1'>
        <button
          className='btn-ghost px-2 py-1 text-violet-500 flex items-center gap-1.5 text-xs'
          onClick={handleGenerate}
          disabled={sending || generating || savingDraft}
          title={generating ? 'Génération…' : 'Générer avec l\u2019IA'}
        >
          {generating ? <LuLoader size={13} className='animate-spin' /> : <LuWand size={13} />}
          {generating ? 'Génération…' : 'Rédiger avec l\u2019IA'}
        </button>
      </div>
      {!(lead as any).email && (
        <div className='text-xs bg-amber-50 border border-amber-200 rounded-md px-3 py-2 text-amber-700'>
          Aucun courriel trouvé pour ce prospect. Vous pouvez en saisir un manuellement.
        </div>
      )}
      <div>
        <label className='label'>À (destinataire)</label>
        <input type='email' className='input' value={to} onChange={e => setTo(e.target.value)} placeholder='contact@entreprise.com' />
      </div>
      <div>
        <label className='label'>Cc</label>
        <input type='text' className='input' value={cc} onChange={e => setCc(e.target.value)} placeholder='vous@entreprise.com' />
        <span className='text-xs text-muted mt-1 block'>Séparez plusieurs adresses par des virgules.</span>
      </div>
      <div>
        <label className='label'>Objet</label>
        <MagicInput type='text' className='input' value={subject} onChange={e => setSubject(e.target.value)} />
      </div>
      <div>
        <label className='label'>Message</label>
        <MagicTextarea className='input min-h-[160px] resize-y' value={body} onChange={e => setBody(e.target.value)} />
      </div>
      <div className='flex justify-between items-center pt-2'>
        <div className='flex gap-1'>
          <button
            className='btn-ghost p-2'
            onClick={handleSaveDraft}
            disabled={sending || savingDraft || clearingStatus || generating}
            title={savingDraft ? 'Enregistrement…' : 'Enregistrer brouillon'}
          >
            <LuSave size={16} />
          </button>
          {(lead as any).hasEmailSent && (
            <button
              className='btn-ghost p-2 text-success'
              onClick={handleClearStatus}
              disabled={sending || clearingStatus}
              title='Réinitialiser le statut envoyé'
            >
              <LuRotateCcw size={16} />
            </button>
          )}
        </div>
        <div className='flex gap-2'>
          <button className='btn-secondary' onClick={onClose} disabled={sending}>Annuler</button>
          <button className='btn-primary gap-1.5 flex items-center' onClick={handleSubmit} disabled={sending}>
            <LuSend size={14} />
            {sending ? 'Envoi…' : 'Envoyer'}
          </button>
        </div>
      </div>
    </div>
  );
}

function NoteModal({ lead, onClose }: { lead: Lead; onClose: () => void }) {
  const identifier = (lead as any).placeId ?? lead.id;
  const { data: notes = [], refetch } = useQuery(getLeadNotes, { identifier });
  const [text, setText] = useState('');
  const [saving, setSaving] = useState(false);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  // Scroll to bottom when new notes arrive
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [(notes as any[]).length]);

  async function handleAdd(e: React.FormEvent) {
    e.preventDefault();
    if (!text.trim()) return;
    setSaving(true);
    try {
      await addLeadNote({ leadId: lead.id, text });
      setText('');
      refetch();
    } catch {
      toast.error('Erreur lors de l\'ajout');
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete(id: string) {
    setDeletingId(id);
    try {
      await deleteLeadNote({ id });
      refetch();
    } catch {
      toast.error('Erreur lors de la suppression');
    } finally {
      setDeletingId(null);
    }
  }

  const noteList = notes as any[];

  return (
    <div className='flex flex-col gap-4'>
      {/* Timeline */}
      <div className='flex flex-col gap-3 max-h-80 overflow-y-auto pr-1'>
        {noteList.length === 0 ? (
          <p className='text-sm text-muted text-center py-6'>Aucune note pour ce prospect.</p>
        ) : (
          noteList.map(n => (
            <div key={n.id} className='flex gap-3 group'>
              {/* Timeline line + dot */}
              <div className='flex flex-col items-center'>
                <div className='w-2 h-2 rounded-full bg-accent-500 mt-1.5 shrink-0' />
                <div className='w-px flex-1 bg-line mt-1' />
              </div>
              <div className='flex-1 pb-3'>
                <div className='flex items-start justify-between gap-2'>
                  <p className='text-xs text-muted'>{formatMontrealTime(n.createdAt)}</p>
                  <button
                    className='opacity-0 group-hover:opacity-100 transition-opacity text-muted hover:text-red-500'
                    onClick={() => handleDelete(n.id)}
                    disabled={deletingId === n.id}
                    title='Supprimer'
                  >
                    {deletingId === n.id ? <LuLoader size={12} className='animate-spin' /> : <LuTrash2 size={12} />}
                  </button>
                </div>
                <p className='text-sm mt-0.5 whitespace-pre-wrap'>{n.text}</p>
              </div>
            </div>
          ))
        )}
        <div ref={bottomRef} />
      </div>

      {/* Add note form */}
      <form onSubmit={handleAdd} className='flex gap-2 border-t border-line pt-3'>
        <textarea
          className='input resize-none flex-1 text-sm'
          rows={2}
          placeholder='Ajouter une note…'
          value={text}
          onChange={e => setText(e.target.value)}
          onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleAdd(e as any); } }}
          autoFocus
        />
        <button type='submit' className='btn-primary self-end gap-1.5' disabled={saving || !text.trim()}>
          {saving ? <LuLoader size={14} className='animate-spin' /> : <LuSend size={14} />}
        </button>
      </form>
    </div>
  );
}

// ─── Manage statuses modal ────────────────────────────────────────────────────

function ManageStatusesModal({
  configs,
  onRefresh,
  onClose,
}: {
  configs: LeadStatusConfig[];
  onRefresh: () => void;
  onClose: () => void;
}) {
  const unknownEntry = configs.find(c => c.key === 'unknown');

  // Local ordered list for instant visual feedback
  const [ordered, setOrdered] = useState(() => configs.filter(c => c.key !== 'unknown'));
  useEffect(() => {
    setOrdered(configs.filter(c => c.key !== 'unknown'));
  }, [configs]);

  const [editId, setEditId] = useState<string | null>(null);
  const [editLabel, setEditLabel] = useState('');
  const [editColor, setEditColor] = useState('');
  const [newLabel, setNewLabel] = useState('');
  const [newColor, setNewColor] = useState('#6366f1');
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const dragIndex = useRef<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);

  function startEdit(c: LeadStatusConfig) {
    setEditId(c.id);
    setEditLabel(c.label);
    setEditColor(c.color);
    setConfirmDeleteId(null);
  }

  async function saveEdit() {
    if (!editId) return;
    setSaving(true);
    try {
      await updateLeadStatusConfig({ id: editId, label: editLabel, color: editColor });
      onRefresh();
      setEditId(null);
    } catch {
      toast.error('Erreur lors de la sauvegarde');
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete(id: string) {
    setSaving(true);
    try {
      await deleteLeadStatusConfig({ id });
      onRefresh();
      setConfirmDeleteId(null);
    } catch (e: any) {
      toast.error(e?.message ?? 'Erreur lors de la suppression');
    } finally {
      setSaving(false);
    }
  }

  async function handleCreate(e: React.FormEvent) {
    e.preventDefault();
    if (!newLabel.trim()) return;
    setSaving(true);
    try {
      await createLeadStatusConfig({
        key: newLabel,
        label: newLabel.trim(),
        color: newColor,
        order: ordered.length,
      });
      setNewLabel('');
      setNewColor('#6366f1');
      onRefresh();
    } catch (e: any) {
      toast.error(e?.message ?? 'Erreur lors de la création');
    } finally {
      setSaving(false);
    }
  }

  function handleDragStart(index: number) {
    dragIndex.current = index;
  }

  function handleDragEnter(index: number) {
    if (dragIndex.current === null || dragIndex.current === index) return;
    setDragOverIndex(index);
    const newList = [...ordered];
    const [moved] = newList.splice(dragIndex.current, 1);
    newList.splice(index, 0, moved);
    dragIndex.current = index;
    setOrdered(newList);
  }

  async function handleDragEnd() {
    setDragOverIndex(null);
    dragIndex.current = null;
    const items = ordered.map((c, i) => ({ id: c.id, order: i }));
    try {
      await reorderLeadStatusConfigs({ items });
      onRefresh();
    } catch {
      toast.error('Erreur lors du réordonnancement');
    }
  }

  return (
    <div className='space-y-4'>
      <div className='flex items-start gap-2.5 rounded-xl border border-amber-200 bg-amber-50 px-3.5 py-3 text-sm text-amber-800'>
        <LuTriangleAlert size={15} className='shrink-0 mt-0.5' />
        <p>Toute modification (renommage, réordonnancement, suppression) s'applique immédiatement à tous les prospects existants.</p>
      </div>
      <div className='space-y-2'>
      {ordered.map((c, index) => (
        <div
          key={c.id}
          draggable
          onDragStart={() => handleDragStart(index)}
          onDragEnter={() => handleDragEnter(index)}
          onDragEnd={handleDragEnd}
          onDragOver={e => e.preventDefault()}
          className={`flex items-center gap-2 p-2.5 rounded-xl border transition-colors ${
            dragOverIndex === index ? 'border-accent-400 bg-accent-50' : 'border-line'
          }`}
        >
          {editId === c.id ? (
            <>
              <input
                type='color'
                value={editColor}
                onChange={e => setEditColor(e.target.value)}
                className='w-7 h-7 rounded cursor-pointer border border-line shrink-0'
              />
              <input
                className='input flex-1 py-1.5 text-sm'
                value={editLabel}
                onChange={e => setEditLabel(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && saveEdit()}
                autoFocus
              />
              <button className='btn-primary py-1 px-2.5 text-xs' onClick={saveEdit} disabled={saving}>
                OK
              </button>
              <button className='btn-secondary py-1 px-2.5 text-xs' onClick={() => setEditId(null)}>
                Annuler
              </button>
            </>
          ) : (
            <>
              {/* Drag handle */}
              <span className='text-muted cursor-grab active:cursor-grabbing shrink-0' title='Glisser pour réordonner'>
                <LuGripVertical size={16} />
              </span>
              <div className='w-4 h-4 rounded-full shrink-0' style={{ backgroundColor: c.color }} />
              <span className='flex-1 text-sm font-medium'>{c.label}</span>
              <span className='text-xs text-muted font-mono bg-canvas px-1.5 py-0.5 rounded'>{c.key}</span>
              {confirmDeleteId === c.id ? (
                <div className='flex items-center gap-1.5'>
                  <span className='text-xs text-red-600 font-medium'>Supprimer ?</span>
                  <button
                    className='text-xs text-red-600 font-semibold hover:underline'
                    onClick={() => handleDelete(c.id)}
                    disabled={saving}
                  >
                    Oui
                  </button>
                  <button
                    className='text-xs text-muted hover:underline'
                    onClick={() => setConfirmDeleteId(null)}
                  >
                    Non
                  </button>
                </div>
              ) : (
                <>
                  <IconBtn title='Modifier' onClick={() => startEdit(c)}>
                    <LuPencil size={14} />
                  </IconBtn>
                  <IconBtn title='Supprimer' variant='danger' onClick={() => setConfirmDeleteId(c.id)}>
                    <LuTrash2 size={14} />
                  </IconBtn>
                </>
              )}
            </>
          )}
        </div>
      ))}

      {/* Locked unknown row */}
      {unknownEntry && (
        <div className='flex items-center gap-2 p-2.5 rounded-xl border border-line bg-canvas opacity-60'>
          <span className='shrink-0'><LuLock size={14} className='text-muted' /></span>
          <div className='w-4 h-4 rounded-full shrink-0' style={{ backgroundColor: unknownEntry.color }} />
          <span className='flex-1 text-sm font-medium'>{unknownEntry.label}</span>
          <span className='text-xs text-muted font-mono bg-canvas px-1.5 py-0.5 rounded'>{unknownEntry.key}</span>
          <span className='text-xs text-muted'>Verrouillé</span>
        </div>
      )}
      </div>

      <hr className='border-line' />

      <form onSubmit={handleCreate} className='flex items-center gap-2'>
        <input
          type='color'
          value={newColor}
          onChange={e => setNewColor(e.target.value)}
          className='w-7 h-7 rounded cursor-pointer border border-line shrink-0'
          title='Couleur du statut'
        />
        <input
          className='input flex-1'
          placeholder='Ex : En négociation'
          value={newLabel}
          onChange={e => setNewLabel(e.target.value)}
          required
        />
        <button type='submit' className='btn-primary gap-1.5 shrink-0' disabled={saving || !newLabel.trim()}>
          <LuPlus size={14} />
          Ajouter
        </button>
      </form>
      <p className='text-xs text-muted'>La clé (identifiant interne) est générée automatiquement depuis le nom.</p>
    </div>
  );
}

// ─── Leads kanban ─────────────────────────────────────────────────────────────

function LeadsKanban({
  leads,
  statusConfigs,
  refetch,
  onEdit,
  onNote,
  onEmail,
}: {
  leads: Lead[];
  statusConfigs: LeadStatusConfig[];
  refetch: () => void;
  onEdit: (lead: Lead) => void;
  onNote: (lead: Lead) => void;
  onEmail: (lead: Lead) => void;
}) {
  const onEditRef = useRef(onEdit);
  onEditRef.current = onEdit;
  const onNoteRef = useRef(onNote);
  onNoteRef.current = onNote;
  const onEmailRef = useRef(onEmail);
  onEmailRef.current = onEmail;

  const kanbanData = useMemo(
    () => extend([], leads.map(l => ({ ...l })), undefined, true) as any[],
    [leads],
  );

  async function handleDragStop(args: any) {
    if (!args?.data?.length) return;
    for (const card of args.data) {
      try {
        await updateLead({ id: card.id, status: card.status });
      } catch {
        toast.error('Erreur lors de la mise à jour du statut');
        refetch();
        return;
      }
    }
    refetch();
  }

  const cardTemplate = useCallback((props: any): React.ReactElement => {
    const lead = props as Lead & { notes?: string | null };
    return (
      <div className='p-3 space-y-2'>
        <div className='font-semibold text-sm leading-tight'>{lead.name}</div>
        <div className='space-y-0.5'>
          {lead.website && (
            <div className='flex items-center gap-1.5 text-xs'>
              <LuGlobe size={10} className='text-muted shrink-0' />
              <a
                href={lead.website}
                target='_blank'
                rel='noopener noreferrer'
                className='text-accent-700 hover:underline truncate'
                onClick={e => e.stopPropagation()}
              >
                {lead.website.replace(/^https?:\/\//, '').replace(/\/$/, '')}
              </a>
            </div>
          )}
          {lead.phone && (
            <div className='flex items-center gap-1.5 text-xs'>
              <LuPhone size={10} className='text-muted shrink-0' />
              <a
                href={`tel:${lead.phone}`}
                className='text-accent-700 hover:underline truncate'
                onClick={e => e.stopPropagation()}
              >
                {lead.phone}
              </a>
            </div>
          )}
          {lead.email && (
            <div className='flex items-center gap-1.5 text-xs'>
              <LuMail size={10} className='text-muted shrink-0' />
              <a
                href={`mailto:${lead.email}`}
                className='text-accent-700 hover:underline truncate'
                onClick={e => e.stopPropagation()}
              >
                {lead.email}
              </a>
            </div>
          )}
        </div>
        <div className='flex items-center gap-1.5 pt-1.5 border-t border-line'>
          {lead.rating != null && (
            <span className='flex items-center gap-0.5 text-xs'>
              <LuStar size={10} className='text-amber-400 fill-amber-400' />
              <span className='font-medium'>{Number(lead.rating).toFixed(1)}</span>
            </span>
          )}
          {lead.mapsUrl && (
            <a
              href={lead.mapsUrl}
              target='_blank'
              rel='noopener noreferrer'
              className='text-xs text-accent-700 hover:underline flex items-center gap-0.5'
              onClick={e => e.stopPropagation()}
            >
              <LuExternalLink size={10} />
              Maps
            </a>
          )}
          <div className='ml-auto flex items-center gap-1'>
            <button
              className='w-6 h-6 rounded flex items-center justify-center hover:bg-canvas text-muted hover:text-ink transition-colors relative'
              title='Envoyer un courriel'
              onClick={e => { e.stopPropagation(); onEmailRef.current(lead as Lead); }}
            >
              <LuSend size={11} />
              {(lead as any).hasEmailSent ? (
                <span className='absolute -top-0.5 -right-0.5 w-1.5 h-1.5 rounded-full bg-success pointer-events-none' />
              ) : (lead as any).hasEmailDraft ? (
                <span className='absolute -top-0.5 -right-0.5 w-1.5 h-1.5 rounded-full bg-amber-400 pointer-events-none' />
              ) : null}
            </button>
            <button
              className='w-6 h-6 rounded flex items-center justify-center hover:bg-canvas text-muted hover:text-ink transition-colors relative'
              title={lead.notes || (lead as any).hasNotes ? 'Voir les notes' : 'Ajouter une note'}
              onClick={e => { e.stopPropagation(); onNoteRef.current(lead as Lead); }}
            >
              <LuNotebook size={11} />
              {((lead as any).hasNotes || lead.notes) && (
                <span className='absolute -top-0.5 -right-0.5 w-1.5 h-1.5 rounded-full bg-accent-500 pointer-events-none' />
              )}
            </button>
            <button
              className='w-6 h-6 rounded flex items-center justify-center hover:bg-canvas text-muted hover:text-ink transition-colors'
              title='Modifier'
              onClick={e => { e.stopPropagation(); onEditRef.current(lead as Lead); }}
            >
              <LuPencil size={11} />
            </button>
          </div>
        </div>
      </div>
    );
  }, []);

  const columnHeaderTemplate = useCallback((props: any): React.ReactElement => {
    const config = statusConfigs.find(s => s.key === props.keyField);
    const color = config?.color ?? '#6366f1';
    return (
      <div className='flex items-center gap-2 px-1 py-0.5'>
        <div className='w-3 h-3 rounded-full shrink-0' style={{ backgroundColor: color }} />
        <span className='font-semibold text-sm'>{props.headerText}</span>
        <span className='text-xs text-muted ml-auto bg-canvas px-1.5 py-0.5 rounded-full'>
          {props.count ?? 0}
        </span>
      </div>
    );
  }, [statusConfigs]);

  if (statusConfigs.length === 0) {
    return <div className='text-muted text-sm py-8 text-center'>Chargement des statuts…</div>;
  }

  return (
    <div className='overflow-x-auto -mx-4 px-4'>
      <KanbanComponent
        id='prospect-kanban'
        keyField='status'
        dataSource={kanbanData}
        cardSettings={{ headerField: 'id', template: cardTemplate, showHeader: false }}
        dragStop={handleDragStop}
        cssClass='gestia-kanban'
      >
        <ColumnsDirective>
          {statusConfigs.map(s => (
            <ColumnDirective
              key={s.key}
              headerText={s.label}
              keyField={s.key}
              template={columnHeaderTemplate}
            />
          ))}
        </ColumnsDirective>
      </KanbanComponent>
    </div>
  );
}

// ─── Leads table ─────────────────────────────────────────────────────────────

function LeadsTable({ searchId, onBack, onShowDetails }: { searchId: string; onBack: () => void; onShowDetails: (values: ReturnType<typeof defaultForm>) => void }) {
  const [searchParams, setSearchParams] = useSearchParams();
  const statusFilter = searchParams.get('status') ?? '';
  const search2 = searchParams.get('q') ?? '';

  function setStatusFilter(val: string) {
    setSearchParams(prev => {
      const next = new URLSearchParams(prev);
      if (val) next.set('status', val); else next.delete('status');
      return next;
    });
  }

  function setSearch2(val: string) {
    setSearchParams(prev => {
      const next = new URLSearchParams(prev);
      if (val) next.set('q', val); else next.delete('q');
      return next;
    });
  }

  const { data: search, isLoading, refetch } = useQuery(getLeadSearchDetail, { searchId });
  const { data: statusConfigs = [], refetch: refetchStatuses } = useQuery(getLeadStatusConfigs);
  const { ask, Dialog: ConfirmDialog } = useConfirm();
  const [view, setView] = useState<'kanban' | 'table'>('kanban');
  const [noteTarget, setNoteTarget] = useState<Lead | null>(null);
  const [editTarget, setEditTarget] = useState<Lead | null>(null);
  const [emailTarget, setEmailTarget] = useState<Lead | null>(null);
  const [exporting, setExporting] = useState(false);

  if (isLoading) {
    return <div className='text-muted'>Chargement…</div>;
  }
  if (!search) return null;

  const leads: Lead[] = (search as any).leads ?? [];
  const filters: any = (search as any).filters ?? {};

  const filtered = leads.filter(l => {
    if (statusFilter && l.status !== statusFilter) return false;
    if (search2) {
      const q = search2.toLowerCase();
      return (
        l.name.toLowerCase().includes(q) ||
        (l.address ?? '').toLowerCase().includes(q) ||
        (l.email ?? '').toLowerCase().includes(q) ||
        (l.phone ?? '').toLowerCase().includes(q) ||
        (l.website ?? '').toLowerCase().includes(q)
      );
    }
    return true;
  });

  async function handleExport() {
    setExporting(true);
    try {
      const { csv } = await exportLeads({ searchId });
      const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(search?.title ?? 'export').replace(/[^a-z0-9]/gi, '_')}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      toast.error('Erreur lors de l\'export');
    } finally {
      setExporting(false);
    }
  }

  return (
    <>
      {ConfirmDialog}
      <Modal
        open={editTarget !== null}
        title={editTarget ? `Modifier — ${editTarget.name}` : 'Modifier'}
        onClose={() => setEditTarget(null)}
      >
        {editTarget && (
          <EditLeadModal lead={editTarget} onClose={() => { setEditTarget(null); refetch(); }} />
        )}
      </Modal>
      <Modal
        open={emailTarget !== null}
        title={emailTarget ? `Envoyer un courriel — ${emailTarget.name}` : 'Envoyer un courriel'}
        onClose={() => setEmailTarget(null)}
      >
        {emailTarget && (
          <ProspectEmailModal lead={emailTarget} onClose={() => setEmailTarget(null)} onSent={refetch} />
        )}
      </Modal>
      <Modal
        open={noteTarget !== null}
        title={noteTarget ? `Note — ${noteTarget.name}` : 'Note'}
        onClose={() => setNoteTarget(null)}
      >
        {noteTarget && (
          <NoteModal lead={noteTarget} onClose={() => { setNoteTarget(null); refetch(); }} />
        )}
      </Modal>

      {/* Header */}
      <div className='flex items-start justify-between gap-4 mb-5'>
        <div className='flex items-center gap-3'>
          <button className='btn-ghost gap-1.5 text-sm' onClick={onBack}>
            <LuChevronLeft size={16} /> Retour
          </button>
          <div>
            <h2 className='text-lg font-semibold'>{search.title}</h2>
            {search.description && (
              <p className='text-sm text-muted italic mb-1'>{search.description}</p>
            )}
            {(search as any).purpose && (
              <p className='text-xs text-muted mb-1'>Objectif : {(search as any).purpose}</p>
            )}
            <div className='flex flex-wrap gap-1.5 mt-1'>
              {filters.businessType && (
                <span className='badge-info'>{filters.businessType}</span>
              )}
              {filters.city && (
                <span className='badge-neutral flex items-center gap-1'>
                  <LuMapPin size={11} />{filters.city}{filters.province ? `, ${filters.province}` : ''}
                </span>
              )}
              {filters.radius && (
                <span className='badge-neutral'>
                  {RADIUS_OPTIONS.find(r => r.value === filters.radius)?.label ?? `${filters.radius / 1000} km`}
                </span>
              )}
              {filters.minRating > 0 && (
                <span className='badge-neutral flex items-center gap-1'>
                  <LuStar size={11} />{filters.minRating}+
                </span>
              )}
              {filters.requireWebsite && (
                <span className='badge-neutral flex items-center gap-1'>
                  <LuGlobe size={11} />Site web requis
                </span>
              )}
              {filters.language && (
                <span className='badge-neutral'>{filters.language === 'fr' ? 'Français' : 'English'}</span>
              )}
              <span className='text-xs text-muted self-center'>{leads.length} prospect(s)</span>
            </div>
          </div>
        </div>
        <div className='flex items-center gap-2 shrink-0'>
          {/* View toggle */}
          <div className='flex items-center border border-line rounded-lg overflow-hidden text-xs font-medium'>
            <button
              className={`px-3 py-1.5 transition-colors ${view === 'kanban' ? 'bg-accent-600 text-white' : 'text-muted hover:bg-canvas'}`}
              onClick={() => setView('kanban')}
            >
              Kanban
            </button>
            <button
              className={`px-3 py-1.5 transition-colors ${view === 'table' ? 'bg-accent-600 text-white' : 'text-muted hover:bg-canvas'}`}
              onClick={() => setView('table')}
            >
              Liste
            </button>
          </div>
          <button
            className='btn-ghost gap-2 text-sm'
            onClick={() => onShowDetails({
              title: search.title,
              description: (search as any).description ?? '',
              purpose: (search as any).purpose ?? '',
              businessType: filters.businessType ?? '',
              city: filters.city ?? '',
              province: filters.province ?? 'QC',
              radius: filters.radius ?? 10000,
              minRating: filters.minRating ?? 0,
              requireWebsite: filters.requireWebsite ?? false,
              maxResults: filters.maxResults ?? 20,
              language: filters.language ?? 'fr',
            })}
          >
            <LuSlidersHorizontal size={15} />
            Détails de la recherche
          </button>
          <button className='btn-secondary gap-2' onClick={handleExport} disabled={exporting}>
            {exporting ? <LuLoader size={15} className='animate-spin' /> : <LuDownload size={15} />}
            Exporter CSV
          </button>
        </div>
      </div>

      {view === 'kanban' ? (
        <LeadsKanban
          leads={leads}
          statusConfigs={statusConfigs as LeadStatusConfig[]}
          refetch={refetch}
          onEdit={setEditTarget}
          onNote={setNoteTarget}
          onEmail={setEmailTarget}
        />
      ) : (
        <>
          {/* Filters bar */}
          <div className='mb-4 flex items-center gap-3 flex-wrap'>
            <div className='relative'>
              <LuSearch size={15} className='absolute left-3 top-1/2 -translate-y-1/2 text-muted' />
              <input
                className='input pl-9 max-w-xs'
                placeholder='Rechercher…'
                value={search2}
                onChange={e => setSearch2(e.target.value)}
              />
            </div>
            <select className='input w-auto' value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
              <option value=''>Tous les statuts</option>
              {(statusConfigs as LeadStatusConfig[]).map(s => (
                <option key={s.key} value={s.key}>{s.label}</option>
              ))}
            </select>
            <span className='text-sm text-muted'>{filtered.length} résultat(s)</span>
          </div>

          {filtered.length === 0 ? (
            <div className='text-muted text-sm py-8 text-center'>Aucun prospect correspondant aux filtres.</div>
          ) : (
        <div className='overflow-x-auto rounded-xl border border-line'>
          <table className='w-full text-sm'>
            <thead>
              <tr className='bg-canvas border-b border-line'>
                <th className='text-left px-4 py-3 font-medium text-muted text-xs uppercase tracking-wide w-64'>Entreprise</th>
                <th className='text-left px-4 py-3 font-medium text-muted text-xs uppercase tracking-wide w-52'>Contact</th>
                <th className='text-left px-4 py-3 font-medium text-muted text-xs uppercase tracking-wide w-62 hidden xl:table-cell'>Site web</th>
                <th className='text-left px-4 py-3 font-medium text-muted text-xs uppercase tracking-wide hidden md:table-cell'>Note / Maps</th>
                <th className='text-left px-4 py-3 font-medium text-muted text-xs uppercase tracking-wide'>Statut</th>
                <th className='text-right px-4 py-3 font-medium text-muted text-xs uppercase tracking-wide'>Actions</th>
              </tr>
            </thead>
            <tbody className='divide-y divide-line'>
              {filtered.map(lead => {
                return (
                  <tr key={lead.id} className='hover:bg-canvas transition-colors'>
                    {/* Name + address + category */}
                    <td className='px-4 py-3 w-56'>
                      <div className='font-medium break-words'>{lead.name}</div>
                      {lead.category && (
                        <div className='text-xs text-muted capitalize break-words'>{lead.category}</div>
                      )}
                      {lead.address && (
                        <div className='flex items-start gap-1 text-xs text-muted mt-0.5'>
                          <LuMapPin size={10} className='shrink-0 mt-0.5' />
                          <span className='break-words'>{lead.address}</span>
                        </div>
                      )}
                      {(lead as any).duplicateSearchTitles?.length > 0 && (
                        <div className='mt-1 flex items-center gap-1 text-xs text-amber-600 bg-amber-50 border border-amber-200 rounded-md px-1.5 py-0.5' title={`Déjà trouvé dans : ${(lead as any).duplicateSearchTitles.join(', ')}`}>
                          <LuTriangleAlert size={11} className='shrink-0' />
                          <span className='truncate'>Déjà dans {(lead as any).duplicateSearchTitles.length === 1 ? `« ${(lead as any).duplicateSearchTitles[0]} »` : `${(lead as any).duplicateSearchTitles.length} recherches`}</span>
                        </div>
                      )}
                    </td>

                    {/* Phone + Email */}
                    <td className='px-4 py-3'>
                      <div className='flex flex-col gap-1'>
                        {lead.phone ? (
                          <div className='flex items-center gap-1'>
                            <LuPhone size={12} className='text-muted shrink-0' />
                            <a href={`tel:${lead.phone}`} className='text-accent-700 hover:underline whitespace-nowrap'>{lead.phone}</a>
                            <CopyBtn text={lead.phone} />
                          </div>
                        ) : (
                          <span className='text-muted text-xs flex items-center gap-1'><LuPhone size={12} />—</span>
                        )}
                        {lead.email ? (
                          <div className='flex items-center gap-1'>
                            <LuMail size={12} className='text-muted shrink-0' />
                            <a href={`mailto:${lead.email}`} className='text-accent-700 hover:underline' title={lead.email}>{lead.email}</a>
                            <CopyBtn text={lead.email} />
                          </div>
                        ) : (
                          <span className='text-muted text-xs flex items-center gap-1'><LuMail size={12} />Non trouvé</span>
                        )}
                      </div>
                    </td>

                    {/* Website */}
                    <td className='px-4 py-3 hidden xl:table-cell'>
                      {lead.website ? (
                        <div className='flex items-center gap-1'>
                          <LuGlobe size={12} className='text-muted shrink-0' />
                          <a
                            href={lead.website}
                            target='_blank'
                            rel='noopener noreferrer'
                            className='text-accent-700 hover:underline truncate max-w-[220px]'
                            title={lead.website}
                          >
                            {lead.website.replace(/^https?:\/\//, '').replace(/\/$/, '')}
                          </a>
                        </div>
                      ) : (
                        <span className='text-muted'>—</span>
                      )}
                    </td>

                    {/* Rating + Maps */}
                    <td className='px-4 py-3 hidden md:table-cell'>
                      <div>
                        {lead.mapsUrl ? (
                          <a href={lead.mapsUrl} target='_blank' rel='noopener noreferrer' className='hover:opacity-75 transition-opacity'>
                            <Stars value={lead.rating ?? null} />
                          </a>
                        ) : (
                          <Stars value={lead.rating ?? null} />
                        )}
                        {lead.reviewCount != null && lead.reviewCount > 0 && (
                          <div className='text-xs text-muted'>{lead.reviewCount} avis</div>
                        )}
                      </div>
                    </td>

                    {/* Status */}
                    <td className='px-4 py-3'>
                      <StatusDropdown lead={lead} statusConfigs={statusConfigs as LeadStatusConfig[]} onRefetch={refetch} />
                    </td>

                    {/* Actions */}
                    <td className='px-4 py-3'>
                      <div className='flex items-center justify-end gap-1'>
                        <div className='relative'>
                          <IconBtn title='Envoyer un courriel' onClick={() => setEmailTarget(lead)}>
                            <LuSend size={15} />
                          </IconBtn>
                          {(lead as any).hasEmailSent ? (
                            <span className='absolute -top-1 -right-1 w-2 h-2 rounded-full bg-success pointer-events-none' />
                          ) : (lead as any).hasEmailDraft ? (
                            <span className='absolute -top-1 -right-1 w-2 h-2 rounded-full bg-amber-400 pointer-events-none' />
                          ) : null}
                        </div>
                        <IconBtn title='Modifier le prospect' onClick={() => setEditTarget(lead)}>
                          <EditIcon />
                        </IconBtn>
                        <div className='relative'>
                          <IconBtn
                            title={lead.notes || (lead as any).hasNotes ? 'Voir les notes' : 'Ajouter une note'}
                            onClick={() => setNoteTarget(lead)}
                          >
                            <LuNotebook size={15} />
                          </IconBtn>
                          {((lead as any).hasNotes || lead.notes) && (
                            <span className='absolute -top-1 -right-1 w-2 h-2 rounded-full bg-accent-500 pointer-events-none' />
                          )}
                        </div>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
      </>
    )}
    </>
  );
}

// ─── Search list ──────────────────────────────────────────────────────────────

function EditSearchModal({ search, onClose }: { search: { id: string; title: string; purpose?: string | null }; onClose: () => void }) {
  const [form, setForm] = useState({ title: search.title, purpose: search.purpose ?? '' });
  const [saving, setSaving] = useState(false);
  const { data: searches, refetch } = useQuery(getLeadSearches);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!form.title.trim()) return;
    setSaving(true);
    try {
      // @ts-ignore
      await updateLeadSearch({ id: search.id, title: form.title, purpose: form.purpose || null });
      await refetch();
      toast.success('Prospection mise à jour');
      onClose();
    } catch {
      toast.error('Erreur lors de la mise à jour');
    } finally {
      setSaving(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className='flex flex-col gap-4'>
      <div>
        <label className='label'>Titre</label>
        <MagicInput
          className='input'
          value={form.title}
          onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
          placeholder='Titre de la recherche'
          autoFocus
          required
        />
      </div>
      <div>
        <label className='label'>
          Objectif <span className='text-muted font-normal'>(optionnel)</span>
        </label>
        <MagicInput
          className='input'
          value={form.purpose}
          onChange={e => setForm(f => ({ ...f, purpose: e.target.value }))}
          placeholder='Ex : proposer une refonte de site web, offrir un audit SEO gratuit…'
        />
        <p className='text-xs text-muted mt-1'>
          L'IA utilise cet objectif pour rédiger les courriels de tous les prospects de cette prospection.
          Si vide, elle adapte le message selon le contexte du prospect.
        </p>
      </div>
      <div className='flex justify-end gap-2 pt-1'>
        <button type='button' className='btn-ghost' onClick={onClose}>Annuler</button>
        <button type='submit' className='btn-primary' disabled={saving}>
          {saving ? 'Enregistrement…' : 'Enregistrer'}
        </button>
      </div>
    </form>
  );
}

function SearchList({
  onSelect,
  onNew,
  onDuplicate,
}: {
  onSelect: (id: string) => void;
  onNew: () => void;
  onDuplicate: (values: Partial<ReturnType<typeof defaultForm>>) => void;
}) {
  const { data: searches, isLoading } = useQuery(getLeadSearches);
  const { ask, Dialog: ConfirmDialog } = useConfirm();
  const [editTarget, setEditTarget] = useState<{ id: string; title: string; purpose?: string | null } | null>(null);

  async function handleDelete(id: string, title: string) {
    if (await ask(`Supprimer la recherche « ${title} » ?`, { description: 'Tous les prospects associés seront supprimés.' })) {
      try {
        await deleteLeadSearch({ id });
        toast.success('Recherche supprimée');
      } catch {
        toast.error('Erreur lors de la suppression');
      }
    }
  }

  if (isLoading) return <div className='text-muted text-sm'>Chargement…</div>;

  const list = searches ?? [];

  if (list.length === 0) {
    return (
      <EmptyState
        title='Aucune recherche'
        description='Lancez votre première prospection pour trouver des clients potentiels.'
        action={<button className='btn-primary' onClick={onNew}>Nouvelle recherche</button>}
      />
    );
  }

  return (
    <>
      {ConfirmDialog}
      <Modal
        open={editTarget !== null}
        title='Modifier la prospection'
        onClose={() => setEditTarget(null)}
      >
        {editTarget && (
          <EditSearchModal search={editTarget} onClose={() => setEditTarget(null)} />
        )}
      </Modal>
      <div className='grid md:grid-cols-2 lg:grid-cols-3 gap-4'>
        {list.map((s: any) => {
          const f: any = s.filters ?? {};
          const leadCount = s.leads?.length ?? s.totalFound ?? 0;
          return (
            <div
              key={s.id}
              role='button'
              tabIndex={0}
              className='card p-5 text-left hover:border-accent-300 transition-colors group cursor-pointer w-full'
              onClick={() => onSelect(s.id)}
              onKeyDown={e => e.key === 'Enter' && onSelect(s.id)}
            >
              <div className='flex items-start justify-between gap-2'>
                <h3 className='font-semibold text-sm leading-tight group-hover:text-accent-700 transition-colors'>
                  {s.title}
                </h3>
                <div onClick={e => e.stopPropagation()} className='flex items-center gap-1'>
                  <IconBtn
                    title='Modifier'
                    onClick={() => setEditTarget({ id: s.id, title: s.title, purpose: s.purpose ?? null })}
                  >
                    <LuPencil size={14} />
                  </IconBtn>
                  <IconBtn
                    title='Dupliquer les filtres'
                    onClick={() => onDuplicate({
                      businessType: f.businessType ?? '',
                      city: f.city ?? '',
                      province: f.province ?? 'QC',
                      radius: f.radius ?? 10000,
                      minRating: f.minRating ?? 0,
                      requireWebsite: f.requireWebsite ?? false,
                      maxResults: f.maxResults ?? 20,
                      language: f.language ?? 'fr',
                    })}
                  >
                    <LuRefreshCw size={14} />
                  </IconBtn>
                  <IconBtn
                    variant='danger'
                    title='Supprimer'
                    onClick={() => handleDelete(s.id, s.title)}
                  >
                    <TrashIcon />
                  </IconBtn>
                </div>
              </div>

              {s.description && (
                <p className='text-xs text-muted mt-1 line-clamp-2'>{s.description}</p>
              )}

              <div className='mt-3 flex items-center gap-2 text-xs text-muted'>
                {f.businessType && (
                  <span className='badge-neutral'>{f.businessType}</span>
                )}
                {f.city && (
                  <span className='flex items-center gap-1'>
                    <LuMapPin size={10} /> {f.city}
                  </span>
                )}
              </div>

              <div className='mt-3 flex items-center gap-1.5 text-xs'>
                <LuUsers size={12} className='text-accent-600' />
                <span className='font-semibold text-accent-700'>{leadCount}</span>
                <span className='text-muted'>prospect(s)</span>
              </div>
            </div>
          );
        })}
      </div>
    </>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function LeadSearchPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const selectedId = searchParams.get('id');
  const [showForm, setShowForm] = useState(false);
  const [formPrefill, setFormPrefill] = useState<Partial<ReturnType<typeof defaultForm>> | undefined>(undefined);
  const [showManageStatuses, setShowManageStatuses] = useState(false);
  const { data: statusConfigs = [], refetch: refetchStatuses } = useQuery(getLeadStatusConfigs);

  function handleDone(id: string) {
    setShowForm(false);
    setFormPrefill(undefined);
    setSearchParams({ id });
  }

  function handleSelect(id: string) {
    setSearchParams({ id });
  }

  function handleBack() {
    setSearchParams({});
  }

  function handleShowDetails(values: ReturnType<typeof defaultForm>) {
    setFormPrefill(values);
    setShowForm(true);
  }

  function handleDuplicate(values: Partial<ReturnType<typeof defaultForm>>) {
    setFormPrefill({ ...values, title: '' });
    setShowForm(true);
  }

  return (
    <>
      <Modal
        open={showManageStatuses}
        title='Gérer les statuts'
        onClose={() => setShowManageStatuses(false)}
      >
        <ManageStatusesModal
          configs={statusConfigs as LeadStatusConfig[]}
          onRefresh={refetchStatuses}
          onClose={() => setShowManageStatuses(false)}
        />
      </Modal>
      <Modal
        open={showForm}
        title={formPrefill && selectedId ? 'Détails de la recherche' : formPrefill ? 'Dupliquer la recherche' : 'Nouvelle prospection'}
        onClose={() => { setShowForm(false); setFormPrefill(undefined); }}
      >
        <SearchForm
          onClose={() => { setShowForm(false); setFormPrefill(undefined); }}
          onDone={handleDone}
          initialValues={formPrefill}
          readOnly={!!(formPrefill && selectedId)}
        />
      </Modal>

      <PageHeader
        title='Prospection'
        subtitle='Trouvez des entreprises à démarcher à partir de Google Maps.'
        actions={
          <div className='flex items-center gap-2'>
            {!selectedId && (
              <>
                <button className='btn-secondary gap-1.5' onClick={() => setShowManageStatuses(true)}>
                  <LuSlidersHorizontal size={14} />
                  Statuts
                </button>
                <button className='btn-primary gap-2' onClick={() => setShowForm(true)}>
                  <LuSearch size={16} />
                  Nouvelle recherche
                </button>
              </>
            )}
          </div>
        }
      />

      {selectedId ? (
        <LeadsTable searchId={selectedId} onBack={handleBack} onShowDetails={handleShowDetails} />
      ) : (
        <SearchList onSelect={handleSelect} onNew={() => setShowForm(true)} onDuplicate={handleDuplicate} />
      )}
    </>
  );
}
