/**
 * Right-side detail panel for a lead (Facebook lead-board style).
 * Opens when a card is clicked on the prospection board: shows the full
 * contact sheet, lets the user change the status, edit the info inline and
 * write notes without leaving the board.
 */

import { useState, useEffect, useRef } from 'react';
import toast from 'react-hot-toast';
import {
  useQuery,
  updateLead,
  // @ts-ignore -- generated by Wasp on next restart
  getLeadNotes,
  // @ts-ignore -- generated by Wasp on next restart
  addLeadNote,
  // @ts-ignore -- generated by Wasp on next restart
  deleteLeadNote,
} from 'wasp/client/operations';
import type { Lead, LeadStatusConfig } from 'wasp/entities';
import {
  LuX,
  LuPhone,
  LuMail,
  LuGlobe,
  LuMapPin,
  LuStar,
  LuExternalLink,
  LuPencil,
  LuSend,
  LuTrash2,
  LuUserPlus,
  LuUserCheck,
  LuClock,
  LuTriangleAlert,
  LuLoader,
  LuCheck,
  LuNotebook,
  LuMessageSquare,
} from 'react-icons/lu';
import {
  NoteThread,
  LeadEditForm,
  CopyBtn,
  formatMontrealTime,
  type LeadFormValues,
} from './leads.shared';

// ─── Read-only contact row ────────────────────────────────────────────────────

function InfoRow({
  icon,
  label,
  children,
  copyText,
}: {
  icon: React.ReactNode;
  label: string;
  children: React.ReactNode;
  copyText?: string;
}) {
  return (
    <div className='flex items-start gap-2.5 py-2'>
      <span className='text-muted mt-0.5 shrink-0'>{icon}</span>
      <div className='min-w-0 flex-1'>
        <div className='text-[11px] uppercase tracking-wide text-muted'>{label}</div>
        <div className='text-sm break-words'>{children}</div>
      </div>
      {copyText && <CopyBtn text={copyText} />}
    </div>
  );
}

// ─── Panel ────────────────────────────────────────────────────────────────────

export function LeadDetailPanel({
  lead: incomingLead,
  statusConfigs,
  existingClientNames,
  onClose,
  onRefetch,
  onEmail,
  onSms,
  onConvert,
  onDelete,
}: {
  lead: Lead | null;
  statusConfigs: LeadStatusConfig[];
  existingClientNames: Set<string>;
  onClose: () => void;
  onRefetch: () => void;
  onEmail: (lead: Lead) => void;
  onSms: (lead: Lead) => void;
  onConvert: (lead: Lead) => void;
  onDelete: (lead: Lead) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [savingStatus, setSavingStatus] = useState<string | null>(null);
  const [noteText, setNoteText] = useState('');
  const [savingNote, setSavingNote] = useState(false);
  const [deletingNoteId, setDeletingNoteId] = useState<string | null>(null);
  const [shown, setShown] = useState(false);
  // Keeps the last lead on screen while the panel slides back out.
  const [lead, setLead] = useState<Lead | null>(incomingLead);

  const leadId = lead?.id ?? null;
  const identifier = (lead as any)?.placeId ?? leadId;
  const { data: notes = [], refetch: refetchNotes } = useQuery(
    getLeadNotes,
    { identifier },
    { enabled: !!identifier } as any,
  );

  // Keep the rendered lead in sync with fresh data from the board.
  useEffect(() => {
    if (incomingLead) setLead(incomingLead);
  }, [incomingLead]);

  // Slide in when a lead is selected, slide out (then unmount) when cleared.
  useEffect(() => {
    if (incomingLead) {
      const t = window.setTimeout(() => setShown(true), 10);
      return () => window.clearTimeout(t);
    }
    setShown(false);
    const t = window.setTimeout(() => setLead(null), 200);
    return () => window.clearTimeout(t);
  }, [incomingLead?.id]);

  // Reset per-lead state when switching cards.
  useEffect(() => {
    setEditing(false);
    setNoteText('');
  }, [leadId]);

  // Escape closes the panel.
  useEffect(() => {
    if (!lead) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
    }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [lead, onClose]);

  const notesDirty = useRef(false);

  function handleClose() {
    if (notesDirty.current) {
      notesDirty.current = false;
      onRefetch();
    }
    onClose();
  }

  if (!lead) return null;

  const l = lead as any;
  const current =
    statusConfigs.find(s => s.key === lead.status) ??
    ({ label: lead.status, color: '#9ca3af', key: lead.status } as LeadStatusConfig);
  const alreadyClient = existingClientNames.has(lead.name.toLowerCase());

  async function handleStatus(key: string) {
    if (key === lead!.status) return;
    setSavingStatus(key);
    try {
      await updateLead({ id: lead!.id, status: key });
      onRefetch();
    } catch {
      toast.error('Erreur lors de la mise à jour du statut');
    } finally {
      setSavingStatus(null);
    }
  }

  async function handleSaveInfo(values: LeadFormValues) {
    await updateLead({
      id: lead!.id,
      name: values.name || undefined,
      phone: values.phone || undefined,
      email: values.email || undefined,
      website: values.website || undefined,
      address: values.address || undefined,
      category: values.category || undefined,
    });
    toast.success('Prospect mis à jour');
    setEditing(false);
    onRefetch();
  }

  async function handleAddNote(e: React.FormEvent) {
    e.preventDefault();
    if (!noteText.trim()) return;
    setSavingNote(true);
    try {
      await addLeadNote({ leadId: lead!.id, text: noteText });
      setNoteText('');
      notesDirty.current = true;
      refetchNotes();
    } catch {
      toast.error('Erreur lors de l\'ajout');
    } finally {
      setSavingNote(false);
    }
  }

  async function handleDeleteNote(id: string) {
    setDeletingNoteId(id);
    try {
      await deleteLeadNote({ id });
      notesDirty.current = true;
      refetchNotes();
    } catch {
      toast.error('Erreur lors de la suppression');
    } finally {
      setDeletingNoteId(null);
    }
  }

  return (
    <>
      {/* Backdrop — mobile only, so the board stays draggable on desktop. */}
      <div
        className={`fixed inset-0 bg-ink/40 z-[34] sm:hidden transition-opacity ${
          shown ? 'opacity-100' : 'opacity-0'
        }`}
        onClick={handleClose}
      />

      {/*
        The panel itself is the scroll container (header and footer stay pinned
        with `sticky`), and `overscroll-contain` keeps the wheel from reaching
        the board underneath once the panel hits its end.
      */}
      <aside
        className={`fixed inset-y-0 right-0 z-[35] w-full sm:w-[380px] lg:w-[420px] bg-white border-l border-line shadow-xl flex flex-col overflow-y-auto overscroll-contain transition-transform duration-200 ${
          shown ? 'translate-x-0' : 'translate-x-full'
        }`}
        role='dialog'
        aria-label={`Détails — ${lead.name}`}
      >
        {/* Header */}
        <div className='sticky top-0 z-10 shrink-0 bg-white px-5 py-4 border-b border-line'>
          <div className='flex items-start gap-2'>
            <div className='min-w-0 flex-1'>
              <h2 className='font-semibold text-base leading-tight break-words'>{lead.name}</h2>
              {lead.category && (
                <p className='text-xs text-muted capitalize mt-0.5'>{lead.category}</p>
              )}
            </div>
            <button
              onClick={handleClose}
              className='text-muted hover:text-ink shrink-0'
              aria-label='Fermer'
            >
              <LuX size={18} />
            </button>
          </div>

          {/* Status picker */}
          <div className='mt-3'>
            <div className='text-[11px] uppercase tracking-wide text-muted mb-1.5'>Statut</div>
            <div className='flex flex-wrap gap-1.5'>
              {statusConfigs
                .filter(s => s.key !== 'unknown' || s.key === lead.status)
                .map(s => {
                  const active = s.key === current.key;
                  return (
                    <button
                      key={s.key}
                      onClick={() => handleStatus(s.key)}
                      disabled={savingStatus !== null}
                      className='text-xs font-medium px-2.5 py-1 rounded-full border transition-colors flex items-center gap-1 disabled:opacity-60'
                      style={
                        active
                          ? { backgroundColor: s.color, borderColor: s.color, color: '#fff' }
                          : { backgroundColor: s.color + '14', borderColor: s.color + '44', color: s.color }
                      }
                    >
                      {savingStatus === s.key ? (
                        <LuLoader size={10} className='animate-spin' />
                      ) : active ? (
                        <LuCheck size={10} />
                      ) : null}
                      {s.label}
                    </button>
                  );
                })}
            </div>
          </div>
        </div>

        {/* Body */}
        <div className='flex-1 px-5 py-4 space-y-5'>
          {l.duplicateSearchTitles?.length > 0 && (
            <div className='flex items-start gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-2.5 py-2'>
              <LuTriangleAlert size={13} className='shrink-0 mt-0.5' />
              <span>
                Déjà présent dans : {l.duplicateSearchTitles.join(', ')}
              </span>
            </div>
          )}

          {/* Contact info */}
          <section>
            <div className='flex items-center justify-between mb-1'>
              <h3 className='text-sm font-semibold'>Informations</h3>
              {!editing && (
                <button
                  className='text-xs text-accent-700 hover:underline flex items-center gap-1'
                  onClick={() => setEditing(true)}
                >
                  <LuPencil size={11} />
                  Modifier
                </button>
              )}
            </div>

            {editing ? (
              <LeadEditForm
                initialValues={{
                  name: lead.name,
                  phone: lead.phone ?? '',
                  email: lead.email ?? '',
                  website: lead.website ?? '',
                  address: lead.address ?? '',
                  category: lead.category ?? '',
                }}
                onSave={handleSaveInfo}
                onCancel={() => setEditing(false)}
              />
            ) : (
              <div className='divide-y divide-line'>
                <InfoRow icon={<LuPhone size={14} />} label='Téléphone' copyText={lead.phone ?? undefined}>
                  {lead.phone ? (
                    <a href={`tel:${lead.phone}`} className='text-accent-700 hover:underline'>
                      {lead.phone}
                    </a>
                  ) : (
                    <span className='text-muted'>—</span>
                  )}
                </InfoRow>
                <InfoRow icon={<LuMail size={14} />} label='Courriel' copyText={lead.email ?? undefined}>
                  {lead.email ? (
                    <a href={`mailto:${lead.email}`} className='text-accent-700 hover:underline'>
                      {lead.email}
                    </a>
                  ) : (
                    <span className='text-muted'>Non trouvé</span>
                  )}
                </InfoRow>
                <InfoRow icon={<LuGlobe size={14} />} label='Site web' copyText={lead.website ?? undefined}>
                  {lead.website ? (
                    <a
                      href={lead.website}
                      target='_blank'
                      rel='noopener noreferrer'
                      className='text-accent-700 hover:underline'
                    >
                      {lead.website.replace(/^https?:\/\//, '').replace(/\/$/, '')}
                    </a>
                  ) : (
                    <span className='text-muted'>—</span>
                  )}
                </InfoRow>
                <InfoRow icon={<LuMapPin size={14} />} label='Adresse' copyText={lead.address ?? undefined}>
                  {lead.address ?? <span className='text-muted'>—</span>}
                </InfoRow>
                <InfoRow icon={<LuStar size={14} />} label='Note Google'>
                  {lead.rating != null ? (
                    <span className='flex items-center gap-1.5'>
                      <span className='flex items-center gap-1'>
                        <LuStar size={12} className='text-amber-400 fill-amber-400' />
                        <span className='font-medium'>{Number(lead.rating).toFixed(1)}</span>
                      </span>
                      {lead.reviewCount != null && lead.reviewCount > 0 && (
                        <span className='text-muted text-xs'>{lead.reviewCount} avis</span>
                      )}
                      {lead.mapsUrl && (
                        <a
                          href={lead.mapsUrl}
                          target='_blank'
                          rel='noopener noreferrer'
                          className='text-accent-700 hover:underline text-xs flex items-center gap-0.5'
                        >
                          <LuExternalLink size={11} />
                          Maps
                        </a>
                      )}
                    </span>
                  ) : (
                    <span className='text-muted'>—</span>
                  )}
                </InfoRow>
                <InfoRow icon={<LuClock size={14} />} label='Ajouté le'>
                  <span className='text-muted'>{formatMontrealTime(lead.createdAt)}</span>
                  {lead.statusUpdatedAt && (
                    <span className='block text-xs text-muted'>
                      Statut modifié le {formatMontrealTime(lead.statusUpdatedAt)}
                    </span>
                  )}
                </InfoRow>
              </div>
            )}
          </section>

          {/* Notes */}
          <section>
            <h3 className='text-sm font-semibold mb-2 flex items-center gap-1.5'>
              <LuNotebook size={13} className='text-muted' />
              Notes
              {(notes as any[]).length > 0 && (
                <span className='text-xs text-muted font-normal'>({(notes as any[]).length})</span>
              )}
            </h3>
            <NoteThread
              notes={notes as any[]}
              text={noteText}
              setText={setNoteText}
              onSubmit={handleAddNote}
              onDelete={handleDeleteNote}
              saving={savingNote}
              deletingId={deletingNoteId}
              autoFocus={false}
              scrollable={false}
            />
          </section>
        </div>

        {/* Footer actions */}
        <div className='sticky bottom-0 z-10 shrink-0 px-5 py-3 border-t border-line bg-canvas-100 flex items-center gap-2'>
          <button
            className='btn-primary gap-1.5 text-sm flex-1 justify-center'
            onClick={() => onEmail(lead)}
            disabled={!lead.email}
            title={lead.email ? undefined : 'Aucun courriel pour ce prospect'}
          >
            <LuSend size={14} />
            {l.hasEmailSent ? 'Réenvoyer' : l.hasEmailDraft ? 'Brouillon' : 'Courriel'}
          </button>
          <button
            className={`btn-secondary gap-1.5 text-sm ${l.hasSmsSent ? 'text-success' : ''}`}
            onClick={() => onSms(lead)}
            disabled={!lead.phone}
            title={lead.phone ? (l.hasSmsSent ? 'Renvoyer un SMS' : 'Envoyer un SMS') : 'Aucun téléphone pour ce prospect'}
          >
            <LuMessageSquare size={14} />
            SMS
          </button>
          {lead.status === 'qualifie' &&
            (alreadyClient ? (
              <span
                className='btn-secondary gap-1.5 text-sm opacity-60 cursor-default'
                title='Déjà ajouté comme client'
              >
                <LuUserCheck size={14} />
                Client
              </span>
            ) : (
              <button
                className='btn-secondary gap-1.5 text-sm'
                onClick={() => onConvert(lead)}
                title='Créer un client depuis ce prospect'
              >
                <LuUserPlus size={14} />
                Client
              </button>
            ))}
          <button
            className='btn-danger gap-1.5 text-sm'
            onClick={() => onDelete(lead)}
            title='Supprimer ce prospect'
          >
            <LuTrash2 size={14} />
          </button>
        </div>
      </aside>
    </>
  );
}
