/**
 * Right-side detail panel for a lead (Facebook lead-board style).
 * Opens when a card is clicked on the prospection board: shows the full
 * contact sheet, lets the user change the status, edit the info inline and
 * write notes without leaving the board.
 */

import { useState, useEffect, useRef } from 'react';
import toast from 'react-hot-toast';
import {
  useQuery,
  updateLead,
  // @ts-ignore -- generated by Wasp on next restart
  getLeadNotes,
  // @ts-ignore -- generated by Wasp on next restart
  addLeadNote,
  // @ts-ignore -- generated by Wasp on next restart
  deleteLeadNote,
  // @ts-ignore -- generated by Wasp on next restart
  getLeadSourceConfigs,
  // @ts-ignore -- generated by Wasp on next restart
  markLeadViewed,
  // @ts-ignore -- generated by Wasp on next restart
  getLeadCardFields,
} from 'wasp/client/operations';
import type { Lead, LeadStatusConfig } from 'wasp/entities';
import { useSmsCapability, useEmailCapability } from '../../client/capabilities';
import {
  LuX,
  LuPhone,
  LuMail,
  LuGlobe,
  LuMapPin,
  LuStar,
  LuExternalLink,
  LuPencil,
  LuSend,
  LuTrash2,
  LuUserPlus,
  LuUserCheck,
  LuClock,
  LuTriangleAlert,
  LuLoader,
  LuCheck,
  LuNotebook,
  LuMessageSquare,
  LuInfo,
} from 'react-icons/lu';
import {
  NoteThread,
  LeadEditForm,
  CopyBtn,
  formatMontrealTime,
  leadExtras,
  leadSourceColor,
  extraFieldId,
  isExtraFieldKey,
  visibleDetailFields,
  MAX_EXTRA_VALUE_CHARS,
  type CardFieldConfig,
  type LeadExtra,
  type LeadSourceOption,
  type LeadFormValues,
} from './leads.shared';

// ─── Read-only contact row ────────────────────────────────────────────────────

function InfoRow({
  icon,
  label,
  children,
  copyText,
}: {
  icon: React.ReactNode;
  label: string;
  children: React.ReactNode;
  copyText?: string;
}) {
  return (
    <div className='flex items-start gap-2.5 py-2'>
      <span className='text-muted mt-0.5 shrink-0'>{icon}</span>
      <div className='min-w-0 flex-1'>
        <div className='text-[11px] uppercase tracking-wide text-muted'>{label}</div>
        <div className='text-sm break-words'>{children}</div>
      </div>
      {copyText && <CopyBtn text={copyText} />}
    </div>
  );
}


// ─── Panel ────────────────────────────────────────────────────────────────────

export function LeadDetailPanel({
  lead: incomingLead,
  statusConfigs,
  existingClientNames,
  onClose,
  onRefetch,
  onEmail,
  onSms,
  onConvert,
  onDelete,
}: {
  lead: Lead | null;
  statusConfigs: LeadStatusConfig[];
  existingClientNames: Set<string>;
  onClose: () => void;
  onRefetch: () => void;
  onEmail: (lead: Lead) => void;
  onSms: (lead: Lead) => void;
  onConvert: (lead: Lead) => void;
  onDelete: (lead: Lead) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [savingStatus, setSavingStatus] = useState<string | null>(null);
  const [savingSource, setSavingSource] = useState(false);
  const { data: sourceConfigs = [] } = useQuery(getLeadSourceConfigs);
  const sources = sourceConfigs as LeadSourceOption[];
  const [noteText, setNoteText] = useState('');
  const [savingNote, setSavingNote] = useState(false);
  const [deletingNoteId, setDeletingNoteId] = useState<string | null>(null);
  const [shown, setShown] = useState(false);
  // Keeps the last lead on screen while the panel slides back out.
  const [lead, setLead] = useState<Lead | null>(incomingLead);

  // Les champs libres déclarés pour le tableau de ce prospect. La fiche ne les
  // invente pas : elle remplit ce que « Cartes » (ou la correspondance) a déclaré,
  // sinon une information saisie ici ne pourrait jamais être étoilée.
  const boardId = (lead as any)?.searchId ?? null;
  const { data: cardFieldRows } = useQuery(
    getLeadCardFields,
    { searchId: boardId },
    { enabled: !!boardId } as any,
  );
  const allCardFields: CardFieldConfig[] = (cardFieldRows as CardFieldConfig[]) ?? [];
  const declaredExtras: CardFieldConfig[] = allCardFields.filter(f => isExtraFieldKey(f.key));

  const leadId = lead?.id ?? null;
  const identifier = (lead as any)?.placeId ?? leadId;
  const { data: notes = [], refetch: refetchNotes } = useQuery(
    getLeadNotes,
    { identifier },
    { enabled: !!identifier } as any,
  );

  // Must stay above the `if (!lead) return null` below: hooks cannot be called
  // conditionally, and this component renders with lead === null while closed.
  const { canSend: smsCanSend, reason: smsReason } = useSmsCapability();
  const { canSend: emailCanSend, reason: emailReason } = useEmailCapability();

  // Keep the rendered lead in sync with fresh data from the board.
  useEffect(() => {
    if (incomingLead) setLead(incomingLead);
  }, [incomingLead]);

  // Slide in when a lead is selected, slide out (then unmount) when cleared.
  useEffect(() => {
    if (incomingLead) {
      const t = window.setTimeout(() => setShown(true), 10);
      return () => window.clearTimeout(t);
    }
    setShown(false);
    const t = window.setTimeout(() => setLead(null), 200);
    return () => window.clearTimeout(t);
  }, [incomingLead?.id]);

  const [extrasDraft, setExtrasDraft] = useState<LeadExtra[]>([]);

  // Reset per-lead state when switching cards.
  useEffect(() => {
    setEditing(false);
    setNoteText('');
  }, [leadId]);

  // Ouvrir la fiche vaut « vu », et c'est ce qui annule l'alerte d'arrivée
  // (voir jobs/leadIntake) : changer le statut ne suffisait pas, on peut très
  // bien traiter un prospect sans le sortir de sa colonne.
  //
  // Piloté par `incomingLead?.id` et non par `leadId` : ce dernier reste garni
  // pendant les 200 ms de fermeture, et rejouerait l'appel à chaque sortie.
  //
  // Le tableau n'est rechargé que si l'ouverture était la première : c'est
  // exactement quand la pastille « jamais ouvert » doit disparaître de la carte.
  // Les consultations suivantes n'écrivent rien et ne rechargent rien.
  const openedId = incomingLead?.id ?? null;
  useEffect(() => {
    if (!openedId) return;
    (markLeadViewed as any)({ leadId: openedId })
      .then((res: any) => { if (res?.marked) onRefetch(); })
      .catch(() => undefined);
  }, [openedId]);

  // Escape closes the panel.
  useEffect(() => {
    if (!lead) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
    }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [lead, onClose]);

  const notesDirty = useRef(false);

  function handleClose() {
    if (notesDirty.current) {
      notesDirty.current = false;
      onRefetch();
    }
    onClose();
  }

  if (!lead) return null;

  const l = lead as any;
  const current =
    statusConfigs.find(s => s.key === lead.status) ??
    ({ label: lead.status, color: '#9ca3af', key: lead.status } as LeadStatusConfig);
  const alreadyClient = existingClientNames.has(lead.name.toLowerCase());

  async function handleStatus(key: string) {
    if (key === lead!.status) return;
    setSavingStatus(key);
    try {
      await updateLead({ id: lead!.id, status: key });
      onRefetch();
    } catch {
      toast.error('Erreur lors de la mise à jour du statut');
    } finally {
      setSavingStatus(null);
    }
  }

  async function handleSource(source: string) {
    if (source === (lead as any)!.source) return;
    setSavingSource(true);
    try {
      await updateLead({ id: lead!.id, source } as any);
      onRefetch();
    } catch {
      toast.error('Erreur lors de la mise à jour de la provenance');
    } finally {
      setSavingSource(false);
    }
  }

  const savedExtras = leadExtras(lead);

  /**
   * Une ligne par champ libre déclaré, garnie de la valeur du prospect s'il en a
   * une, suivie des valeurs orphelines.
   *
   * Orphelines = un champ retiré de la configuration depuis que ce prospect est
   * arrivé. Elles restent affichées et modifiables plutôt que d'être effacées au
   * premier enregistrement : le formulaire disait bien cela ce jour-là, et une
   * décision d'affichage prise après coup ne doit pas détruire la donnée.
   */
  function seedExtrasDraft(): LeadExtra[] {
    const byKey = new Map(savedExtras.map(e => [e.key, e]));
    const declared = declaredExtras.map(field => {
      const id = extraFieldId(field.key);
      const found = byKey.get(id);
      byKey.delete(id);
      return { key: id, label: field.label, value: found?.value ?? '' };
    });
    return [...declared, ...byKey.values()];
  }

  /** Les lignes à lire : les champs déclarés qui ont une valeur, puis les orphelines. */
  const visibleExtras = seedExtrasDraft().filter(e => e.value.trim().length > 0);

  /** Les champs que la fiche affiche, dans l'ordre réglé dans « Cartes ». */
  const detailFields = visibleDetailFields(allCardFields);

  /** Le rendu d'une ligne d'information, ou `null` si ce champ n'a rien à montrer. */
  function renderDetailRow(field: CardFieldConfig): React.ReactNode {
    const key = field.key;

    if (isExtraFieldKey(key)) {
      const extra = visibleExtras.find(e => e.key === extraFieldId(key));
      if (!extra) return null;
      return (
        <InfoRow key={key} icon={<LuInfo size={14} />} label={field.label} copyText={extra.value}>
          <span className='whitespace-pre-wrap'>{extra.value}</span>
        </InfoRow>
      );
    }

    if (key === 'phone') {
      return (
        <InfoRow key={key} icon={<LuPhone size={14} />} label={field.label} copyText={lead!.phone ?? undefined}>
          {lead!.phone ? (
            <a href={`tel:${lead!.phone}`} className='text-accent-700 hover:underline'>
              {lead!.phone}
            </a>
          ) : (
            <span className='text-muted'>—</span>
          )}
        </InfoRow>
      );
    }

    if (key === 'email') {
      return (
        <InfoRow key={key} icon={<LuMail size={14} />} label={field.label} copyText={lead!.email ?? undefined}>
          {lead!.email ? (
            <a href={`mailto:${lead!.email}`} className='text-accent-700 hover:underline'>
              {lead!.email}
            </a>
          ) : (
            <span className='text-muted'>Non trouvé</span>
          )}
        </InfoRow>
      );
    }

    if (key === 'website') {
      return (
        <InfoRow key={key} icon={<LuGlobe size={14} />} label={field.label} copyText={lead!.website ?? undefined}>
          {lead!.website ? (
            <a
              href={lead!.website}
              target='_blank'
              rel='noopener noreferrer'
              className='text-accent-700 hover:underline'
            >
              {lead!.website.replace(/^https?:\/\//, '').replace(/\/$/, '')}
            </a>
          ) : (
            <span className='text-muted'>—</span>
          )}
        </InfoRow>
      );
    }

    if (key === 'address') {
      return (
        <InfoRow key={key} icon={<LuMapPin size={14} />} label={field.label} copyText={lead!.address ?? undefined}>
          {lead!.address ?? <span className='text-muted'>—</span>}
        </InfoRow>
      );
    }

    if (key === 'category') {
      return (
        <InfoRow key={key} icon={<LuInfo size={14} />} label={field.label} copyText={(lead as any).category ?? undefined}>
          {(lead as any).category ?? <span className='text-muted'>—</span>}
        </InfoRow>
      );
    }

    if (key === 'rating') {
      return (
        <InfoRow key={key} icon={<LuStar size={14} />} label={field.label}>
          {lead!.rating != null ? (
            <span className='flex items-center gap-1.5'>
              <span className='flex items-center gap-1'>
                <LuStar size={12} className='text-amber-400 fill-amber-400' />
                <span className='font-medium'>{Number(lead!.rating).toFixed(1)}</span>
              </span>
              {lead!.reviewCount != null && lead!.reviewCount > 0 && (
                <span className='text-muted text-xs'>{lead!.reviewCount} avis</span>
              )}
              {lead!.mapsUrl && (
                <a
                  href={lead!.mapsUrl}
                  target='_blank'
                  rel='noopener noreferrer'
                  className='text-accent-700 hover:underline text-xs flex items-center gap-0.5'
                >
                  <LuExternalLink size={11} />
                  Maps
                </a>
              )}
            </span>
          ) : (
            <span className='text-muted'>—</span>
          )}
        </InfoRow>
      );
    }

    return null;
  }

  async function handleSaveInfo(values: LeadFormValues) {
    await updateLead({
      id: lead!.id,
      name: values.name || undefined,
      phone: values.phone || undefined,
      email: values.email || undefined,
      website: values.website || undefined,
      address: values.address || undefined,
      category: values.category || undefined,
      // Les lignes vides ne sont pas enregistrées : un champ déclaré mais non
      // rempli pour ce prospect n'est pas une valeur vide, c'est une absence.
      extras: extrasDraft.filter(e => e.value.trim().length > 0),
    } as any);
    toast.success('Prospect mis à jour');
    setEditing(false);
    onRefetch();
  }

  async function handleAddNote(e: React.FormEvent) {
    e.preventDefault();
    if (!noteText.trim()) return;
    setSavingNote(true);
    try {
      await addLeadNote({ leadId: lead!.id, text: noteText });
      setNoteText('');
      notesDirty.current = true;
      refetchNotes();
    } catch {
      toast.error('Erreur lors de l\'ajout');
    } finally {
      setSavingNote(false);
    }
  }

  async function handleDeleteNote(id: string) {
    setDeletingNoteId(id);
    try {
      await deleteLeadNote({ id });
      notesDirty.current = true;
      refetchNotes();
    } catch {
      toast.error('Erreur lors de la suppression');
    } finally {
      setDeletingNoteId(null);
    }
  }

  return (
    <>
      {/* Backdrop — mobile only, so the board stays draggable on desktop. */}
      <div
        className={`fixed inset-0 bg-ink/40 z-[34] sm:hidden transition-opacity ${
          shown ? 'opacity-100' : 'opacity-0'
        }`}
        onClick={handleClose}
      />

      {/*
        The panel itself is the scroll container (header and footer stay pinned
        with `sticky`), and `overscroll-contain` keeps the wheel from reaching
        the board underneath once the panel hits its end.
      */}
      <aside
        // pb-20 : la bulle de messagerie flotte au-dessus de ce coin, rien
        // d'utile ne doit finir sous un disque de 56 px.
        className={`fixed inset-y-0 right-0 z-[35] w-full sm:w-[380px] lg:w-[420px] pb-20 bg-white border-l border-line shadow-xl flex flex-col overflow-y-auto overscroll-contain transition-transform duration-200 ${
          shown ? 'translate-x-0' : 'translate-x-full'
        }`}
        role='dialog'
        aria-label={`Détails — ${lead.name}`}
      >
        {/* Header */}
        <div className='sticky top-0 z-10 shrink-0 bg-white px-5 py-4 border-b border-line'>
          <div className='flex items-start gap-2'>
            <div className='min-w-0 flex-1'>
              <h2 className='font-semibold text-base leading-tight break-words'>{lead.name}</h2>
              {lead.category && (
                <p className='text-xs text-muted capitalize mt-0.5'>{lead.category}</p>
              )}
            </div>
            <button
              onClick={handleClose}
              className='text-muted hover:text-ink shrink-0'
              aria-label='Fermer'
            >
              <LuX size={18} />
            </button>
          </div>

          {/* Status picker */}
          <div className='mt-3'>
            <div className='text-[11px] uppercase tracking-wide text-muted mb-1.5'>Statut</div>
            <div className='flex flex-wrap gap-1.5'>
              {statusConfigs
                .filter(s => s.key !== 'unknown' || s.key === lead.status)
                .map(s => {
                  const active = s.key === current.key;
                  return (
                    <button
                      key={s.key}
                      onClick={() => handleStatus(s.key)}
                      disabled={savingStatus !== null}
                      className='text-xs font-medium px-2.5 py-1 rounded-full border transition-colors flex items-center gap-1 disabled:opacity-60'
                      style={
                        active
                          ? { backgroundColor: s.color, borderColor: s.color, color: '#fff' }
                          : { backgroundColor: s.color + '14', borderColor: s.color + '44', color: s.color }
                      }
                    >
                      {savingStatus === s.key ? (
                        <LuLoader size={10} className='animate-spin' />
                      ) : active ? (
                        <LuCheck size={10} />
                      ) : null}
                      {s.label}
                    </button>
                  );
                })}
            </div>
          </div>

          {/* Provenance */}
          <div className='mt-3'>
            <div className='text-[11px] uppercase tracking-wide text-muted mb-1.5'>Provenance</div>
            <div className='flex items-center gap-2'>
              <span
                className='w-2 h-2 rounded-full shrink-0'
                style={{ backgroundColor: leadSourceColor(l.source as string, sources) }}
              />
              <select
                className='input py-1 text-xs w-auto'
                value={(l.source as string) ?? 'google_maps'}
                onChange={e => handleSource(e.target.value)}
                disabled={savingSource}
                title="D'où vient ce prospect"
              >
                {sources.map(s => (
                  <option key={s.key} value={s.key}>{s.label}</option>
                ))}
              </select>
              {savingSource && <LuLoader size={12} className='animate-spin text-muted' />}
            </div>
          </div>
        </div>

        {/* Body */}
        <div className='flex-1 px-5 py-4 space-y-5'>
          {l.duplicateSearchTitles?.length > 0 && (
            <div className='flex items-start gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-2.5 py-2'>
              <LuTriangleAlert size={13} className='shrink-0 mt-0.5' />
              <span>
                Déjà présent dans : {l.duplicateSearchTitles.join(', ')}
              </span>
            </div>
          )}

          {/* Contact info */}
          <section>
            <div className='flex items-center justify-between mb-1'>
              <h3 className='text-sm font-semibold'>Informations</h3>
              {!editing && (
                <button
                  className='text-xs text-accent-700 hover:underline flex items-center gap-1'
                  onClick={() => {
                    setExtrasDraft(seedExtrasDraft());
                    setEditing(true);
                  }}
                >
                  <LuPencil size={11} />
                  Modifier
                </button>
              )}
            </div>

            {editing ? (
              <LeadEditForm
                initialValues={{
                  name: lead.name,
                  phone: lead.phone ?? '',
                  email: lead.email ?? '',
                  website: lead.website ?? '',
                  address: lead.address ?? '',
                  category: lead.category ?? '',
                }}
                onSave={handleSaveInfo}
                onCancel={() => setEditing(false)}
                // Un champ retiré de la fiche n'a pas non plus à s'y modifier :
                // le formulaire proposerait sinon de remplir une valeur que rien
                // n'affiche ensuite.
                hiddenKeys={allCardFields
                  .filter(f => f.onDetail === false)
                  .map(f => f.key)}
                extraFields={
                  extrasDraft.length > 0 ? (
                    <>
                      {extrasDraft.map((line, i) => (
                        <div key={`${line.key}-${i}`} className='sm:col-span-2'>
                          <label className='label'>{line.label || 'Information'}</label>
                          <textarea
                            className='input'
                            rows={2}
                            value={line.value}
                            maxLength={MAX_EXTRA_VALUE_CHARS}
                            onChange={e =>
                              setExtrasDraft(d =>
                                d.map((l, j) => (j === i ? { ...l, value: e.target.value } : l)),
                              )
                            }
                          />
                        </div>
                      ))}
                    </>
                  ) : undefined
                }
              />
            ) : (
              <div className='divide-y divide-line'>
                {/* Les lignes d'information viennent du réglage « Cartes » et non
                    d'une liste figée : sur un tableau alimenté par formulaire, la
                    note Google ne peut rien valoir et n'avait aucune raison d'occuper
                    une ligne à vide. Un champ éteint quitte la fiche sans quitter la
                    base — le téléphone continue d'armer le bouton SMS. */}
                {detailFields.map(field => renderDetailRow(field))}
                <InfoRow icon={<LuClock size={14} />} label='Ajouté le'>
                  <span className='text-muted'>{formatMontrealTime(lead.createdAt)}</span>
                  {lead.statusUpdatedAt && (
                    <span className='block text-xs text-muted'>
                      Statut modifié le {formatMontrealTime(lead.statusUpdatedAt)}
                    </span>
                  )}
                </InfoRow>
              </div>
            )}
          </section>

          {/* Notes */}
          <section>
            <h3 className='text-sm font-semibold mb-2 flex items-center gap-1.5'>
              <LuNotebook size={13} className='text-muted' />
              Notes
              {(notes as any[]).length > 0 && (
                <span className='text-xs text-muted font-normal'>({(notes as any[]).length})</span>
              )}
            </h3>
            <NoteThread
              notes={notes as any[]}
              text={noteText}
              setText={setNoteText}
              onSubmit={handleAddNote}
              onDelete={handleDeleteNote}
              saving={savingNote}
              deletingId={deletingNoteId}
              autoFocus={false}
              scrollable={false}
            />
          </section>
        </div>

        {/* Footer actions */}
        <div className='sticky bottom-0 z-10 shrink-0 px-5 py-3 border-t border-line bg-canvas-100 flex items-center gap-2'>
          {/* Like the SMS button: the label stays put and the state shows in the
              colour — green once sent, amber while a draft is waiting. */}
          <button
            className={`gap-1.5 text-sm flex-1 justify-center ${
              !emailCanSend
                ? 'btn-secondary'
                : l.hasEmailSent
                  ? 'btn-secondary text-success'
                  : l.hasEmailDraft
                    ? 'btn-secondary text-amber-600'
                    : 'btn-primary'
            }`}
            onClick={() => onEmail(lead)}
            disabled={!lead.email || !emailCanSend}
            title={
              !emailCanSend
                ? (emailReason ?? '')
                : !lead.email
                  ? 'Aucun courriel pour ce prospect'
                  : l.hasEmailSent
                    ? 'Déjà contacté — écrire un nouveau courriel'
                    : l.hasEmailDraft
                      ? 'Brouillon en cours — cliquer pour reprendre'
                      : 'Envoyer un courriel'
            }
          >
            <LuSend size={14} />
            Courriel
          </button>
          <button
            className={`btn-secondary gap-1.5 text-sm relative ${l.hasSmsSent && smsCanSend ? 'text-success' : ''}`}
            onClick={() => onSms(lead)}
            disabled={!lead.phone || !smsCanSend}
            title={
              !smsCanSend
                ? (smsReason ?? '')
                : !lead.phone
                  ? 'Aucun téléphone pour ce prospect'
                  : l.smsUnreadCount
                    ? `${l.smsUnreadCount} réponse(s) non lue(s)`
                    : 'Envoyer un SMS'
            }
          >
            <LuMessageSquare size={14} />
            SMS
            {smsCanSend && l.smsUnreadCount > 0 && (
              <span className='ml-0.5 min-w-[16px] h-4 px-1 rounded-full bg-accent-500 text-white text-[10px] font-semibold flex items-center justify-center'>
                {l.smsUnreadCount}
              </span>
            )}
          </button>
          {lead.status === 'qualifie' &&
            (alreadyClient ? (
              <span
                className='btn-secondary gap-1.5 text-sm opacity-60 cursor-default'
                title='Déjà ajouté comme client'
              >
                <LuUserCheck size={14} />
                Client
              </span>
            ) : (
              <button
                className='btn-secondary gap-1.5 text-sm'
                onClick={() => onConvert(lead)}
                title='Créer un client depuis ce prospect'
              >
                <LuUserPlus size={14} />
                Client
              </button>
            ))}
          <button
            className='btn-danger gap-1.5 text-sm'
            onClick={() => onDelete(lead)}
            title='Supprimer ce prospect'
          >
            <LuTrash2 size={14} />
          </button>
        </div>
      </aside>
    </>
  );
}
